### ISSUE TITLE
File browser instead of text input fields

### ISSUE THREAD

**Issue by jimlei** [jfurrow/flood#108]
Would be nice to have a file browser instead of having to manually enter the paths. Something like this

![image](https://cloud.githubusercontent.com/assets/4523053/17645870/3840d57e-61b2-11e6-82f9-96ad872df3b0.png)

**Comment by jfurrow** [comment]
I agree and definitely plan to add something like this.

**Comment by jfurrow** [comment]
@jimlei This was implemented in https://github.com/jfurrow/flood/pull/182, let me know what you think!
