### ISSUE TITLE
Edit text in readme regarding config.secret (Bcrypt -> JWT)

### ISSUE THREAD

**Issue by jimlei** [jfurrow/flood#114]
> Create a long, unique secret (used by bcrypt to hash passwords) in config.js.

As far as I can see this is not used for Bcrypt hashing (which is a good thing) - but for JWT token creation. It might seem trivial but I'd suggest changing the text. I almost skipped the repo because I'm scared of custom implementations of Bcrypt.

```js
// flood/server/models/Users.js
    bcrypt.genSalt(10, (err, salt) => {
      if (err) {
        return callback(null, err);
      }

      let username = credentials.username;

      bcrypt.hash(credentials.password, salt, null, (err, hash) => {
        if (err) {
          return callback(null, err);
        }

        this.db.insert({username: username, password: hash}, (err, user) => { 
```

```js
// flood/server/routes/auth.js
      let token = jwt.sign(credentials, config.secret, {
        expiresIn: expirationSeconds
      });
```

**Comment by jfurrow** [comment]
Great point, fixed in #115. Not sure what I was thinking...
