### ISSUE TITLE
[FreeBSD] flood exits with Exit code 1

### ISSUE THREAD

**Issue by piperun** [jfurrow/flood#12]
I'm kind of new to both node.js and flood, but on my test machine, it seems to not being able to run since it gives me this rather cryptic error message:

```
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_proce
ss.js:211:5)                                                                    
10 verbose pkgid flood@0.0.0                                                    
11 verbose cwd /usr/home/nodejs/flood-master                                    
12 error FreeBSD 9.3-RELEASE-p31                                                
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"                
14 error node v4.4.1                                                            
15 error npm  v2.14.7                                                           
16 error code ELIFECYCLE                                                        
17 error flood@0.0.0 start: `npm prune && npm install && ./node_modules/.bin/gul
p dist && nodemon ./server/bin/www`                                             
17 error Exit status 1                                                          
18 error Failed at the flood@0.0.0 start script 'npm prune && npm install && ./n
ode_modules/.bin/gulp dist && nodemon ./server/bin/www'.                        
18 error This is most likely a problem with the flood package,                  
18 error not with npm itself.                                                   
18 error Tell the author that this fails on your system:                        
18 error     npm prune && npm install && ./node_modules/.bin/gulp dist && nodemo
n ./server/bin/www                                                              
18 error You can get their info via:                                            
18 error     npm owner ls flood                                                 
18 error There is likely additional logging output above.                       
19 verbose exit [ 1, true ]                                                     
                                                                                         

```

Also when I did npm start > file I got this output from gmake:
                                                                                
```
` /usr/home/nodejs/flood-master/node_modules/gulp-sass/node_modules/node-sass/ve
ndor/freebsd-x64-47/binding.node ` exists.                                      
 testing binary.                                                                
Problem with the binary.                                                        
Manual build incoming.                                                          
Building: /usr/local/bin/node /usr/home/nodejs/flood-master/node_modules/gulp-sa
ss/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbos
e --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=        
gmake: Entering directory '/usr/home/nodejs/flood-master/node_modules/gulp-sass/
node_modules/node-sass/build'                                                   
  c++ '-DNODE_GYP_MODULE_NAME=libsass' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BIT
S=64' '-DLIBSASS_VERSION="3.3.2"' -I/root/.node-gyp/5.9.1/include/node -I/root/.
node-gyp/5.9.1/src -I/root/.node-gyp/5.9.1/deps/uv/include -I/root/.node-gyp/5.9
.1/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-u
nused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-omit-frame-poi
nter -std=gnu++0x -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Releas
e/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libs
ass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp                            
src/libsass.target.mk:136: recipe for target 'Release/obj.target/libsass/src/lib
sass/src/ast.o' failed                                                          
gmake: Leaving directory '/usr/home/nodejs/flood-master/node_modules/gulp-sass/n
ode_modules/node-sass/build'                                                    
                                                                                
```

**Comment by piperun** [comment]
I also noticed that this happens on AlpineLinux, but runs fine on Ubuntu Server.

**Comment by piperun** [comment]
I've further nailed it down to it showing:

`GET /client/torrents 500 11.004 ms - 2`

**Comment by jfurrow** [comment]
Thanks for filing the issue! I'm not sure what's going on here but I'll investigate. I'm installing FreeBSD on a VM right now to test it out myself.

**Comment by jfurrow** [comment]
While I'm setting this up, can you see if there are any errors in your browser's console when you access the instance running on Ubuntu Server?

**Comment by jfurrow** [comment]
For what it's worth, I was able to get the node app running on FreeBSD 10.3 with Node 5.9.1 and NPM 2.14.7. I have not installed rTorrent on this VM yet, but the app is running. What versions of FreeBSD, Node, and NPM were you trying, out of curiosity?

Next I'll try to duplicate the issue you found with Ubuntu Server.

**Comment by piperun** [comment]
No problem, I was running FreeBSD 9.3-RELEASE-p31 (FreeNAS version) inside a jail, where I tested the pkgng version (which was the latest 5.9.x and NPM 2.14.7) and the Node4 version found in the /usr/ports/www/node4 catalogue.

Both failed at the same step.

Also I am not sure if I should be running flood as root or as a normal user, I tried with both and both failed.

With Ubuntu, I found the following from the console:

```
Object { data: "", status: 0, statusText: "", headers: Object, config: Object } app.js:21015:8
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create app.js:19767:416
GET 
XHR 
http://192.168.1.240:3000/client/torrents [HTTP/1.1 500 Internal Server Error 52ms]
Object { data: Object, status: 500, statusText: "Internal Server Error", headers: Object, config: Object } app.js:22127:8
undefined app.js:23466:8
```

**Comment by jfurrow** [comment]
I run Flood on Ubuntu (this is my torrent server) as a normal user. It works both as root and normal for me, so I'm struggling to figure out what could be causing the `500` errors.

I just pushed a small commit that will trace the origin of the `500` error you're receiving. Could you please try this again and let me know what output you see in the terminal? I just added some simple error tracing to see what's causing the problem.

As for the compilation errors you received on AplineLinux and FreeBSD, it seems you're missing some packages that are required for installing `gulp-sass`, which is a small wrapper for `node-sass`, which itself is a wrapper for `libsass`, which is written in C. Are you able to compile other C packages on these operating systems? Maybe [this AlpineLinux wiki page](http://wiki.alpinelinux.org/wiki/Running_glibc_programs) would be helpful?

I'm sorry your first experience with Flood has been so terrible!

**Comment by piperun** [comment]
It's fine, after all it's part of the joy when dealing with software. :-)

Unfortunately I am very busy and will not be able to post results until much later.

I think the problem with both Alpine and FreeBSD is that they don't use glibc (as you said), but I might be wrong when it comes to FreeBSD.

**Comment by jfurrow** [comment]
No worries. Thanks for opening the issue! I'll put more effort into cross platform support, possibly by removing the dependency on libsass entirely.

**Comment by gretel** [comment]
working fine for me on `10-stable`:
```
$ sudo pkg install node npm
$ git clone --depth 1 https://github.com/jfurrow/flood
$ npm start
```

**Comment by piperun** [comment]
@jfurrow thank you so much for your patient! I don't know what you manage to do but on my testbed (Ubuntu) machine, it now works.

I will have to wait and see if it works in production.

**Comment by thde** [comment]
Just FYI flood works fine for me on Alpine Linux 3.4 and with the nodejs-lts package.

**Comment by piperun** [comment]
@thde that could've been it that I did not use the lts version.

**Comment by jfurrow** [comment]
Thanks for the followup, everyone! I really appreciate it. Glad to hear it's working more reliably. I'm going to close this, but please make another if you have any other problems!
