### ISSUE TITLE
Firefox error

### ISSUE THREAD

**Issue by pmwoodward3** [jfurrow/flood#131]
The stylesheet http://localhost:3000/style.css was not loaded because its MIME type, "text/html", is not "text/css".localhost:3000

SyntaxError: expected expression, got '<'

White page when viewing Flood on firefox.

**Comment by Embraser01** [comment]
Same issue [here ](https://github.com/jfurrow/flood/issues/129), I give a fix ;)

**Comment by jfurrow** [comment]
This is fixed in https://github.com/jfurrow/flood/pull/132
