### ISSUE TITLE
Different rtorrent config for different users.

### ISSUE THREAD

**Issue by Daiyousei** [jfurrow/flood#147]
Hello. it would be nice to define different rtorrent config (host/port) associated to differents users.
We could use the same Flood server to connect differents instances of rtorrent.

**Comment by jfurrow** [comment]
I agree, I think this would be the best way to handle multiple users. Honestly it's not a high priority right now, but I would like to add it in the future.

**Comment by jfurrow** [comment]
Let's move this discussion to #216
