### ISSUE TITLE
! + red : what does it mean ?

### ISSUE THREAD

**Issue by Angristan** [jfurrow/flood#153]
Hello,

I wonder why some torrents are red : 
![screenshot_24-10-2016_b 6moz9dhe](https://cloud.githubusercontent.com/assets/11699655/19663559/d0926d7a-9a3c-11e6-850b-f91f20f0dea2.png)

What does it mean ?

**Comment by Angristan** [comment]
BTW if I stop and then start the torrent, it get back to blue.

**Comment by jfurrow** [comment]
Sorry for the delay — the exclamation point icon and red torrent is the error state. Flood determines a torrent has an error by looking for a value returned from the `d.message` method call to rTorrent. AFAIK this is how ruTorrent determines errors also.

You can see the error message by opening the torrent details modal and looking at the value for "message."
