### ISSUE TITLE
Uploads slots bug

### ISSUE THREAD

**Issue by Angristan** [jfurrow/flood#154]
Hello,

I set this in my conf : 
![screenshot_24-10-2016_b kcug-cri](https://cloud.githubusercontent.com/assets/11699655/19664556/44574b00-9a41-11e6-9bec-c85f60e1c785.png)

But it's seeding to more than 20 peers per torrent : 

![screenshot_24-10-2016_b hzjntv6s](https://cloud.githubusercontent.com/assets/11699655/19664550/3bd34330-9a41-11e6-9ed4-59207db6e235.png)

Do I do something wrong ? :/

BTW, what is "upload slot divider" ?

**Comment by jfurrow** [comment]
This is a value used by rTorrent, Flood just allows you to adjust it. "Upload Slots Per Torrent" is supposed to do what it sounds like, according to this entry in the rTorrent wiki: https://github.com/rakshasa/rtorrent/wiki/Performance-Tuning

I honestly don't understand what the divider does (the key in rTorrent is called `throttle.max_uploads.div`). Here's a vague explanation: https://github.com/rakshasa/rtorrent/blob/master/doc/old/rtorrent.1#L343-L345
