### ISSUE TITLE
Wrong download speed

### ISSUE THREAD

**Issue by Angristan** [jfurrow/flood#155]
Hello,

Flood tells it's downloading at a very low speed, however all my torrents are finished : 
![screenshot_24-10-2016_b 87hgkhz6](https://cloud.githubusercontent.com/assets/11699655/19664677/d8bcc9c8-9a41-11e6-9a3b-b0c1371cfac7.png)

Why ? Is it related to the trackers ?

**Comment by jfurrow** [comment]
This is the value reported by rTorrent, I'm assuming it's the overhead of communicating with trackers and peers.
