### ISSUE TITLE
Idea : Add the possibility to unselect a torrent

### ISSUE THREAD

**Issue by Angristan** [jfurrow/flood#156]
When you click on a torrent, it's highlighted in blue.

However it is not possible to unselect it. I would be great for an improved visibility. For now, you have to refresh the page to not have any torrent highlighted.

What do you think ?

**Comment by jfurrow** [comment]
Yeah, I agree this should be possible!

**Comment by Angristan** [comment]
Oh thanks !

**Comment by jeremejevs** [comment]
@jfurrow Clicking elsewhere on the page should reset the selection too, IMO (except for the buttons which operate on the selection). Do you have a specific reason for not adding that? Or "PRs are welcome"?

**Comment by noraj1337** [comment]
@jeremejevs PRs are always welcome but open a discussion issue before creating some code.
