### ISSUE TITLE
Idea : select multiple torrents at once

### ISSUE THREAD

**Issue by Angristan** [jfurrow/flood#157]
It would be much easier when doing a mass delete for exemple.

**Comment by jfurrow** [comment]
This is already possible. You can select multiple torrents by holding command/control (mac/others), or you can select a range of torrents by selecting one, then holding shift and clicking another.

**Comment by Angristan** [comment]
This is so obvious haha, thank you

**Comment by jfurrow** [comment]
@Angristan no problem! Thanks for the issues! Sorry for the delay, I'm not being notified about closed issues... need to check my Github notification settings.
