### ISSUE TITLE
Torrent are not added

### ISSUE THREAD

**Issue by Angristan** [jfurrow/flood#164]
Sometimes, when adding torrent it just does not work : 
![screenshot_01-11-2016_b gy7z9qpo](https://cloud.githubusercontent.com/assets/11699655/19910385/de2f5456-a08c-11e6-9ced-0d832d85f15e.png)

If I add multiple torrents, I will stay on the "Add Torrents" window, but the other torrents will be added.

Here is what nodejs tells us : 
```
Trace: { [Error: XML-RPC fault: Call XML not a proper XML-RPC call.  Call is not valid XML.  Invalid XML "content".  Problem with token at '<...': unclosed token]
  code: -503,
  faultCode: -503,
  faultString: 'Call XML not a proper XML-RPC call.  Call is not valid XML.  Invalid XML "content".  Problem with token at \'<...\': unclosed token' }
    at ClientRequest.onCompleteFn (/srv/seedbox/flood/server/util/ajaxUtil.js:7:17)
    at ClientRequest.handleError (/srv/seedbox/flood/server/models/ClientRequest.js:69:12)
    at _rejected (/srv/seedbox/flood/node_modules/q/q.js:844:24)
    at /srv/seedbox/flood/node_modules/q/q.js:870:30
    at Promise.when (/srv/seedbox/flood/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/srv/seedbox/flood/node_modules/q/q.js:788:41)
    at /srv/seedbox/flood/node_modules/q/q.js:604:44
    at runSingle (/srv/seedbox/flood/node_modules/q/q.js:137:13)
    at flush (/srv/seedbox/flood/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:420:9)
POST /api/client/add-files 500 30.530 ms - 178

```

**Comment by jfurrow** [comment]
Thanks for the issue, I've not seen this before.

Are you adding torrents by URLs or by uploading the torrent files?

**Comment by Angristan** [comment]
In this case it's files, but I think it already happened with magnet, I'm not sure anymore

**Comment by Flyy-y** [comment]
Hey, i'm getting the same issue, only with some torrents, adding with files.
![flood2](https://cloud.githubusercontent.com/assets/7773641/20032465/b7e672e2-a38a-11e6-8498-80fbdf8646b9.png)
![flood1](https://cloud.githubusercontent.com/assets/7773641/20032468/be8050b4-a38a-11e6-8852-23aa0fbc5064.png)

**Comment by jfurrow** [comment]
@Angristan Flyy-y could either of you provide an example of a torrent that exhibits this behavior? I can't seem to reproduce :(

**Comment by Angristan** [comment]
If I find one again, I'll post here

**Comment by jfurrow** [comment]
Thanks. I almost exclusively add torrents via URL but I'll start downloading them to try to reproduce.

**Comment by WonderWheel** [comment]
I've got the same problem when i add torrent...

 ```
Trace: { [Error: XML-RPC fault: Call XML not a proper XML-RPC call.  Call is not valid XML.  Invalid XML "content".  Problem with token at '<...': unclosed token]
  code: -503,
  faultCode: -503,
  faultString: 'Call XML not a proper XML-RPC call.  Call is not valid XML.  Invalid XML "content".  Problem with token at \'<...\': unclosed token' }
```

It is private torrent so i can't share you.

**Comment by WonderWheel** [comment]
I've got the same problem when i add torrent...

 ```
Trace: { [Error: XML-RPC fault: Call XML not a proper XML-RPC call.  Call is not valid XML.  Invalid XML "content".  Problem with token at '<...': unclosed token]
  code: -503,
  faultCode: -503,
  faultString: 'Call XML not a proper XML-RPC call.  Call is not valid XML.  Invalid XML "content".  Problem with token at \'<...\': unclosed token' }
```

It is private torrent so i can't share you.

**Comment by HarryLafranc** [comment]
I had this issue with all my torrents files containing accents or strange characters (like °, or ç, etc). Renaming the torrent file with a simple name resolved this !

Hope it helps :)

**Comment by Angristan** [comment]
Another problem with [this torrent](https://file.quad.moe/Westworld_1973_BDRip_1080p_DTS_multi-_HighCodePH.torrent). Renaming the file didn't help
```
Trace: { [Error: XML-RPC fault: Call XML not a proper XML-RPC call.  XML-RPC request too large.  Max allowed is 524288 bytes]
  code: -503,
  faultCode: -503,
  faultString: 'Call XML not a proper XML-RPC call.  XML-RPC request too large.  Max allowed is 524288 bytes' }
    at /srv/seedbox/flood/server/util/ajaxUtil.js:7:17
    at ClientRequest.onCompleteFn (/srv/seedbox/flood/server/models/client.js:48:11)
    at ClientRequest.handleError (/srv/seedbox/flood/server/models/ClientRequest.js:59:12)
    at _rejected (/srv/seedbox/flood/node_modules/q/q.js:844:24)
    at /srv/seedbox/flood/node_modules/q/q.js:870:30
    at Promise.when (/srv/seedbox/flood/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/srv/seedbox/flood/node_modules/q/q.js:788:41)
    at /srv/seedbox/flood/node_modules/q/q.js:604:44
    at runSingle (/srv/seedbox/flood/node_modules/q/q.js:137:13)
    at flush (/srv/seedbox/flood/node_modules/q/q.js:125:13)
POST /api/client/add-files 500 19.145 ms - 139

```

**Comment by jfurrow** [comment]
@Angristan You can increase the allowed size of XML RPC commands with the this setting in your `rtorrent.rc` file: `network.xmlrpc.size_limit.set = 2000000` (this is approx 2MB)

**Comment by jfurrow** [comment]
@HarryLafranc @Flyy-y @Angristan The issue with torrent filenames was fixed by https://github.com/jfurrow/flood/pull/196. Thanks for your patience!

**Comment by beadon** [comment]
@jfurrow - I think the xmlrpc size limit is causing a lot of weird errors for everyone.  Can I request that the UI report some kind of error to the user to tune this parameter if it's not set ?

**Comment by jfurrow** [comment]
@beadon Yeah that's a good idea, can you create an issue for that?
