### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by duvholt** [jfurrow/flood#174]
Any plans to add websockets support instead of polling?

**Comment by jfurrow** [comment]
I don't have any plans in the near future, but I do agree it would be better!

**Comment by jfurrow** [comment]
@duvholt I should add that I'd gladly accept a PR which converts the current polling implementation with websockets :)

**Comment by duvholt** [comment]
@jfurrow I might look into it. A bit busy with exams at the moment. :smile:
