### ISSUE TITLE
Torrents are download in "undefined" directory

### ISSUE THREAD

**Issue by mbothorel** [jfurrow/flood#175]
Hello,

First, I would like to thank you for Flood. :)

I have an issue. When I add a torrent, it download it in ~/undefined/ directory. I can see the directory I configure in resources settings, it is the one I put in my .rtorrent.rc file. 
I'm using Debian Jessie and rtorrent 0.9.2-1

How can I help or what informations do you need ?

Thanks.

**Comment by mbothorel** [comment]
Well, it seems Flood puts torrents in default directory now. When I add a torrent, the destination displayed is my default dir.

In order to avoid such problems, is it possible to download torrents in default directory, even if no directory is specified ?

**Comment by jfurrow** [comment]
Agreed, this should be handled better. It happens when the destination directory is empty.
