### ISSUE TITLE
Notifications not initialising

### ISSUE THREAD

**Issue by linus-dev** [jfurrow/flood#184]
I saw a previously 'closed' but, however this issue is still occurring for me.
Notifications are not initialising, that seems to be the only problem, not quite sure what you need me to provide. Should be able to disable them or at least not limit the usage entirely based on notifications loading.
I fixed it by clearing notifcations.db in ./server/db

**Comment by jfurrow** [comment]
Hey @linus-dev, I'm really sorry this is still happening and thanks for creating the issue. Just for my own sanity, are you 100% certain you're on `master` and pulled the latest from Github?

If you're fully up-to-date and just want to use Flood immediately, you can delete lines 87 to 93 in `client/scripts/components/Sidebar/NotificationsButton.js`: https://github.com/jfurrow/flood/blob/master/client/scripts/components/Sidebar/NotificationsButton.js#L87-L93

I may have figured out what's causing the bug and will have a fix up ASAP (probably 24hrs or so). But honestly this has been a little tricky to debug. The closest I can get to reproducing is intentionally return a malformed response from the `/notifications` endpoint, and I can see a problem here, but I'm not entirely sure it's what you're running into.

Anyway, bear with me, I'll have this resolved ASAP. I don't think it's a good idea to make these UI dependencies optional, they just shouldn't be buggy like this.

**Comment by linus-dev** [comment]
Yeah I pulled latest before posting.

**Comment by JonesN7** [comment]
Want to confirm I am also getting this bug on master. Let me know if there is anything I can provide that would be of help.

**Comment by jfurrow** [comment]
@linus-dev @JonesN7 I'm fairly certain this is fixed in https://github.com/jfurrow/flood/pull/186. Could one of you please verify? Check out branch `bug/fix-notifications-tooltip`

If nobody is available to verify the fix, I'll just merge this in the next 24 hours as I am 99% sure this fixes the bug you encountered.

**Comment by linus-dev** [comment]
@jfurrow It actually initialise properly when I launch it now, I believe it is working properly now, thank you!

**Comment by jfurrow** [comment]
@linus-dev Great! I'll merge that PR and close this. Thanks for testing it!
