### ISSUE TITLE
possible feature: Compact view

### ISSUE THREAD

**Issue by Porco-Rosso** [jfurrow/flood#190]
Hi, firstly amazing job. Not only was flood a breeze to set up, it looks absolutely beautiful! 
The only thing missing is some of the more advanced features of rutorrents' plugins. But i'm sure those are to come.

If you would consider it, I would like to suggest a "compact" list view.
For instance I have a lot of torrents, and it's hard to get a good overview seeing how much vertical space each torrent takes up. 
A toggle to shrink them to just the titles and maybe the status on the far right, would be ideal.
Keep up the great work!

**Comment by jfurrow** [comment]
Thanks for the kind words! I definitely agree that this is necessary and will be adding it soon™. It will likely exist (at least initially) as an option in the User Interface section of the settings.

**Comment by Porco-Rosso** [comment]
Sure I'll add the features I'd like to see first as other issues

**Comment by scoobynz** [comment]
+1 for compact view

**Comment by jfurrow** [comment]
@scoobynz I agree! It's currently in the design phase :)

**Comment by Porco-Rosso** [comment]
https://github.com/jfurrow/flood/pull/233
I see you've implemented the feature, thanks!

**Comment by jfurrow** [comment]
It's finally done, thanks for your patience! Let me know what you think. :)

**Comment by scoobynz** [comment]
Awesome. Much more usable now. Keep up the good work :-)
