### ISSUE TITLE
Unable to view list in Safari

### ISSUE THREAD

**Issue by gcrevell** [jfurrow/flood#191]
The list of current torrents never appears when viewed in Safari. I can view the list page but it shows nothing in the list as if I had no torrents. The numbers under the different status groups is correct. But no list. Any idea why or how to fix?

**Comment by jfurrow** [comment]
Thanks for the issue! It's probably a relatively simple styling bug, I'll try to get to it ASAP.

**Comment by jfurrow** [comment]
This is fixed by https://github.com/jfurrow/flood/pull/193
