### ISSUE TITLE
How to directly load a torrent in Flood from Firefox ?

### ISSUE THREAD

**Issue by Spheerys** [jfurrow/flood#192]
Hi,
Is there an addon for firefox to load torrent file directly fron my browser to my flood instance ?

**Comment by jfurrow** [comment]
There is not. I honestly don't plan to do this, unless a lot of people think it would be helpful. Even then, it would be a ways off; there are a lot of other features I'd like to build that I think are more important.

Sorry, and thanks for the issue!
