### ISSUE TITLE
No option to get the downloaded files via browser

### ISSUE THREAD

**Issue by loskutov** [jfurrow/flood#203]
Some other rtorrent web interfaces (such as pyrt) allow to download the files to your machine with browser. This seems to be a useful (and not hard to implement) feature.

**Comment by Porco-Rosso** [comment]
Agreed, If you are going to implement this, please allow the downloading of folders as well.
these might be a good place to start:
https://stuk.github.io/jszip/
https://github.com/sindresorhus/multi-download

**Comment by jfurrow** [comment]
Agreed, this is needed.
