### ISSUE TITLE
few features request

### ISSUE THREAD

**Issue by xiayyu** [jfurrow/flood#204]
* fast resume when add torrent (skip checking hash for downloaded torrent)
* ~~set tag when add torrent~~ (Done in #248)
* ~~more convenient way to prompt torrent details, perhaps double clicks on torrent list, rather than a small icon on the right.~~ (Done in #247)

I have tested flood for two days, truly fond of it. I basically need a local GUI for rtorrent but the config of php and nginx of rutorrent really fucked me up. Flood makes it more simple and wish I can contribute a little to improve it.

**Comment by varyoo** [comment]
I would like to add to this list the following:
* a field in `config.js` to set the default umask (when Flood creates folders, moves files...), simillar to `system.umask.set` in [rtorrent.rc](https://github.com/rakshasa/rtorrent/blob/master/src/command_local.cc#L267)

**Comment by jfurrow** [comment]
Thanks for the kind words and feature requests @xiayyu and @varyoo! It would be helpful if you could create separate issues for these. I'll leave this open until then.

I do agree with all of your options, just need to prioritize them and the time to implement them...

**Comment by varyoo** [comment]
What about replacing the double click (which is nice) by a single click on the highlighted torrent?

**Comment by jfurrow** [comment]
Sorry @varyoo but I think the UX on that will be a little strange; I don't think users would expect that to happen.

**Comment by jfurrow** [comment]
I'm going to create a separate issue for the fast resume feature and close this issue. Feel free to open new issues for other feature requests!
