### ISSUE TITLE
Sequential download

### ISSUE THREAD

**Issue by RokenTroll** [jfurrow/flood#206]
Have you planned to add an option to download in sequential mode? As in Tixati for example ?

**Comment by DavePS** [comment]
@jfurrow This is not possible with rTorrent.

**Comment by noraj1337** [comment]
Sequential download is only helpful if you want to begin to stream a media (for exampel a video) before the download of the torrent is fully completed. On a seedbox a torrent is usually download in a few seconds and running rTorrent somewhere else than in a seedbox is a weird thing.
Furthermore, sequential download is not very good for the bittorrent network.

So this feature is really not a priority at all.

**Comment by bbashy** [comment]
Agreed. Time to close this as it's not supported in rTorrent (still).

Can build it yourself with this change from gist: https://gist.github.com/sormy/25404b53872e44f035cf204dfe14aae6 which is used in https://gist.github.com/sormy/587dd7652a6d2281d8eeb31df5adf085
