### ISSUE TITLE
default download directory not automaticaly set when adding a torrent

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#210]
When adding a new torrent.

If **destination** is let as default (`\`) and then you start the torrent. The torrent won't begin to be downloaded.

If you check torrent location you can see that the value is `undefined`.

This is not normal because a **default download directory** is set in **settings** > **ressources** > **disk**. Value was `/home/user/torrents`.

Then if you right click on those torrents, click **torrent location**, enter `/home/user/torrents` and press **set location**, torrents begin to dowload.

So the default download directory is not automaticaly set when adding a torrent and not specifing a download location.

**Comment by jfurrow** [comment]
Thanks @noraj1337 I'll fix this ASAP>

**Comment by jfurrow** [comment]
Closed by #242
