### ISSUE TITLE
Contextual menu disappear if not hover over

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#211]
Using Firefox 50.1.0, when right clicking on a torrent and instantly releasing the button, the contextual menu disappear.

![](https://i.imgur.com/6GkRhpc.gif)

But if I right click on a torrent and then I hover over iI can release the mouse and the contextual menu doesn't disappear.

![](https://i.imgur.com/Cuo2aU7.gif)

Sorry for the screencast glitches (when you see my background).

**Comment by noraj1337** [comment]
This bug happens with Firefox 50.1.0 on Linux.
But yeaterday I used Firefox Developer Edition 52.0a on Windows and it was working.
I don't know if it can help you.

**Comment by jfurrow** [comment]
Fixed by #226, sorry for the delay.

**Comment by noraj1337** [comment]
@jfurrow : works fine now, thanks
