### ISSUE TITLE
[Request] Detailed list design

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#213]
## Request

It could be great if you add an additionnal detailed list view and let user the possibility to switch between the current view (actuall flat design) and a detailed list view.

Here an example of a detailed list view (from ruTorrent):

![](http://i.imgur.com/842HPOU.png)

Here is the actual design for teh same torrent:

![](http://i.imgur.com/ewPowIk.png)

## Why?

The actual design is very beautiful and nice but when you have to manage lot of torrents (ex: more than 40) you want to be able to see a lot of them on the same page withotu scrolling.
Whit the actual design you can hardly stack more than 11 torrents on teh same page. On my screenshot the actual design take 51.7 + 2*10 = 71.7 px height for a sing torrent.
Instead of that the detailed view of ruTorrent is only taking 22 px per torrent. So we can stack 3.25 times more torrent in the same area with ruTorrent (withotu counting the interface).

With the detailed view we should be able to sort torrent by column directly by clicking on them, and sort them increasingly or decreasingly by click an additionnal time on the column.

I talked about ruTorrent because it is also a web interface for rTorrent but I could have talk about Nemo or Thunar files explorers that have a similar detailed view.

**Comment by jfurrow** [comment]
@noraj1337 I totally agree, this is coming soon! It's in the design phase now.

**Comment by noraj1337** [comment]
@jfurrow amazing work
