### ISSUE TITLE
Add support for labels when adding torrents

### ISSUE THREAD

**Issue by onedr0p** [jfurrow/flood#218]
I would love to use this daily but lack of supports for labels is holding me back. When I add a torrent I would like to set the label and I would also like to be able to filter the list by labels. 

This app looks beautiful by the way.

Thanks.

**Comment by onedr0p** [comment]
Part of this feature would be to query for the existing labels and letting the user choose, or add a new one.

**Comment by noraj1337** [comment]
There is already label suppor.
Currently you can't add a label when adding a torrent. But once the torrent is added you can right click and then *add tags*. ANd of course you can filter by tags.

**Comment by noraj1337** [comment]
Some questions are (as there is no documentation):
- does a torrent support multiple tags ?
- if yes, how to delimit them, example: a comma `,` ?

**Comment by onedr0p** [comment]
Ah, I missed that. Also, I don't think there is multi label support in rtorrent.

**Comment by jfurrow** [comment]
@noraj1337 Yes, you can set multiple labels by providing a comma delimited string. I agree that you should be able to add labels when adding a torrent, so I'll use this issue to track it (unless there's an earlier request for this open...)
