### ISSUE TITLE
Floud reset after crash

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#220]
Floud crashed for a reason I don't now. So I started it back.

And when I came back on the web interface I was redirected to the **register** page. My account was deleted, so I created a new one. And all the settings were gone, the floud app was *reset*.

**Comment by jfurrow** [comment]
Hmm interesting. Do you by chance have the corresponding contents of `npm-debug.log` that you could post? Otherwise there's not much I can do to debug this.

**Comment by noraj1337** [comment]
There were no error so npm-debug.log: doesn't exist.

**Comment by jfurrow** [comment]
Sorry @noraj1337 but I'm going to close this for now. I have not experienced this myself. Feel free to  reopen this if you have any additional details.
