### ISSUE TITLE
No scrollbar for firefox

### ISSUE THREAD

**Issue by akyag** [jfurrow/flood#222]
Hi, I am new at this but absolutely love this GUI. While I was testing, I found out that when I used firefox (50.1.0) there was no scrollbar in the files section from torrent info. I was unable to scroll down and select/deselect any files from the torrent. Check the screenshots below 

**Firefox**
![selection_002](https://cloud.githubusercontent.com/assets/7376589/22013479/420cab04-dcbf-11e6-8c12-33333d28316f.png)

**Chrome**
![selection_003](https://cloud.githubusercontent.com/assets/7376589/22013497/541b1966-dcbf-11e6-93f7-ac6c43a83445.png)

**Comment by jfurrow** [comment]
Thanks for the issue! I just merged the PR that fixes this. https://github.com/jfurrow/flood/pull/223
