### ISSUE TITLE
[Feature request] Sort By both directions

### ISSUE THREAD

**Issue by bengadbois** [jfurrow/flood#225]
"Sort By" toggle option for both ascending and descending. It appears to be ascending for all the sort types.

**Comment by jfurrow** [comment]
This is terrible UX, but if you re-select the option (e.g. select "Name" from the dropdown, then open the dropdown again and select "Name" again), it will reverse the sorting order.

I'm completely refactoring the torrent list view at the moment and this interaction is a lot more obvious and easy to do. It's very close to being done (like a few days).

Sorry, but bear with it for a little bit longer, it'll be worth it!

**Comment by bengadbois** [comment]
Ah I see, good to know it's possible. And exciting an improvement is on the way!

**Comment by KangarooCreativeTeam** [comment]
(Sorry for the noise)

I too discovered this (by re-selecting the current sort FOR SCIENCE, and was super-pleased it is already implemented) - but seriously, the UX needed an up/down arrow to indicate the sort direction! 

Of course you've mentioned your upcoming refactoring, so issue is resolved. (looking forward to it!)

Thanks for FLOOD!  ^_^
