### ISSUE TITLE
Tuning UI

### ISSUE THREAD

**Issue by DavePS** [jfurrow/flood#238]
Hey guys,

I wanted to know if we can customize the UI like title, adding custom functions etc.

Dave

**Comment by jfurrow** [comment]
At this point you can customize the UI by editing the Javascript directly! I'd love to add a plugin system, but that's a significant effort and I don't plan to work on it any time soon.

That being said, I'll happily review PRs or accept feature requests. I'm going to close this for now, but if there's something specific you'd like to request, feel free to file another issue.
