### ISSUE TITLE
No failed login message?

### ISSUE THREAD

**Issue by formatme** [jfurrow/flood#243]
Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
    at app.js:14

**Comment by formatme** [comment]
TypeError: e.data is null
Stack trace:
_.authenticate/<@http://dev.ctzn.pw:3001/app.js:14:3767
D/</o@http://dev.ctzn.pw:3001/app.js:2:12037
D/<@http://dev.ctzn.pw:3001/app.js:2:12159
e.exports/l@http://dev.ctzn.pw:3001/app.js:2:16281

**Comment by jfurrow** [comment]
Thanks, I'll work on this. I really need to add some tests... :(
