### ISSUE TITLE
register fails to make an account

### ISSUE THREAD

**Issue by formatme** [jfurrow/flood#244]
(redacted)/api/history [HTTP/1.1 401 Unauthorized 95ms]
XML Parsing Error: syntax error
Location: (redacted)/api/history?snapshot=fiveMin
Line Number 1, Column 1:  history:1:1
XML Parsing Error: syntax error
Location: (redacted)/api/notifications?limit=10&start=0
Line Number 1, Column 1:  notifications:1:1
XML Parsing Error: syntax error
Location: (redacted)/api/stats
Line Number 1, Column 1:  stats:1:1
XML Parsing Error: syntax error
Location: (redacted)/api/client/torrents
Line Number 1, Column 1:  torrents:1:1
XML Parsing Error: syntax error
Location: (redacted)/api/settings
Line Number 1, Column 1:  settings:1:1
XML Parsing Error: syntax error
Location: (redacted)/api/client/settings
Line Number 1, Column 1:  settings:1:1
XML Parsing Error: syntax error
Location: (redacted)/api/history?snapshot=fiveMin
Line Number 1, Column 1:  history:1:1
XML Parsing Error: syntax error
Location: (redacted)/api/stats
Line Number 1, Column 1:  stats:1:1

**Comment by jfurrow** [comment]
Unfortunately I can't reproduce this one. Where are you seeing this output?

**Comment by formatme** [comment]
in google chromes console

**Comment by formatme** [comment]
i have a test up "http://dev.ctzn.pw:3001/" try to login and look at the console. i don't know if I misconfigured something or what. but i think the register script never worked for me then after i make an account it trys to login with my account which is not in the db

**Comment by formatme** [comment]
well, i guess it did make the account and i was able to login? must of been sleepy last night.
https://leethacker.club/files/46b1077.png

**Comment by jfurrow** [comment]
Hmm this is weird. Sorry, I'm not sure what happened but it does seem that registration is working fine for me.

Errors during login were not being displayed properly; I just pushed a fix for that a few hours ago. Do a `git pull` and you'll be notified when entering an incorrect password or an invalid user account.

If you wouldn't mind re-registering, you can do that by deleting `users.db` and restarting the Node app, then refreshing the UI. You should be prompted to register. I'd love to see if you get the same error.

**Comment by formatme** [comment]
sure just did and everything seems to be working now, https://leethacker.club/files/8a2031e.png
also i think maybe i was having one or two issues because i was running it like this
npm run start:production

**Comment by jfurrow** [comment]
Thanks! Glad to hear it's working properly now. `npm run start:production` is the exact same as `npm start` (I left it in for legacy support).
