### ISSUE TITLE
500 (Internal Server Error) while trying to add a torrent.

### ISSUE THREAD

**Issue by formatme** [jfurrow/flood#249]
I'm able to add torrents it seems but I ran into an issue with this one torrent that won't let me upload.
`POST http://dev.ctzn.pw:3001/api/client/add-files 500 (Internal Server Error)
(anonymous) @ app.js:14
e.exports @ app.js:14
e.exports @ app.js:14
`
https://leethacker.club/files/984955b.png

**Comment by jfurrow** [comment]
Can you show me the Node server's output when this happens?

**Comment by jfurrow** [comment]
Also, what version of node are you running?

**Comment by formatme** [comment]
node -v
v4.7.3

**Comment by formatme** [comment]
https://leethacker.club/files/9b82c6e.png
as you can see the post is a 500

**Comment by jfurrow** [comment]
@formatme That's the problem, please upgrade to the latest LTS version of node (6.9).

**Comment by jfurrow** [comment]
I'm going to close this but feel free to reopen if the problem persists after you upgrade to node 6.9

**Comment by formatme** [comment]
still getting it on
node v6.9.5
https://leethacker.club/files/1a25af5.png

**Comment by formatme** [comment]
ahh after looking into and checking the response with chrome   I found this
my torrent file size is 543kb

`{"code":-503,"faultCode":-503,"faultString":"Call XML not a proper XML-RPC call.  XML-RPC request too large.  Max allowed is 524288 bytes"}``
