### ISSUE TITLE
500 (Internal Server Error) while trying to add a torrent. part 2

### ISSUE THREAD

**Issue by formatme** [jfurrow/flood#254]
still getting this error
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
app.js:14 POST http://dev.ctzn.pw:3001/api/client/add-files 500 (Internal Server Error)
(anonymous) @ app.js:14
e.exports @ app.js:14
e.exports @ app.js:14

```
node -v
v6.9.5

https://leethacker.club/files/1a25af5.png

**Comment by formatme** [comment]
ahh after looking into and checking the response with chrome I found this
my torrent file size is 543kb

`{"code":-503,"faultCode":-503,"faultString":"Call XML not a proper XML-RPC call. XML-RPC request too large. Max allowed is 524288 bytes"}``

**Comment by formatme** [comment]
looks like 196 and 164 did not fix this

**Comment by jfurrow** [comment]
Hey @formatme that's correct :)
