### ISSUE TITLE
Changelog, releases, tags

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#259]
Please, can you write a changelog where you keep state of version, date and modifications.

This will allow users to know when an update was release and if they want to update or not.

**Comment by jfurrow** [comment]
Yes, agreed, it's time to start doing this...

**Comment by bengadbois** [comment]
It would be nice to see official tags/releases

**Comment by jfurrow** [comment]
Alright, this is finally happening! I just released v1.0.0. Thanks for your patience! <3
