### ISSUE TITLE
Tooltips for controller buttons

### ISSUE THREAD

**Issue by bengadbois** [jfurrow/flood#268]
It would be nice for new users to explicitly state what these icons are ![icons](http://i.imgur.com/Kfkd6SX.png)

It's not totally obvious if the plus/minus is adding/removing individual torrents (or the current view, or selected?), adding/removing columns, or creating new torrents, etc. And given they might be deletion it's a risky click if you don't know.

Maybe mouseover tooltips, or small text underneath, or something else - I'm not a designer.

**Comment by jfurrow** [comment]
This is a good idea, thanks!
