### ISSUE TITLE
Security issue :  Too much verbose Authentication Error Messages 

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#270]
Actually the login page return `You entered an incorrect username.` is you enter a bad username or `You entered an incorrect password.` if you enter a bad password.

This is bad because (from OWASP):

> Incorrectly implemented error messages in the case of authentication functionality can be used for the purposes of user ID and password enumeration. An application should respond (both HTTP and HTML) in a generic manner. 

Here are the best practices : https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Authentication_and_Error_Messages

**Comment by jfurrow** [comment]
Good point, I'll do this. Thanks!

**Comment by noraj1337** [comment]
Glad to help. This is very easy to do it the good way.

**Comment by jfurrow** [comment]
Closed by #274 

Thanks very much for noticing & filing issues for these security issues!
