### ISSUE TITLE
Torrent list empty after server reboot

### ISSUE THREAD

**Issue by neviel47** [jfurrow/flood#278]
Hello,

After reboot the server, and start flood and rtorrent, the torrent list from flood is empty, but the still got the files.

Centos 7

**Comment by jfurrow** [comment]
1. Can you confirm the files are still visible in rTorrent?
2. Can you copy & paste the Node server's output?

**Comment by jfurrow** [comment]
@neviel47 I'm going to close this for now, please re-open when you have more information.
