### ISSUE TITLE
Connection using rpc socket

### ISSUE THREAD

**Issue by ArtyumX** [jfurrow/flood#28]
Hi, can you implement the connection using a rpc socket instead than using SCGI ?
Nice project btw, thanks :)

**Comment by jfurrow** [comment]
I'll have to do more research on this as I'm honestly not familiar with this concept. I do see now that it's the recommended approach to RPC with rTorrent, documented here: https://github.com/rakshasa/rtorrent/wiki/RPC-Setup-XMLRPC

Thanks for filing the issue!

**Comment by jfurrow** [comment]
Fixed in #28, props to @zp!

**Comment by jockef3000** [comment]
Can anyone describe how to use the rpc socket? How does the URL look that I can use?
