### ISSUE TITLE
Option to add 'Download File' to torrent context menu

### ISSUE THREAD

**Issue by wopian** [jfurrow/flood#281]
I've recently ditched Deluge WebUI in favour of this on my server, which also required a seperate frontend to *access* the files to download - which Flood is capable of, so I've ditched that too.

However the only way I've found to download files is rather slow and tedious, as its behind 2 menus for each torrent.

1. Right click torrent (or double click - skip 2)
2. Click Torrent Details in context menu
3. Click Files tab
4. Check each file to download
5. Click download file link

Would be nice to have `Download File' in the right click context menu, as almost all of my torrents contain a single file. 

Plus it serves multiple file downloads in a tar archive, so you'd only have to use the File tab if you only want certain files.

**Comment by xiprox** [comment]
A "copy link address" context menu item would be appreciated too.

**Comment by jfurrow** [comment]
Thanks for the issue, I'll add this!

**Comment by dcousens** [comment]
This would be amazing :+1:
