### ISSUE TITLE
Top toolbar / table header not visible on Chrome Android

### ISSUE THREAD

**Issue by rarescosma** [jfurrow/flood#282]
Android version: 6.0.1
Chrome version: 56.0.2924.87

The Chrome navigation bar obscures the flood top toolbar and/or table header. 
Please see the attached screenshot and let me know if you need any extra info to reproduce the issue. 
![screenshot_20170303-122918](https://cloud.githubusercontent.com/assets/520445/23547826/621cae00-000d-11e7-93fc-25e753f105ae.png)

**Comment by jfurrow** [comment]
The entire UI is not mobile friendly at this point, but I do plan to make it so in the future.

**Comment by na-ji** [comment]
How about some basic bootstrap magic ? Making the left side a collapsable menu and maybe also collapse the top buttons ?

**Comment by berot3** [comment]
would love to see a responsive flood! Please make it happen!

I just discoverd that rutorrent has even 2 mobile-plugins! [1](https://github.com/xombiemp/rutorrentMobile) and [2](https://github.com/JimmyLaurent/ru-mobile/)

But with your design it would look much cooler ofc :smile:
