### ISSUE TITLE
BaseURI won't work

### ISSUE THREAD

**Issue by bg-o** [jfurrow/flood#284]
Hi,

I'm having troubles configuring Flood behind a reverse-proxy (nginx).

Few issues:
* Style.css is loaded without the baseURI in the path, leading to white screen in browsers (css should be accessible at myservice/baseuri/style.css)
* Loading screen stay stuck with "Torrent Taxonomy" and "Data Transfer Rate Details" grayed out

Thanks for your input !

**Comment by jfurrow** [comment]
@bg-o Make sure you're forwarding _all_ requests. Here's how you can accomplish that:

```
        location /flood/ {
            rewrite ^/flood/(.*) /$1 break;
            proxy_pass http://flood_host:flood_port;
        }
```

**Comment by bg-o** [comment]
All good thanks.

**Comment by jfurrow** [comment]
@bg-o Yeah, that's probably a good idea. I'll have to check out how Sonarr and Couchpotato are doing it, that's interesting.

**Comment by frebib** [comment]
Sonarr/CP use a static path at runtime in the config fixing it to that path. Deluge is interesting as it uses a HTTP header in the client request: `X-Deluge-Base: /deluge` which IMO is much more sensible as it allows for more flexibility as a single instance can be run at multiple URLs at the same time.

I'd like to add I had a similar issue with this as I thought the `baseURI` field in the config file was to achieve this and not define the base for the rTorrent daemon, it took me several days of messing around to work that out.

Perhaps some documentation on this would be worthwhile to save headaches.

**Comment by KaKi87** [comment]
Hi,

I have the same issue with apache2, can you help me please ?

Thanks ! :)
