### ISSUE TITLE
Hash user passwords

### ISSUE THREAD

**Issue by sa7mon** [jfurrow/flood#29]
It would be great if `server/db/users.js` would contain the hash of a user's password instead of the plaintext. Indeally, something that implements key stretching as well such as PBKDF2 or bcrypt.

**Comment by jfurrow** [comment]
Agreed, what I'm doing now is really dumb. Thanks!

**Comment by jfurrow** [comment]
I implemented a much more robust authentication method in #45, using bcrypt to hash passwords. `server/db/users.js` is gone in favor of a `users.db` which will be created for you automatically.
