### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by ajthemacboy** [jfurrow/flood#292]
I'm not sure if there's already a way to do this, I'm not familiar with rTorrent. Is there any way to use a SOCKS5 proxy like with Deluge[d]? And, can proxy support be implemented into Flood?

**Comment by jfurrow** [comment]
What does Flood need to do specifically to support a SOCKS5 proxy? As far as I can tell this configuration should exist outside of Flood entirely.

**Comment by ajthemacboy** [comment]
I don't know how many other torrent web interfaces support proxies (I think I remember uTorrent and Transmission supporting it, and I know Deluge does,) but I think it would be useful to a lot of people. 

I'm running Flood in a Docker container and there's no easy way to run it through a SOCKS5 proxy.

**Comment by jfurrow** [comment]
Sorry for the delay, but there's nothing that Flood needs to do differently for this to work, unless I am mistaken... can you provide any more details? I'll close this for now but feel free to reopen if you can provide some specific requirements.
