### ISSUE TITLE
Put static assets in a URL namespace

### ISSUE THREAD

**Issue by m45t3r** [jfurrow/flood#294]
For users using nginx, one way to increase performance is to intercept static requests and serve them with nginx directly, since nginx is much more efficient than express.js to serve them. Like described in this article ("Static file intercept"): http://blog.argteam.com/coding/hardening-node-js-for-production-part-2-using-nginx-to-avoid-node-js-load/

However, to do this in flood nowadays is quite difficult since flood does not separate its static files in a separate URL namespace. If all static contents are served from, for example, `/static` or `/assets`, it would be much easier to configure nginx to intercept static files.

So please, move all static content to a namespace.

**Comment by jfurrow** [comment]
Thanks for the issue, sorry for the delay! This is good to know, but can't you accomplish this right now? The only static assets are `style.css`, `app.js`, and `images/*.png`, so it seems like you could define a pattern in nginx like `(css|js|png)$` and then route them to the `server/assets` directory of your Flood installation.
