### ISSUE TITLE
Configure Polling Rate according to pollInterval

### ISSUE THREAD

**Issue by thiagokokada** [jfurrow/flood#295]
I am having some performance issues with flood server side. I am running a small torrent server in a first generation Raspberry Pi, coming from RuTorrent. In RuTorrent I never saw a significant usage in CPU, however flood process (`node`) constantly uses 30~70% and this badly influences performance (this is without an active torrent, with an active torrent this is even worse when a torrent is active (since rtorrent can consume a fair amount of CPU when downloading torrents, especially at higher speeds).

There is probably some opotunities to reduce server CPU usage, however one that I found is in Polling Rate: actually, it seems to be hard coded in source, even if there is a option to set it up:
https://github.com/jfurrow/flood/blob/master/server/models/client.js#L457
https://github.com/jfurrow/flood/blob/master/server/models/history.js#L124

While allowing a change in Polling Rate wouldn't resolve the performance issues, it would help if I only had a CPU spike usage each 30 seconds instead each 5 seconds.

**Comment by jfurrow** [comment]
Thanks for the issue! You're right, the poll interval in the config is meant for the Flood client to poll the Flood server. This should be more clearly defined, and I agree that the Flood server's poll of rTorrent should be configurable.

Regarding CPU usage, there are definitely optimizations that could be made when the Flood server processes the data returned by rTorrent. Please file a separate issue for that.

**Comment by AStove** [comment]
It seems as it is currently the torrentClientPollInterval parameter in the config is the polling rate that the flood server does to the rtorrent process. I changed this from 2000ms to 20000ms and the CPU usage on my raspberry pi 3 went from ~30% to ~2%.
