### ISSUE TITLE
How to add locales

### ISSUE THREAD

**Issue by Bonnee** [jfurrow/flood#296]
I wanted to translate flood in Italian, haven't found how to make it work. I did add it.js and update index.js in the i18l dir, but the locales menu still didn't have the italian entry. I then found the client/scripts/constants/Languages.js file and added an entry for italian, but the locale still doesn't show up in the settings.
Is there something else that I have to accomplish to have italian, or any other languages, working? Am I doing something wrong?

**Comment by llwu** [comment]
I think you gotta add it to the other languange's menus for Language select.

Example:
https://github.com/jfurrow/flood/search?utf8=%E2%9C%93&q=fr&type=

**Comment by jfurrow** [comment]
Sorry @Bonnee for the immense delay, and thanks for your willingness to contribute. @llwu is correct; those are all of the files that need to reference the new language.

I'll close this issue as the question is answered, but I would be thrilled to have you submit the Italian translation file! If this task seems to daunting, I'd be happy to do the work for you if you could just provide me with the `it.js` file.
