### ISSUE TITLE
Question: Would you be able to setup a personal seedbox with this?

### ISSUE THREAD

**Issue by eddiewang** [jfurrow/flood#302]
Hi,
Would you be able to setup a seedbox with this? Looking to have my own VPS setup with a torrent client... I know node but don't know about seedboxes very well (just discovered the possibilities of it).
Would I be able to get a VPS instance somewhere and host flood?

Thanks,
Eddie

**Comment by bengadbois** [comment]
It's possible if you run rtorrent as your torrent client. Flood is just a frontend, comparable to rutorrent.

**Comment by karibuTW** [comment]
Can.
I written an article just now, on how to install flood (and rtorrent) on Debian (Should be similar for Ubuntu)
https://freedif.org/flood-modern-web-ui-for-rtorrent/

You can then simply get a VPS and install it ;)

**Comment by jfurrow** [comment]
I'm closing this since the question is answered.
