### ISSUE TITLE
[Question] fsevents warnings

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#309]
Are those warnings with `fsevents` serious problems?

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by wopian** [comment]
Nope, they're just child dependencies that are only needed for a specific OS (i.e Darwin for fsevent) to function properly ☺

**Comment by jfurrow** [comment]
👍 I agree the warnings are super annoying, but there's no way around them as far as I know. If anyone does know, please feel free to re-open this issue with more details.

**Comment by wopian** [comment]
Hopefully this will become a DEBUG message and not shown by default at some point (https://github.com/npm/npm/pull/12841#issuecomment-271795543)

**Comment by noraj1337** [comment]
Thanks all for the answer
