### ISSUE TITLE
Flood not working anymore after update

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#310]
I updated flood (following the README), and after the update flood was not reachable anymore.

```
$ sudo /usr/bin/npm start --production --ddd                                                                                                                                     shark@rawsec
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'start',
npm verb cli   '--production',
npm verb cli   '--ddd' ]
npm info using npm@4.4.4
npm info using node@v7.7.3
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle flood@0.0.0~prestart: flood@0.0.0
npm sill lifecycle flood@0.0.0~prestart: no script for prestart, continuing
npm info lifecycle flood@0.0.0~start: flood@0.0.0

> flood@0.0.0 start /srv/flood
> node server/bin/www

removed 0 entries from weekSnapshot
removed 0 entries from daySnapshot
removed 1 entries from hourSnapshot
removed 4 entries from thirtyMinSnapshot
removed 8 entries from fiveMinSnapshot
removed 0 entries from monthSnapshot
```

(my domain name is still reachable, rTorrent working, I can access to him with ruTorrent, only flood is not working).

I have no error or warnings, no logs, status ok but it's just not running (was fine before updating).

I tried with Firefox and Vivaldi, both show error 102 `ERR_CONNECTION_REFUSED`.

I'm confused because flood doesn't give me logs.

The only config I changed is: I added`  floodServerHost: '127.0.0.1',` in my `config.js` because it was added in the template since my last update.

**Comment by blacksponge** [comment]
If you're trying to access to flood directly via yourdomain:3000 without proxying flood with nginx or so this is a normal behavior. ```floodServerHost: '127.0.0.1'``` tells node to listen **only** on the loopback address but you want to reach it via the distant address of your server. Thus you can change it to ```floodServerHost: '0.0.0.0'```, that way you will be able to reach flood on any network interface or you can setup your webserver to proxy the connection from a vhost to flood.
I hope this helped you a bit and sorry if I was messy.

**Comment by wopian** [comment]
And this is why we need https://github.com/jfurrow/flood/issues/259 with semver versioning for breaking changes like this 😢

**Comment by jfurrow** [comment]
Ahh shit, sorry, I didn't think about that...

**Comment by noraj1337** [comment]
@blacksponge : you're right, I'm not proxying it.
@wopian : yes `floodServerHost` that was not clear that was a listen address and there is no changelog or doc so...
@jfurrow you're welcome, you do very good job but #259 seems to be a number 1 priority.
