### ISSUE TITLE
Undefined directory when adding torrent by file

### ISSUE THREAD

**Issue by zp** [jfurrow/flood#33]
I have my rtorrent default base download path set to `~/downloads` and whenever I add a torrent by file with flood, flood ignores it and instead creates/uses `~/undefined`.

Adding the same torrent by URL/magnet causes it to correctly use the `~/downloads` path.

Also, the `Start Torrent` tickbox seems to be ignored when adding torrents by file, doesn't get added in a paused/stopped state if the box isn't checked. (again, seems to work fine with urls)

edit: Running in an Alpine Linux 3.4 VM, nodejs 4.4.5, rtorrent 0.9.6, libtorrent 0.13.6 , flood master 5420932. Connecting to flood via Chrome on Win10.

**Comment by jfurrow** [comment]
Thanks for the issue! This is fixed by #37 and #38.
