### ISSUE TITLE
[UX suggestion] When adding torrents let "location" and "tags" be the same across the tabs. 

### ISSUE THREAD

**Issue by NoLooseEnds** [jfurrow/flood#333]
When adding torrents let "location" and "tags" be the same across the tabs. The only "field" that should change is the "torrent" field.

This stops users from redoing when they start filling out on the "By URL", but really wants to add "By File".

**Comment by jfurrow** [comment]
I agree, good idea! This is covered by https://github.com/jfurrow/flood/issues/329 so I'll close this for now. Thanks for the issue!
