### ISSUE TITLE
[UX Suggestion] speed indicators

### ISSUE THREAD

**Issue by vinz243** [jfurrow/flood#336]
I really like the UI, except for the indicators for speeds and sizes. I mean it's common UX design to use no more than one or two fonts, and avoid different text sizes in the same documents, and even more in the same blocks. I think something like that would look better:

![http://i.imgur.com/7TXQrOq.png](http://i.imgur.com/7TXQrOq.png)

Thanks in advance

**Comment by jfurrow** [comment]
I'll consider making the font sizes more consistent in the next iteration, but I think it works well as-is. If other users have opinions about this, feel free to chime in here.

Sorry @vinz243 but thanks for filing the issue!
