### ISSUE TITLE
Cosmetic features

### ISSUE THREAD

**Issue by abduct** [jfurrow/flood#343]
I installed flood on windows which is working surprisingly well using the rtow latest binaries and npm.

Anyways heres a list of a few cosmetic changes that I think should be added or adjustable:

-Percent Complete: This should be changeable to allow a "completeness bar" as it is now, or a actual percentage out of 100. I find the bar hard to read and not very accurate for me due to that. So either a way to swap between the two or get rid of the bar from the category and move it else where. Perhaps when you click on a torrent (single click to highlight) create a panel that scrolls up from the bottom to indicate more stats such as a completion bar and other useful information.

-Api Update Time: I haven't seen a way to edit this inside flood itself (only the config). But I think each api should have adjustable poll time if that is possible. Say for instance a user likes to have an accurate download speed displayed but only needs other apis to update every 5 seconds. These should be individually adjustable.

-Reusable Tags: Once a tag is created it should be able to use in a click menu to assign it to another torrent rather than having to retype the tags name over and over. This might help for people like me who tag torrents heavily.

-Multiple Tags Filter: Another good feature is to be able to create an array of tags, which allows you to select from the filter menu which tags you want to display. For instance say you have movies and tag them "horror, action, scary" and want to search for "action, scary" movies. By selecting a group of tags you can filter torrents with said tags.

Other than that I really enjoy this UI and I thank you for developing it!

Edit:: Not pertaining to the topic but in the wiki I may suggest adding a page for available features. This will help newcomers see if they want to use Flood before installing.

**Comment by wopian** [comment]
>Multiple Tags Filter

See #286

**Comment by Phr33d0m** [comment]
>Api Update Time

Isn't this what ```pollInterval``` is for?

**Comment by abduct** [comment]
@Phr33d0m You can not control the individual times that each API updates with. For instance, if you want one API more responsive than the other to save on total API calls to rtorrent while still getting the responsiveness you desire.

**Comment by jfurrow** [comment]
I agree about some of these features. It would be really helpful if you could create separate issues for each one. This would help gauge community interest and also make working the tasks a bit more clear. Thanks!

**Comment by abduct** [comment]
This can be closed as I added individual issues.
