### ISSUE TITLE
[Bug] Flood stops updating after an invalid api response

### ISSUE THREAD

**Issue by frebib** [jfurrow/flood#347]
It seems that after a while (sometimes 30s, sometimes several minutes) flood stops updating itself. A friend of mine made a good suggestion that it could be something to do with Chrome putting the process into the background?

What happens is when flood sees a failed request to `stats` or `torrents` endpoints, it doesn't send another request again.

![failed requests](https://i.imgur.com/NA5HCql.png)

There are no errors in the console nor anything in the flood logs that I can see, nor any visible warnings on the page, just that the information is no longer changing.

I'm not sure whether it's relevant or not but I'm running flood through nginx as a reverse proxy on `/flood`, a 500ms update interval and using Chromium v58.

**Comment by jfurrow** [comment]
Interesting. It's weird that the requests are canceled after such a short duration (3 and 2 ms). So the tab was inactive while this was happening?

**Comment by frebib** [comment]
I thought initially it could have been but I observed the same behaviour leaving the tab open and walking away from my computer for a while.
What causes the cancellation?

**Comment by jfurrow** [comment]
I'm not sure what would cause the requests to be canceled, especially after such a short period of time... have you observed this behavior since reporting the issue? I'm not sure how to reproduce this.

**Comment by frebib** [comment]
Apologies for not following up on this.
Yeah it still happens, pretty much every 5 minutes or so. It's very strange and I can't work out what a _cancelled_ request means. Does that mean Chrome is cancelling it?
I have my final exam this afternoon so I'll try and do some digging this next week or so

**Comment by frebib** [comment]
I'm reading some reports that ad blockers could potentially affect it so I'll run for a while with uBlock disabled and let you know

**Comment by frebib** [comment]
The part that interests me over the fact requests are being cancelled is that no more attempts are made when it fails. 
Ideally I would imagine there should be a timeout where it retries regardless of how the first request failed- similar to the functionality of TCP timeouts where it tracks the rolling average RTT+a bit then retry if the request hasn't responded in that time

**Comment by noraj** [comment]
@frebib Any updates ?

**Comment by frebib** [comment]
I haven't used Flood/rTorrent since this. I still never worked out why this happens or if it still happens. I was banking on the potential Deluge support, but I'm taking the slow development as a sign that may not come to fruition for a while/ever.
