### ISSUE TITLE
[Request] Download files through http

### ISSUE THREAD

**Issue by NoLooseEnds** [jfurrow/flood#349]
(Not sure if this has been brought up before, but I think everything else is about .torrent files)

I would like the ability to download downloaded files (i.e not the .torrent, but the actual files) through  Flood.

Basically the same function as the "[Data](https://github.com/Novik/ruTorrent/wiki/PluginData)" plugin of rutorrent.

**Comment by abduct** [comment]
I believe this feature is already present. Double click a torrent, click on files, then check mark which files you wish to download. Once selected a download button will appear which will download the files via the browser.

**Comment by NoLooseEnds** [comment]
@abduct You are right. Thank you. I did not see the check marks, it looks nice when you know it, but it's not that easy to spot (at least not for me ;)).

I guess this can be marked as solved. :)
