### ISSUE TITLE
[Request] Drag & drop torrent to torrentList

### ISSUE THREAD

**Issue by larsjohnsen** [jfurrow/flood#350]
Adding a torrent file is currently a many-step process (click "Add torrent" → click "By file" → drag & drop → click "Add file"). Since adding a single torrent is done quite often, it would be nice to be able to drag & drop to add and start the torrent, as soon as the site has loaded.

**Comment by abduct** [comment]
I agree. Perhaps to expand on this allow drag and dropping to the "add torrent" button in the upper right to instantly add the torrent with the last settings used previously to add a torrent.

**Comment by jfurrow** [comment]
Good idea, thanks for the issue!
