### ISSUE TITLE
[Request] Multiple Tag Filter

### ISSUE THREAD

**Issue by abduct** [jfurrow/flood#357]
Multiple Tags Filter: A feature which allows you to select from the filter menu which tags you want to display. For instance say you have movies and tag them "horror, action, scary" and want to search for "action, scary" movies. By selecting a group of tags you can filter torrents with said tags.

See also https://github.com/jfurrow/flood/issues/286

**Comment by jfurrow** [comment]
Yep, this is a good idea.
