### ISSUE TITLE
[Bug] Downloading multiple files causes flood to hang

### ISSUE THREAD

**Issue by abduct** [jfurrow/flood#359]
I have a torrent finished with 12 400mb files and when I select 2 or more files and click download it causes flood to hang.

What is flood attempting to do? I would advise against running any kind of compression on the files since it might take a long while to archive them. A better solution would be to simply throw the files into a archiving format such as tar (which does not compress by itself) which should vastly increase the performance of the feature while still being able to download multiple files at once.

Depending on the setup of the web server the stream may already be compressed using a streaming compression such as gzip. During transit the browser may send the Accept-Encoding http header which should theoretically tell the webserver if it should compress the stream or now. I am not up to date on the HTTP RFC though.

**Comment by jfurrow** [comment]
I feel pretty dumb for not having thought of this, but you're absolutely right, the files should not be compressed at all. Flood uses the https://github.com/archiverjs/node-archiver, which itself uses https://github.com/npm/node-tar to create the tar files. I'll explore the API options and see if removing compression entirely resolves this issue.

**Comment by dcousens** [comment]
Fixed...

**Comment by jfurrow** [comment]
Everyone should shower @dcousens with admiration and praise, because this is fixed.
