### ISSUE TITLE
rtorrent removed from homebrew

### ISSUE THREAD

**Issue by mahoek** [jfurrow/flood#36]
rtorrent got removed from Homebrew[1] so it is not that easy anymore to get it running on Mac OS X.

I fired up a Docker container with rtorrent and made flood connect with it.

[1]https://github.com/Homebrew/homebrew-core/issues/338

**Comment by jfurrow** [comment]
Noooo! That's too bad. I'll update the readme, thanks for letting me know!

**Comment by jfurrow** [comment]
Removed in https://github.com/jfurrow/flood/pull/134
