### ISSUE TITLE
Flood completely hang with large number of torrents

### ISSUE THREAD

**Issue by romancin** [jfurrow/flood#360]
First of all thank you really much for this awesome Webui. After testing it I fell in love with it, so I decided to migrate my current setup to a rutorrent+flood setup on the same docker container. I have more than 2000 torrents seeding. After migrating using rutorrent and working flawlessly, when I start flood everything hung. Cannot access flood nor rutorrent web interfaces. rTorrent is still running, because I can see in my private trackers control panel, but I loose access completely, what makes this unusable... Have anyone tested flood with this number of torrents? Is there any log file that helps me to see what is happening? For your reference, if I kill flood rutorrent starts working immediately. Thank you!

**Comment by nVitius** [comment]
If I remember correctly, this has to do with Flood polling rtorrent for every item really often. I believe @jfurrow is working on a refactor that should solve this issue.

**Comment by romancin** [comment]
Awesome! Will wait for it :D

**Comment by jfurrow** [comment]
I believe this is the same issue as https://github.com/jfurrow/flood/issues/320, so I'll close this for now.

A solution is in the works, and if that doesn't fix this, then I'll evaluate this separately.
