### ISSUE TITLE
api 401 after creating user with with flood using nginx + proxypass - reload fixes it

### ISSUE THREAD

**Issue by userdocs** [jfurrow/flood#365]
When the create user prompt is completed i see this:

![1](https://cloud.githubusercontent.com/assets/16525024/26373298/e0396ca8-3ff8-11e7-99ef-ab4fc6f23c2d.jpg)

Upon looking at my screen session i see this:

![2](https://cloud.githubusercontent.com/assets/16525024/26373297/e02df800-3ff8-11e7-8850-0c95237ecac5.jpg)

If I ctrl + f5 the page, login again flood loads completely and works fine.

I figure this is an nginx 401 issue but I am not sure why it happens,

nginx + proxypass with flood in screen session.

**Comment by jfurrow** [comment]
Interesting... I'll investigate. Thanks for the issue!

**Comment by userdocs** [comment]
Just realised the title of the issue was 404 when I meant 401.

**Comment by jfurrow** [comment]
Thanks @userdocs, this should be fixed.
