### ISSUE TITLE
Can no longer see how many peers/seeds in list

### ISSUE THREAD

**Issue by NoLooseEnds** [jfurrow/flood#382]
After I pulled the new version, I can no longer see peers/seeds in the main windows. All it shows is "NaN of NaN"

<img width="1429" alt="flood" src="https://user-images.githubusercontent.com/4103531/27044531-c540c106-4f95-11e7-8d49-43ce1131c7a8.png">

**Comment by noraj1337** [comment]
First I didn't see because I was using the condensed view, but testing the Expanded view I have the same behaviour. I, also, just updated last week-end.

**Comment by NoLooseEnds** [comment]
Can confirm I can see peers/seeds in the condensed view.

**Comment by jfurrow** [comment]
Thanks for the bug report — I missed this when changing some property names... this is why I need to write tests. 😭

**Comment by jfurrow** [comment]
This was fixed in https://github.com/jfurrow/flood/pull/393, thanks for the patience!
