### ISSUE TITLE
Torrents with multiple files aren't handled correctly

### ISSUE THREAD

**Issue by JohnFlowerful** [jfurrow/flood#390]
When adding a torrent with multiple files (e.g. [this](http://linuxtracker.org/index.php?page=torrent-details&id=a35898f236132f3fad41b445473dc6a206700827)), the parent directory for the torrent is not created. Instead the torrent's files are created in the directory specified by 'Destination'.

The torrent directory can be created with 'Set Download Location', but that leads me to another issue: When using 'Set Download Location' with move data ticked, the files are not moved. It appears they are copied. It also appears that this function starts the torrent even if the previous state was stopped.

Setup:
libtorrent-ps feature-bind ([ebuild](https://github.com/JohnFlowerful/flowerlay/blob/master/net-libs/libtorrent/libtorrent-9999.ebuild))
rtorrent-ps feature-bind ([ebuild](https://github.com/JohnFlowerful/flowerlay/blob/master/net-p2p/rtorrent/rtorrent-9999.ebuild))
nginx running for reverse proxy: https://p.teknik.io/Raw/RJu6R
Flood config: https://p.teknik.io/Raw/IuIVk

rtorrent displays no errors, neither does npm nor client (Chromium 61.0.3133.0).

P.S. sorry for the multi-issue issue~

**Comment by varyoo** [comment]
I observed the same issue since the "Base path" option has been added.

**Comment by jfurrow** [comment]
Sorry for the delay in this silly bug!

**Comment by hunti88** [comment]
Hello, with commit 524a0796c9bcf95693f4f3fe0ae1ad8633441d47, this is broken again.

**Comment by jfurrow** [comment]
Sorry @hunti88, will take a look.

**Comment by varyoo** [comment]
Dupe https://github.com/jfurrow/flood/issues/506

**Comment by noraj1337** [comment]
I confirm that parent directory is not created (making a mess in the root torrent folder), the `Move data` doesn't works, and even if you move files manually the `Check Hash` option is not working (see issue #537). Managing Torrents with multiple files is very painful because of those issues and this can lead into ratio drop on private trackers if a mistake make you download files twice. So I think this is a critical bug.

**Comment by dcousens** [comment]
Also confirmed here
