### ISSUE TITLE
Can't access to Flood after login, infinite loading

### ISSUE THREAD

**Issue by Hayath** [jfurrow/flood#391]
Hi, 

I get this screen and it's loading like forever : 

![fireshot capture 42 - flood - http___37 59 61 185_3001_overview](https://user-images.githubusercontent.com/4759683/27659220-f54fd5b6-5c52-11e7-898e-04f7320b507d.png)

Also, i had to change option in config.js because i cannot access to http://myserver:3000. 
This is the lines i changed : 
```

  floodServerHost: '0.0.0.0',
  floodServerPort: 3001,

```
I get this : 
```
root@ns374792:/srv/torrent/flood# npm start

> flood@1.0.0 start /srv/torrent/flood
> node server/bin/www

GET / 304 1590.578 ms - -
GET /style.css 304 10.792 ms - -
GET /app.js 304 2.829 ms - -
GET /fonts/Roboto-500/Roboto-500.woff2 304 4.872 ms - -
GET /favicon-32x32.png 304 7.036 ms - -
GET /auth/verify?1498682893005 200 80.860 ms - 21
GET /favicon-16x16.png 304 2.395 ms - -
GET /fonts/Roboto-700/Roboto-700.woff2 304 2.196 ms - -
GET /fonts/Roboto-italic/Roboto-italic.woff2 304 2.249 ms - -
GET /favicon-32x32.png 304 1.903 ms - -
GET /api/client/settings 304 92.269 ms - -
GET /api/settings 304 49.784 ms - -
GET /favicon-16x16.png 304 1.728 ms - -
GET /api/activity-stream?historySnapshot=fiveMin 200 42.772 ms - -

```
Does someone have an idea to resolve my issue ? 
Thanks

**Comment by Fanarito** [comment]
I am having the same issue, it seems that `GET /api/activity-stream?historySnapshot=fiveMin 200` is the problem. Firefox complains that it can't establish a connection to it.

**Comment by JohnFlowerful** [comment]
Check that rtorrent's scgi details are correctly set in config.js.  

Oh, and don't run as root...

**Comment by dkanada** [comment]
I have a similar issue, when I created an account the check marks stopped after authentication status. I reloaded the page and logged in with the credentials I tried to create and now all the checks are marked except for flood settings.

**Comment by sebkoe** [comment]
I had the same issue after I upgraded flood. I had to revert back to a7f8ce921b0ae24a94fb5db6192d37b9497be788 to get flood working again.

**Comment by BartoX360** [comment]
I had the same issue after I upgraded flood. I revert back to get flood working again too.

**Comment by jfurrow** [comment]
@Fanarito @Hayath @BartoX360 @sebkoe Sorry you're all having problems. Let's try to debug all of your issues at the same time!

Are you running Flood behind a proxy?
What browsers are you using?
What version of Node are you all using?

**Comment by sebkoe** [comment]
> Are you running Flood behind a proxy?

Yes, nginx

```
server {
        listen 80;
        listen [::]:80;
        server_name [CENSORED];
        rewrite ^(.*) https://$host$1 permanent;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name [CENSORED];

    ssl_certificate /etc/ssl/[CENSORED].pem;
    ssl_certificate_key /etc/ssl/[CENSORED].key;

    add_header Strict-Transport-Security max-age=31536000;

    root /var/www/default;
    index index.html;

    location ^~ /.well-known {
        try_files $uri $uri/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-forwarded-for $proxy_add_x_forwarded_for;

        proxy_pass http://10.0.3.16:3000/;
        proxy_redirect default;
    }
}
```

> What browsers are you using?

Chrome, Android Chrome, Firefox, Edge

> What version of Node are you all using?

6.10.3

**Comment by BartoX360** [comment]
> Are you running Flood behind a proxy?

Yes, Nginx too

`server {
 listen 80;
 server_name CENSORED;
 return 301 CENSORED$request_uri;

 access_log /dev/null;
 error_log /dev/null;
}

server {
 listen 443 ssl http2;
 server_name CENSORED;

 access_log /var/log/nginx/flood-access.log;
 error_log /var/log/nginx/flood-error.log;

 location / {
  proxy_pass http://127.0.0.1:3000/;
  proxy_set_header Connection "";
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_pass_header X-Transmission-Session-Id;
 }

 ssl_certificate CENSORED;
 ssl_certificate_key CENSORED;
 ssl_trusted_certificate CENSORED;

 ssl_protocols TLSv1.2;
 ssl_ecdh_curve secp384r1;
 ssl_ciphers EECDH+AESGCM:EECDH+AES;
 ssl_prefer_server_ciphers on;
 resolver 80.67.169.12 80.67.169.40 valid=300s;
 resolver_timeout 5s;
 ssl_stapling on;
 ssl_stapling_verify on;
 ssl_session_cache shared:SSL:10m;
 ssl_session_timeout 5m;
 ssl_session_tickets off;
}`

> What browsers are you using?

Chrome, Safari, Firefox, Edge, Internet Explorer

> What version of Node are you all using?

6.11.0

**Comment by okeehou** [comment]
I had the same issue after upgraded.

**Comment by jfurrow** [comment]
@sebkoe @BartoX360 Sounds like it's a problem with using nginx and server-sent events (which is now how the Flood client receives updates from the Flood server). I just remembered somebody brought this up in the Slack channel also, but I'm not sure if that user ever solved the issue.

I'll try to look into, but if somebody else could help, that would be great.

Here are some relevant links to help debug:
https://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx
https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate

**Comment by jfurrow** [comment]
@okeehou Are you using an Nginx proxy also?

**Comment by okeehou** [comment]
@jfurrow Yes, I'm using Nginx proxy.

**Comment by jfurrow** [comment]
@okeehou @sebkoe @BartoX360 @Fanarito @Hayath I'm pretty sure I fixed this in #398, can you please pull the latest and verify? Here's the nginx config I am using to test this:

```nginx
events {
  worker_connections 2000; # I don't know what this does, just FYI
}

http {
  server {
    listen 127.0.0.1:8001;

    # This just allows you to host flood somewhere other than the root of the host.
    # Ensure this value matches the `baseURI` value in config.js
    location /flood/ {
      rewrite ^/flood/(.*) /$1 break;
      proxy_pass http://localhost:3000;
    }
  }
}
``

**Comment by okeehou** [comment]
@jfurrow This doesn't work for me. `event` block is not allowed. And I've never added a `http` block in a nginx file before. This is really weird.

**Comment by jfurrow** [comment]
Okay ignore the nginx config, I don't use nginx myself but it was
complaining about the events block missing.

The fix, I believe, is the PR I merged with the new header. So try with
your current nginx config, pull from master and retry, if you haven't
already.

If you have already tried the latest master, then it's apparently not
fixed...

What version of nginx?

**Comment by okeehou** [comment]
I pulled the latest version, and it still keep loading at the `Authentication Status` screen.

I'm using `nginx version: nginx/1.10.3 (Ubuntu)`

**Comment by jfurrow** [comment]
Thanks for the info, sorry it's not fixed... I'm not sure why it's working
for me but I'll try again tomorrow.

If anyone else has a chance to test, I'd be grateful!

On Jul 5, 2017 11:46 PM, "okeehou" <notifications@github.com> wrote:

I pulled the latest version, and it still keep loading at the Authentication
Status screen.

I'm using nginx version: nginx/1.10.3 (Ubuntu)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jfurrow/flood/issues/391#issuecomment-313310807>, or mute
the thread

**Comment by okeehou** [comment]
Don't worry, thanks for your great working! Looking for your next version of Flood, an hope that this problem will be fixed!

**Comment by sebkoe** [comment]
> If anyone else has a chance to test, I'd be grateful!

I just did and it works for me. Thank you for your work

**Comment by squaresmile** [comment]
The PR fixes it for me. It takes a long time to finish loading before.

**Comment by jfurrow** [comment]
@okeehou I'm running `nginx/1.12.0`, any chance you can try upgrading? I'm trying to install an older version now...

@sebkoe @squaresmile Glad to hear it's fixed for both you — can you both please report which version of nginx are you using? `nginx -v` will tell you this.

**Comment by okeehou** [comment]
I tried to install it on a Vultr VPS, it works! Thank you!

**Comment by sebkoe** [comment]
>  can you both please report which version of nginx are you using?

1.13.0

**Comment by jfurrow** [comment]
@okeehou Awesome, glad to hear it! Closing this ticket now, thanks for reporting.

**Comment by SckyzO** [comment]
Hi all, 
Juste for information, i have the same problem but only with latest firefox version
Working with Chrome.

**Comment by angarod** [comment]
I have the same problem too on firefox 61.0

**Comment by noraj** [comment]
@angarod Did u updated to the last flood version and tried the [wiki](https://github.com/jfurrow/flood/wiki/Troubleshooting) ?
