### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by mahoek** [jfurrow/flood#40]
I thought it would be a nice feature for Flood to support i18n.

_I've been frustrated by the old rutorrent interface since I began using it years ago. I've had the idea of creating something like u did here for a very long time. So when I found out about Flood last weekend I was really excited and quickly started testing it. It looks really nice._

_I am just getting started with React and started playing around with Flood this weekend. I've looked at the code for hours and I am beginning to understand how it was build more and more. I've learned a lot this weekend. Thanks for that!_

_What I did is trying to get some kind of i18n working in Flood. You can see what I did here:_

https://github.com/mahoek/flood/tree/feature/i18n

_Surely I did not build it like you would build this, but at least I wanted to mention it here. I am going to work it out further just to learn. If you have any tips or suggestions then I'd really like to hear them._

_It would be really cool if you'd (or someone else) make an IRC or Slack channel for Flood where we can talk about the future of Flood. What do you think?_

_Thanks and keep up the good work!_

**Comment by jfurrow** [comment]
Thanks for this! I agree, this is absolutely necessary.

You've brought up a lot of really good questions, and unfortunately I don't have answers for all of them at this time. Let me take a bit of time to think before I say anything too binding :). One thing specifically I want to consider is what to consider `settings` vs `config`, and where/how these defaults should be defined/overridden. In the near future I would like to include a UI that allows full configuration of the application, which writes to the `config` file permanently.

As a whole, I think what you've done is great. I have a few arbitrary stylistic requests, which I should document somewhere for future contributions. But for now, here goes:
* I'd like to keep external module imports separate from internal module imports, where external module imports are all at the top of the file.
* When importing specific members of modules, let's avoid the whitespace after and before the brackets. So `import { foo } from 'bar';` should be `import {foo} from 'bar';`
* I would also like to alphabetize member imports: `import { foo, bar } from 'baz';` should be `import {bar, baz} from 'bar';`

So, given [this example](https://github.com/mahoek/flood/commit/e0d34833c6de8bc7521143a5b44da8d5224ffe9e#diff-f5ab0a2b30bf8f64f53ef9aa636c6c86R5), I would like for it to appear as:
```javascript
import {addLocaleData, IntlProvider} from 'react-intl';
import nl from 'react-intl/locale-data/nl';
import React from 'react';
import ReactDOM from 'react-dom';  

// ...internal module imports...
```

I'm also concerned about defaulting the language to `nl`, [here](https://github.com/mahoek/flood/commit/e0d34833c6de8bc7521143a5b44da8d5224ffe9e#diff-17e59e72a32ae6367833efd3de7a52ddR23). I think maybe this should be included in the app's config, but I don't feel super strongly about this. And we should probably default to `en` for now, though I sort-of feel like a xenophobic ass for suggesting this.

Again, thank you so much for the contribution! I welcome a PR for these changes as I think this is a great start.

I'll think about the other points you brought up and update this as soon as I have organized my thoughts.

**Comment by mahoek** [comment]
Thanks for your reply. I will try to do some more work on the internationalization later this week. I will fulfill your requests mentioned above and open a PR as soon as I find some spare time. We then can discuss the further implementation of the internationalization in the PR then.

**Comment by mahoek** [comment]
Added with PR #42
