### ISSUE TITLE
Mediainfo error

### ISSUE THREAD

**Issue by ghostswe** [jfurrow/flood#401]
Getting this when try to mediainfo a torrent file in the ui

An error occurred while running mediainfo on the server. Check that mediainfo is installed and available in the PATH to Flood.

Shows this 

GET /api/mediainfo?hash=65F878981993A86211C13EAA0A2D11C4E9098C67 500 161.690 ms 

Running Debian 8

**Comment by NoLooseEnds** [comment]
I have had this for as long as I can remember also. Ubuntu 16.10

**Comment by runaroundhome** [comment]
Pretty sure this is a known bug, and there is no fix yet. I get the same.

**Comment by albaldi** [comment]
> An error occurred while running mediainfo on the server. Check that mediainfo is installed and available in the PATH to Flood.

but mediainfo is installed
```
$ which mediainfo
/usr/local/bin/mediainfo
$ mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v0.7.97
```

node run with abc user
```
 ps
PID   USER     TIME   COMMAND
    1 root       0:00 s6-svscan -t0 /var/run/s6/services
   31 root       0:00 s6-supervise s6-fdholderd
  196 root       0:00 s6-supervise flood
  198 abc        0:02 npm
  223 abc        0:00 sh -c node server/bin/www
  224 abc        0:18 node server/bin/www
  234 root       0:00 /bin/bash
  258 root       0:00 ps

su -c echo $PATH abc
No passwd entry for user '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
```

Can we put the location of mediainfo in settings

thanks

**Comment by jfurrow** [comment]
I'm able to reproduce this, will fix when I can!

**Comment by SavageCore** [comment]
@ghostswe @NoLooseEnds @runaroundhome @albaldi Do you want to give this a test?

**Comment by SanPilot** [comment]
@jfurrow @SavageCore This should be tested and merged in ASAP.

**Comment by jfurrow** [comment]
Thanks again @SavageCore!

**Comment by C74K** [comment]
dont work

**Comment by noraj1337** [comment]
@C74K Can you be more specific ?
