### ISSUE TITLE
Torrent's files not removed when deleting torrent

### ISSUE THREAD

**Issue by sin0light** [jfurrow/flood#406]
Hi !

I'm experiencing an issue when removing a torrent added by magnet (didn't try with torrent file). The torrent is successfly removed in flood but torrent's files aren't removed (only the xxxxx.meta file is removed).
I have already seen #158, so I `git pull` but it didn't solve the problem.
I also saw #289, so I ran `npm install rimraf` but it still didn't work.
The torrent's directory is owned by rtorrent:rtorrent (tried with rtorrent:flood but didn't solve).
I have this log : 
`POST /api/client/torrents/delete 200 8.068 ms - 238`
`Error deleting file: /path/to/files`
`Error: EACCES: permission denied, unlink '/path/to/files'`
`Error deleting file: /path/to/files`
`Error: EACCES: permission denied, unlink '/path/to/files'`

I tried to run flood as root : it doesn't result in an error but it doesn't remove the files either.

Thanks !

**Comment by jfurrow** [comment]
@sin0light it seems this is a permissions issue on your end, I'm afraid. What are the user/group permissions on the files, and what user/group permissions is the Flood instance?

**Comment by abduct** [comment]
This issue also happens on windows. I am not sure what day I cloned the master but it was very shortly after this commit (was probably even the same day): 

https://github.com/jfurrow/flood/commit/a0e66218737170572967aaa47a4f986d4c6cb3b7 

Notably the same problem happens on my linux server which was updated the same day. Prior to this commit the torrent deletion was working fine on Windows. I have not updated to the latest master as of yet though so I am not sure if this bug might of been fixed. I will check it out later and reply back if it was fixed or not.

**Comment by jfurrow** [comment]
@abduct There was definitely a bug relating to torrent deletion that has been fixed since that commit, so please check it out (and if you have problems, please create a separate issue). The `EACCES` error is due to mismatched file & runtime permissions.

**Comment by sin0light** [comment]
Hello, thanks for your answer

The files and the directory belong to rtorrent:rtorrent,; the flood instance belongs to flood:flood and run as flood.

**Comment by abduct** [comment]
@sin0light I would suggest either running both applications under the same user, or creating a group called "torrent" adding both users to it as well as set it to the main group for both users. Afterwards you need to recursively chown all your torrent data to have the flags rtorrent:torrent.

You may have to even chmod all the files to make them group read/write.

As it is right now I have a suspicion that all the actual data rtorrent downloads is owned by rtorrent:rtorrent with fairly restrictive permissions (most likely 755) which may prevent world from writing/deleting the files thus preventing the flood user from manipulating the data properly.

You can find out by logging into the rtorrent user and running "stat" on a file name to check permissions and uid/gid groups. Also be aware that you may have to completely log out of a terminal and back in before new user groups take effect. 

The easiest solution is to run both applications as the same user and everything works as intended.

**Comment by sin0light** [comment]
It works ! Thank you a lot !
