### ISSUE TITLE
Infinite loading on /api/client/settings

### ISSUE THREAD

**Issue by Soullivaneuh** [jfurrow/flood#412]
I recently added 200 fast resumed torrent onto my rtorrent watch directory.

Rtorrent is still working and seems to manage my torrent, but flood does not do anything since this time.

It is stuck here:

![image](https://user-images.githubusercontent.com/1698357/28715022-6363808e-7396-11e7-8081-8587ab230b9c.png)

Here is the corresponding XHR request:

![image](https://user-images.githubusercontent.com/1698357/28715028-6c9a30d0-7396-11e7-86d4-9e21026f7f04.png)

What could be wrong ? I'm using the last master commit of your project.

EDIT: I try to clean all the project (`git clean -fdx`) and re-install it. Same issue. Still stuck at this part with never ending...

**Comment by aztazt** [comment]
Just installed Flood locally on my PC, and I encounter the exact same problem.
I'm on Windows 10 Insider Preview, I've installed nodeJS 6.11.1 LTS.
I renamed config.template.js to config.js. I've set the host and port of my remote rtorrent server, but was not able to set a username and a password in the config file.
When I go to localhost:3000, I 'm able to write a username and a password, so I type my rTorrent ones and I'm stuck at "Flood settings" as mentionned above by Soullivaneuh.

Did I do something wrong ?

**Comment by Soullivaneuh** [comment]
For my case, I'm not sure this is completly related to flood.

This happen only if I add **a lot** of torrent file to the rtorrent watch directory on single time.

**Comment by Soullivaneuh** [comment]
I have again the issue, with not many torrent this time (only 2).

Please tell me what information you need to find a solution.

**Comment by jfurrow** [comment]
@Soullivaneuh @aztazt The error handling could definitely be better for this. But generally this happens when the Flood server can't connect to rTorrent. What does the Flood server's output show in your terminal session? If it can't connect to rTorrent, Flood displays a warning there.

Things to check:
* rTorrent is compiled with XML-RPC support (did you compile rTorrent yourself, and did you do so with the `--with-xmlrpc-c` flag?)
* the SCGI port or socket have been defined in your rTorrent configuration (`rtorrent.rc` — check out [this section of Flood's README](https://github.com/jfurrow/flood#configuring) if you're confused by this)
* the same SCGI port or socket have been defined in Flood's `config.js`

**Comment by Soullivaneuh** [comment]
@jfurrow The rtorrent and flood configs are good because the connection is done.

The infinite loading does not occur every time.

When it occurs, there is no error message. The XHR request is still on `pending` state and terminate by a timeout.

**Comment by alvadorn** [comment]
The same thing is occurring with me, my _rtorrent_ and _flood_ is executed with screen. This load finishes when I login at my server with ssh.

**Comment by ponasromas** [comment]
So, is there any solution to this problem? Please provide fix.

**Comment by deed02392** [comment]
I'm getting this issue too. My XMLRPC endpoint is behind a VHOST. Other apps can use it with the following connection spec: `https://foo.bar/RPC2`

I have tried lots of variations for putting this in `config.js` terms, to no avail.

**Comment by ponasromas** [comment]
Problem fixed after completely re--installed Flood and launched it as root.

**Comment by deed02392** [comment]
I used the latest build of the Docker container on both Linux and OS X...

**Comment by noraj1337** [comment]
@ponasromas Running flood as root is a security issue, please follow [this](https://github.com/jfurrow/flood/wiki/Install-flood-with-a-service-account) for your own security.

**Comment by ponasromas** [comment]
Running flood as root on private lan is not a security issue. I simply don't care.

**Comment by noraj1337** [comment]
@ponasromas Your LAN is not connected to the internet? How are you downloading your downloading torrents so? I just told that for you. Security matters everywhere but you are free to do as you want of course. If you don't agree no need to reply here in order to keep this issue clean. Thanks.

**Comment by noraj** [comment]
> Problem fixed after completely re--installed Flood and launched it as root.

And no more updates since Dec 2017. We can close.
