### ISSUE TITLE
Remove with data not working with moved completed files

### ISSUE THREAD

**Issue by Soullivaneuh** [jfurrow/flood#416]
I'm using the "move to complete" method: http://www.krank.se/2014/06/25/rtorrent-magic-moving-finished-torrents-based-on-labels/

This is working great.

But if I want to remove the torrent **with** the data trough your interface, the torrent is removed, but not the data.

I suspect Flood trying to manually remove the data from the provided path for incomplete files instead of telling rtorrent to do the remove itself.

Am I right? How to solve this?

Thanks.

**Comment by randomnonsense** [comment]
Your way is the clumsy way to do this. See https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#id11 for the right way with recent rtorrent. 

This said, there is a problem with flood and rtorrent as they somehow conflict in processing torrents which complete. The problem only occurs **if you add torrents via Flood**. Flood's fault. If you add torrents directly to watch folders, flood will display everything correctly.

**Comment by randomnonsense** [comment]
Solved here https://github.com/jfurrow/flood/issues/434

**Comment by noraj** [comment]
Solved here #434
