### ISSUE TITLE
Partial download info not correctly transmitted to rtorrent

### ISSUE THREAD

**Issue by Soullivaneuh** [jfurrow/flood#420]
I added many torrent files from the flood interface in paused state and editing file listing to remove some files from download.

First problem: The torrent is not considered as finished (progress bar not completed), but "seems" to stop after downloading files.

Second problem: Did I just say "seems"? Yeah. Because in reality, rtorrent was downloading all the torrent files, **including** skipped ones.

The file list detail of one of the caused torrent:

![image](https://user-images.githubusercontent.com/1698357/28969795-5af32a7c-7926-11e7-827d-c0412488cdc2.png)

The complete corresponding foldeR:

![image](https://user-images.githubusercontent.com/1698357/28969804-62071850-7926-11e7-99a3-dd85c2bd4cb3.png)

As you can see, the files is completely downloaded, it should not be.

**Comment by jfurrow** [comment]
This is not an issue with Flood — it looks like you've active torrent files, which is not supported in Flood (nor is it supported in rtorrent).
