### ISSUE TITLE
[Bug] Interface is blinking with downloading or verifying torrents

### ISSUE THREAD

**Issue by Soullivaneuh** [jfurrow/flood#421]
While I have downloading or verifying torrent on the list, the interface is regularly blinking and can be sometime un-usable.

It seems the torrent list is an html refresh, am I right?

In this case, it may be better to get some JSON data and update the template accordingly.

**Comment by jfurrow** [comment]
@Soullivaneuh What browser? What's your OS and resources? How many torrents? It sounds like it's a matter of the UI consuming a lot of resources, but I can't be sure.

The UI is no "html refresh"; it's a full client-side application, consuming JSON from the Flood server and rendering client-side.

**Comment by Soullivaneuh** [comment]
OS : Ubuntu 17.04
Browser : Chrome Version 59.0.3071.109 (Official Build) (64-bit)
Resolution : 1080p
Torrents number : more than 40 under download to make it happen.

> It sounds like it's a matter of the UI consuming a lot of resources

It's not impossible because the blinking is disappearing if I reduce the windows size.

**Comment by randomnonsense** [comment]
It's the chrome mismanaging the video driver as it tries to use hardware acceleration. Chrome/chromium's issues with video happen all the time, especially on Linux. Disable attempted hardware accel. Flood is fine.

**Comment by jfurrow** [comment]
I'm going to close this, but I want to acknowledge that the Flood UI probably isn't perfect, performance-wise. I think it's pretty good, at least for how I use it, but I'm always looking for ways to improve. Open a new issue if you want to discuss any aspect of the UI's performance.
