### ISSUE TITLE
Torrents disappear when shutdown unexpectedly 

### ISSUE THREAD

**Issue by genericsauce** [jfurrow/flood#423]
Whenever my computer crashes and I need to force a reboot all of my torrents disappear from flood and rtorrent. Is there a way to prevent this?

**Comment by antonioantunes** [comment]
This is related to rTorrent not to flood.

**Comment by genericsauce** [comment]
I have used rtorrent+rutorrent for a while and never has it deleted torrents on crash. This is clearly a flood issue.

**Comment by antonioantunes** [comment]
Try this: shutdown unexpectedly, then start only rTorrent (not flood) to check if your torrents are still there.

**Comment by genericsauce** [comment]
Created new directory for session in .rtorrent.rc and now works as expected.
