### ISSUE TITLE
Set permissions for directory creation

### ISSUE THREAD

**Issue by kwevers** [jfurrow/flood#426]
When specifying a download directory that doesn't excist, flood will create the directory automatically.
This is obviously a good thing.
The problem however is when using different users for flood and rtorrent.
The directory is created with permissions of the flood user which can  cause rtorrent not being able to write to it.
It would be great if we can set the owner, group and (!) mode of the created directories in config.js

**Comment by randomnonsense** [comment]
Put both users in the same group, system-wise. Add appropriate umask notations to users' .profile or .login so anything they create is saved with a proper group permissions. Solved.

**Comment by kwevers** [comment]
You are right. I've added a UMask setting in the systemd file though because my user doesn't have a shell.
