### ISSUE TITLE
Flood won't launch on Debian 9

### ISSUE THREAD

**Issue by phxn** [jfurrow/flood#428]
Hello!

Any idea why this is happening? I've tried versions 6.x-8.x of nodejs and none work for me. Please help!

When launching, all I see is this...

> flood$ npm start
> flood@1.0.0 start /home/user/flood
> node server/bin/www

**Comment by phxn** [comment]
Change:

> floodServerHost: '127.0.0.1',

to

> floodServerHost: '0.0.0.0',

**Comment by jfurrow** [comment]
Yes, the default is `127.0.0.1` because unbinding the host is a potential security risk if the server is exposed to the outside world and you haven't taken necessary precautions.
