### ISSUE TITLE
Regex download rules

### ISSUE THREAD

**Issue by karelvanhecke** [jfurrow/flood#431]
I can't get this to work.

`.*Video.*1080p.* `should in theory download all torrents from an RSS feed that contain both those patterns, correct?

**Comment by SanPilot** [comment]
Maybe the order is the issue? This regex will match anything (including nothing) _followed by_ 'Video' followed by '1080p' ...

**Comment by randomnonsense** [comment]
The order is the issue. Also simpler it would be (Video).*(1080p)

It will only match names as such (in this order, first "Video", then "1080p":
Some.Show.Name.HDTV.**_Video_**.Something.Here.**_1080p_**.x264-FLOOD

and no other torrents.

It will **_not_** match
Some.Show.Name.HDTV.**_1080p_**.Something.Here.**_Video_**.x264-FLOOD

**Comment by SanPilot** [comment]
Try this: `(Video|1080p)`

This should match any title with either of those in any order.

**Comment by randomnonsense** [comment]
OP, please clarify what you want, matches including both or 'either or'.

**Comment by jfurrow** [comment]
@randomnonsense and @SanPilot are correct and deserve a _huge_ "thank you" for answering this! ❤️

**Comment by enoch85** [comment]
I'm coming from ruTorrent and I've been trying for the last 3 hours to wrap my head around how the RSS works in Flood.

This is a regex example from ruTorrent:
`/Name of Series.*(s|S)(2|02)(e|E)?[0-30]+.*(720p|1080p).*/i`

It will match:
Name of Series
Season 2
Episode 0 to 30
720p or 1080p
It will be case-insensitive (/i)

So how if Flood doing it? Can I not use the RSS regex straight off from ruTorrent? Any help is greatly appreciated. ping @SanPilot @randomnonsense @jfurrow Thanks!

**Comment by noraj** [comment]
@enoch85 I think it is done this way https://github.com/jfurrow/flood/blob/03d394397443cea2b0a13b5cec663850450a75e7/server/services/feedService.js#L98-L108

**Comment by noraj** [comment]
@SanPilot is right, `RegExp(rule.match, 'gi')` `g` is for global and `i` for case insensitive.

**Comment by enoch85** [comment]
Guys, you are awesome! Just changed my feeds.db to match your suggestions. Let's hope it works!

**Comment by enoch85** [comment]
Yup, it worked, just awesome!
