### ISSUE TITLE
RSS Feeds are parsed incorrectly

### ISSUE THREAD

**Issue by SanPilot** [jfurrow/flood#433]
Currently, Flood uses the URL from the `<link>` tag of an RSS item to download. However, most torrent sites' RSS feeds use the `url` attribute of the `<enclosure>` to contain the actual torrent file/magnet link. Often the `<link>` tag links to the listing page for the torrent.

See the RSS feed for YIFY, eztv, etc. 

The FeedSub module's documentation is lacking, and I couldn't get it to work in a node shell, but the correct url must be grabbed from the attribute.

**Comment by jfurrow** [comment]
This has been brought up before, and if I remember correctly, trackers are not consistent about where they put their torrent URLs in feeds. So probably the best solution is to allow users to configure which tags contain the torrent URL (and if the URL is simply wrapped in the tags, or if it's an attribute on a specific tag? ugh).

Perhaps someone could do some digging and find out how the top 2 or 3 tracker software handle this. I wrote Flood to work primarily with Gazelle's feeds, for what it's worth (and I based it off of one or two trackers, not the actual Gazelle source).

**Comment by SanPilot** [comment]
Perhaps we can grab both and test if they are a magnet/torrent link
