### ISSUE TITLE
Differently formatted peers and seeds; and shorter column names

### ISSUE THREAD

**Issue by randomnonsense** [jfurrow/flood#439]
This is a proposed feature. Please label as enhancement. To save space please consider formatting peers and seeds differently. Now it's "12 of 39". Perhaps utorrent's "12 (39)" would be much better.

In case of "condensed" view perhaps column headers could have shorter names, e.g. "FS" instead of "File size", "R" instead of "Ratio", S" and "P" instead of "Seeds" and "Peers", "DL" instead of "Downloaded", "DR" and "UR" instead of "Download Speed" and "Upload Speed" (or better "Download Rate" and "Upload rate" since "speed" seems to be a wrong word choice), and so on whenever this makes sense. Most should be self-explanatory.  Perhaps this could be a user-selectable option, e.g. "Display short column headers" at the Settings/User interface page.

Also progress could be simply expressed in percents, but this has already been requested elsewhere.

Thanks for your consideration.

**Comment by SanPilot** [comment]
I dunno. One of Flood's most prominent and unique features is its simplicity. IMHO, abbreviating makes the interface more technical, and increases the learning curve slightly for novice users. There is massive variety when it comes to torrent clients, but this is something that is unique to Flood.

**Comment by randomnonsense** [comment]
Your perspective is nonsensical. What you basically said is "Let's not allow Flood to evolve any further since the slow ones will be slow at it". Anyway, as I wrote, this could easily be optional. This way anybody developmentally challenged can stick to the 'factory defaults'.

**Comment by jfurrow** [comment]
I side with @SanPilot on these requests, with the exception of displaying peers/seeds as `12 (39)`. Please file a separate issue for this.
