### ISSUE TITLE
No extensive documentation?

### ISSUE THREAD

**Issue by piperun** [jfurrow/flood#44]
It would be really nice if there was a "Get started contributing" where it showcase more of what each file/directory is for.

**Comment by jfurrow** [comment]
I agree. I want to restructure the component directory, as I've let it get really messy. When I do so I'll write some documentation for this.

**Comment by piperun** [comment]
Thanks, since I think this project might one day be able to replace rutorrent if it's able to scale.

**Comment by noraj1337** [comment]
We may close #44 as an older duplicate.

**Comment by jfurrow** [comment]
Closing in favor of https://github.com/jfurrow/flood/issues/385
