### ISSUE TITLE
Problem starting flood service

### ISSUE THREAD

**Issue by slippern** [jfurrow/flood#443]
Sep 10 16:54:15 web systemd: Started flood.service.
Sep 10 16:54:15 web systemd: Starting flood.service...
Sep 10 16:54:16 web notell: > flood@1.0.0 start /srv/torrent/flood
Sep 10 16:54:16 web notell: > node server/bin/www
Sep 10 16:54:16 web notell: /srv/torrent/flood/node_modules/nedb/lib/datastore.js:77
Sep 10 16:54:16 web notell: if (err) { throw err; }
Sep 10 16:54:16 web notell: ^
Sep 10 16:54:16 web notell: Error: EACCES: permission denied, open './server/db/notifications.db'
Sep 10 16:54:16 web notell: at Error (native)
Sep 10 16:54:16 web notell: npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
Sep 10 16:54:16 web notell: npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "start"
Sep 10 16:54:16 web notell: npm ERR! node v6.9.0
Sep 10 16:54:16 web notell: npm ERR! npm  v3.10.10
Sep 10 16:54:16 web notell: npm ERR! code ELIFECYCLE
Sep 10 16:54:16 web notell: npm ERR! flood@1.0.0 start: `node server/bin/www`
Sep 10 16:54:16 web notell: npm ERR! Exit status 1
Sep 10 16:54:16 web notell: npm ERR!
Sep 10 16:54:16 web notell: npm ERR! Failed at the flood@1.0.0 start script 'node server/bin/www'.
Sep 10 16:54:16 web notell: npm ERR! Make sure you have the latest version of node.js and npm installed.
Sep 10 16:54:16 web notell: npm ERR! If you do, this is most likely a problem with the flood package,
Sep 10 16:54:16 web notell: npm ERR! not with npm itself.
Sep 10 16:54:16 web notell: npm ERR! Tell the author that this fails on your system:
Sep 10 16:54:16 web notell: npm ERR!     node server/bin/www
Sep 10 16:54:16 web notell: npm ERR! You can get information on how to open an issue for this project with:
Sep 10 16:54:16 web notell: npm ERR!     npm bugs flood
Sep 10 16:54:16 web notell: npm ERR! Or if that isn't available, you can get their info via:
Sep 10 16:54:16 web notell: npm ERR!     npm owner ls flood
Sep 10 16:54:16 web notell: npm ERR! There is likely additional logging output above.
Sep 10 16:54:16 web notell: npm ERR! Please include the following file with any support request:
Sep 10 16:54:16 web notell: npm ERR!     /srv/torrent/flood/npm-debug.log
Sep 10 16:54:16 web systemd: flood.service: main process exited, code=exited, status=1/FAILURE
Sep 10 16:54:16 web systemd: Unit flood.service entered failed state.
Sep 10 16:54:16 web systemd: flood.service failed.
Sep 10 16:54:16 web systemd: flood.service holdoff time over, scheduling restart.
Sep 10 16:54:16 web systemd: start request repeated too quickly for flood.service
Sep 10 16:54:16 web systemd: Failed to start flood.service.
Sep 10 16:54:16 web systemd: Unit flood.service entered failed state.
Sep 10 16:54:16 web systemd: flood.service failed.

flood.service init script:
[Service]
WorkingDirectory=/srv/torrent/flood
ExecStart=/usr/bin/npm start
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=notell
User=flood
Group=flood
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target

**Comment by noraj1337** [comment]
You want to follow [Install flood with a service account](https://github.com/jfurrow/flood/wiki/Install-flood-with-a-service-account)

`/etc/systemd/system/flood.service`:

```
[Unit]
Description=Flood, web interface for rTorrent
After=network.target

[Service]
User=flood
ExecStart=/usr/bin/npm start --production /srv/flood
WorkingDirectory=/srv/flood/
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by slippern** [comment]
Tank you it worked! :)
