### ISSUE TITLE
Flood not downloading torrent with magnet links

### ISSUE THREAD

**Issue by slippern** [jfurrow/flood#449]
For some reason flood is not able to download torrent from RSS or magnet links..
It is beeing added to the torrent list, with the name 1841A463F6F8D3416787B10AE1B11120B0396B48.meta.. (torrenthash.meta)...

But the download is never started... 
When im adding the torrent from the rtorrent console it began download immediately...

**Comment by noraj1337** [comment]
@slippern How many time did you wait? It often 1-2min before synchronizing.

**Comment by slippern** [comment]
I have waited for over 30 minutes, still no downloading..
magnet:?xt=urn:btih:868A65A5489A7B4F48E08C10D2B107B901094875&dn=Salvation+S01E12+1080p+HDTV+X264+DIMENSION&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce

**Comment by noraj1337** [comment]
@saldru This is working. I added the magnet link. Then I started the torrent then it synced and transmorded the name from *868A65A5489A7B4F48E08C10D2B107B901094875.meta* to *Salvation.S01E12.1080p.HDTV.X264.DIMENSION* and automatically stopped. Then I started the torrent and it instantly begin to download.

So either you didn't did that or you have a configuration problem (maybe your flood settings, maybe your network setup, maybe your rtorrent settings, etc...).

@jfurrow This is not a flood bug.

**Comment by dcousens** [comment]
Can be closed.
This sounds like a poorly configured DHT or encryption being too strict.

**Comment by jfurrow** [comment]
While Flood's magnet link handling should be better, this isn't a Flood issue.

**Comment by slippern** [comment]
The problem was that the rtorrent did not have permission to some temp folders..

**Comment by echersdk** [comment]
I apologize for bringing this up again, however, @slippern what did you do? I mean, what temp folders?
I seem to have the same issue as you.

**Comment by slippern** [comment]
@echersdk The problem was that rtorrent did not have write permissions to the /tmp folder on my server.
