### ISSUE TITLE
Can't start flood service 

### ISSUE THREAD

**Issue by Drastiques** [jfurrow/flood#459]
first i tried to install flood on my debian vps 
but when i use supervisor to start flood it instantly crashes with either a FATAL error or a BACKOFF

here is my npm debug log 
i can't get it to run and it's making me maaaaaaaaaaaad 

can you help me please ? 

`
/home/seedbox/flood/server/bin/www:4
let fs = require('fs');
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! flood@1.0.0 start: `node server/bin/www`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the flood@1.0.0 start script.
npm ERR! This is most likely a problem with the flood package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls flood
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-042stab120.11
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/seedbox/flood
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/seedbox/flood/npm-debug.log
npm ERR! not ok code 0
`

**Comment by midzer** [comment]
@Drastiques hi. do you meet all flood Pre-Requisites? like node v6.9 etc?

**Comment by Drastiques** [comment]
yeah, i just noticed that  my node js  was outdated and now flood is running but i don't know what url to access flood

**Comment by geekism** [comment]
http://serverip:3000/

⁣Sent from TypeApp ​

**Comment by sachaw** [comment]
Did this solve your issue, if so please close the issue.

**Comment by jfurrow** [comment]
This is not an issue with Flood. Thanks @sachaw for trying to clean things up!

**Comment by dcousens** [comment]
For others who might be using `systemd` to run `flood`:

flood.service
``` conf
[Unit]
Description=flood
After=network.target rtorrent.service

[Service]
Environment=DEBUG=*
Environment=NODE_ENV=production

Type=simple
User=rtorrent
WorkingDirectory=/home/rtorrent/flood
ExecStart=/usr/bin/node /home/rtorrent/flood/server/bin/start.js
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

rtorrent.service
``` conf
[Unit]
Description=rtorrent
After=network.target

[Service]
User=rtorrent

Type=forking
KillMode=None
ExecStart=/usr/bin/tmux new-session -c "rtorrent" -s rtorrent -n rtorrent -d rtorrent
ExecStop=/usr/bin/tmux send-keys -t rtorrent:rtorrent C-q
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
