### ISSUE TITLE
Several issues spotted

### ISSUE THREAD

**Issue by mirolm** [jfurrow/flood#467]
1. Sometimes flood freezes on page load. It takes several page refreshes to load normally.

![flood_freeze](https://user-images.githubusercontent.com/9135358/31538533-8c8d60b0-b00e-11e7-85f5-6abcfbaa174d.png)

I think it is a matter of synchronization - if other sections load before "Authentication Status" then page freezes. This happens very rare when i connect to flood locally - i need like 10-20 refreshes for it to freeze like this. At my work where my connection is proxied to a different location it happens 1 of every 2-3 loads.

2. After last update from yesterday i notice chrome gives the following error:

```
app.js:19 Uncaught TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at t.value (app.js:19)
    at Object.ID_4 (app.js:19)
    at t.e._invokeCallback (app.js:17)
    at t.e.dispatch (app.js:17)
    at t.value (app.js:17)
    at EventSource.handleTaxonomyFullUpdate (app.js:18)
```

This happens to me mostly at work too - flood continues to work as usual, but this errors shows in chrome development tools.

3. One time i managed to break flood settings database. It took several setting changes and page refreshes to do so. When this happened flood refused to load and i needed to reinstall.

I will try to reproduce this and see when and how it happens.

Will it be better to use some file database like SQLite for example instead of json flat files to store the application settings and data?

4. Some eye candy stuff:
- torrent start button - make it green on hover.
- torrent stop button - make it red on hover.
- remove torrent pause button - it does not work anyway. can be replaced with create torrent - mktorrent console utility can be called to do so.
- add torrent button - make it green on hover.
- delete torrent button - make it red on hover.

**Comment by sachaw** [comment]
Good idea with the color on the buttons, for a MySQL back-end I made a crude php script that accepts post requests and writes the the db file, due to flood using bcrypt, it is also compatible with php's password hashing api
https://github.com/sachaw/flood-db-updater

**Comment by dcousens** [comment]
What should the `pause` button do anyway?

**Comment by jfurrow** [comment]
The pause button literally does nothing — this is an embarrassing secret that has some how gone unnoticed, even by myself, until now. I'm not sure what it's supposed to do — I think I just built it into the UI because ruTorrent has it, but never figured out what the behavior was.

So let's remove it!

**Comment by jfurrow** [comment]
@mirolm It would be great if you could file individual issues for each of these ideas! That way we can have a discussion about each one independently.

**Comment by mirolm** [comment]
Sorry about that - will break this into separate issues/enhancements and then close this one.

**Comment by mirolm** [comment]
Issue from point 2 was not seen after last big update. For others i filed separate ones.

**Comment by jfurrow** [comment]
Thanks @mirolm — I appreciate you doing that!
