### ISSUE TITLE
Update implementation of bcrypt to use the $2y prefix

### ISSUE THREAD

**Issue by sachaw** [jfurrow/flood#468]
bcrypt has been around for a long time, as such old revisions are now deemed insecure, as it stands now you are storing them with the $2a prefix.
ref:
https://security.stackexchange.com/questions/20541/insecure-versions-of-crypt-hashes

**Comment by jfurrow** [comment]
@sachaw Thanks for bringing this up.

I'm not a security expert, but I do not believe the prefix is enough to determine the security of the hashed passwords.

Spurred by this issue, I did some research and found a [significantly more popular and active bcrypt](https://github.com/kelektiv/node.bcrypt.js) implementation. The `$2a` prefix insecurities [referenced in the stackexchange thread](https://security.stackexchange.com/a/20543) are apparently not applicable for this module, as stated [here](https://github.com/kelektiv/node.bcrypt.js#security-issuesconcerns).

Thanks again for bringing this up — I'm happy that Flood will be using a more widely used bcrypt module.
