### ISSUE TITLE
package-lock.json is overwritten by npm install

### ISSUE THREAD

**Issue by varyoo** [jfurrow/flood#473]
So package-lock.json has been added to the repository, I hurry to test it:

~~~ txt
$ git clone https://github.com/jfurrow/flood
$ cd flood
$ npm install
$ git status
modified:   package-lock.json
~~~

I can observe in this repository 's package.json what is described in this answer on why `npm install` would overwrite package-lock: https://stackoverflow.com/a/45566871

**Comment by midzer** [comment]
Perhaps some1 forgot to push latest `package-lock.json` to repo.

**Comment by mirolm** [comment]
Is it okay config.js and alot of server side javascript to be included into main.js in assets?

**Comment by jfurrow** [comment]
@varyoo It does make sense to heed the advice in the stackoverflow post, and use exact versions. I'll make this change.

@mirolm You're right that `config.js` should probably not be in the bundle, but none of the server side JavaScript is included.

**Comment by jfurrow** [comment]
@varyoo I decided _not_ to use specific versions of dependencies, in favor of more up-to-date dependencies. I'll keep `package-lock.json` for now, and when the `--from-lock-file` option is supported, we'll recommend this in the readme.
