### ISSUE TITLE
Flood page freeze on main page load

### ISSUE THREAD

**Issue by mirolm** [jfurrow/flood#489]
Sometimes flood freezes on page load. It takes several page refreshes to load normally.

![flood_freeze](https://user-images.githubusercontent.com/9135358/31849416-6f22b934-b64a-11e7-8ed7-493bdfc23c9d.png)

I think it is a matter of synchronization - if other sections load before "Authentication Status" then page freezes. This happens very rare when i connect to flood locally - i need like 10-20 refreshes for it to freeze like this. At my work where my connection is proxied(and have way bigger latency) to a different location it happens 1 of every 2-3 loads.

**Comment by randomnonsense** [comment]
Never happens to me. How are you communicating with rtorrent, tcp or socket?

**Comment by mirolm** [comment]
In my config flood and rtorrent are on same machine and i use tcp. 

By locally i mean i connect from my desktop machine to my seedbox where flood is in my local network. In this case flood freezes very rare, but you still make it after several refreshes.

It usually happens when i connect to flood from work to monitor torrents and in this case latency is bigger. If i use some proxy to simulate bigger latency this issue becomes even more frequent.

**Comment by mirolm** [comment]
Yes i have nginx in front of it and i redirect all flood static content via nginx location. Other flood stuff is proxied from nginx. I can attach my config if it can help to debug this.

I do not have proxy at home it is just internet --> router --> nginx --> flood.

**Comment by randomnonsense** [comment]
Let me solve this for you then. Firstly, use nginx as SSL terminator if you use SSL (so your client connects to nginx via ssl, then nginx bounces to flood plaintext). Secondly, the default proxy caches nginx uses are too small. Try this:

location ~ ^/flood {
                rewrite ^/flood/(.*) /$1 break;
                proxy_pass http://<someip>:3000;
                proxy_buffering on;
                proxy_buffer_size 32k;
                proxy_buffers 4 32k;
                proxy_max_temp_file_size 0;
}

Or rise the buffers as needed. I have over 5000 torrents in my rtorrent and this works for me via long distance connection at around 40ms.

**Comment by mirolm** [comment]
In my config i have:

        proxy_buffers 8 32k;
        proxy_buffer_size 64k;
        large_client_header_buffers 8 32k;

    location ~* \.(js|map|png|xml|ico|json|svg|css|woff|woff2|eot|ttf)$ {
        root /media/lv2/seedbox/flood/server/assets/;
        try_files $uri =404;
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://localhost:3000;
        proxy_redirect off;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $http_upgrade;
    }

I will try the one you suggest.

**Comment by randomnonsense** [comment]
Keep things simple. All those header definitions are unnecessary. Also rather "etag" than "expire" flood resources. It is still in development. At any moment anything can change and this way things may get "stuck".

If you want to use flood at /flood/, then you need to add to your config.js too.

**Comment by jfurrow** [comment]
I'm going to close this as it's not an issue with Flood.
