### ISSUE TITLE
Fresh install - account registration is not offered.

### ISSUE THREAD

**Issue by drphr4ud** [jfurrow/flood#497]
New CentOS 7 install. 
SELinux disabled.

nvm scripted install of node as the user "flood" from within /home/flood
```

[flood@media ~]$ whoami
flood
[flood@media ~]$ pwd
/home/flood
[flood@media ~]$ uname -a
Linux media 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[flood@media ~]$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[flood@media ~]$ node --version
v8.7.0

git clone https://github.com/jfurrow/flood.git
cd flood
npm install
npm run build
npm start
```

Compile and install went error-free. Just some warnings about fsevent which seems to be only applicable on MacOS, not CentOS.

**Expected behavior:**

Visiting http://ip:3000 should prompt for creation of username and password.

**Actual behavior:** 

Visiting http://ip:3000 prompts for an existing password.

Contents of config.js:

```
const CONFIG = {
  baseURI: '/',
  dbCleanInterval: 1000 * 60 * 60,
  dbPath: './server/db/',
  floodServerHost: '0.0.0.0',
  floodServerPort: 3000,
  floodServerProxy: 'http://127.0.0.1',
  maxHistoryStates: 30,
  pollInterval: 1000 * 5,
  secret: 'BBA1F87C28477C209E314A',
  scgi: {
    host: 'localhost',
    port: 45000,
    socket: false,
    socketPath: '/tmp/rtorrent.sock'
  },
  ssl: false,
  sslKey: '/etc/letsencrypt/live/privkey.pem',
  sslCert: '/etc/letsencrypt/live/fullchain.pem',
  torrentClientPollInterval: 1000 * 2
};

module.exports = CONFIG;

```

Tried stopping service, then `rm /home/flood/flood/server/db/users.db` and restart.

Tried starting over from scratch after 

```
rm -rf /home/flood/flood 
git clone https://github.com/jfurrow/flood.git
cd flood
npm install
npm run build
npm start


```

**Comment by meoberto** [comment]
Debian 9.2 here.
I fresh installed flood a couple of minutes ago and I've been struggling with this exact problem ever since.
```rtorrent@ignis:~/flood$ node --version
v6.11.4
```

**Comment by heihachi** [comment]
Getting this now as well with new install

`[heihachi@server flood]$ node --version
v8.6.0`

**Comment by sakhavhyand** [comment]
Same here on Debian Jessie and Node v8.7.0

**Comment by antoine-radio** [comment]
You can resolve it using older commits :)

**Comment by varyoo** [comment]
Which one? I rolled back to https://github.com/jfurrow/flood/commit/3752a0cf92def5f1d844a93f6657eb9547efd383

**Comment by jfurrow** [comment]
Thanks for the reports, everyone. This is fixed.
