### ISSUE TITLE
Bower.json missing?

### ISSUE THREAD

**Issue by Kuchiru** [jfurrow/flood#5]
Hi,

I attempted to install your project, having never used bower before i gave it a go but it tells me that bower.json is missing and wont continue.
Will you add this at a later stage?

regards

**Comment by jfurrow** [comment]
Hi @Kuchiru! Thanks for your interest. Sorry, but the readme was terribly out of date (I'm not using Bower at all anymore). I've since [updated it](https://github.com/jfurrow/flood#how-to-use).

Please let me know if you have any other questions!

**Comment by Kuchiru** [comment]
Awesome thanks for the update and keep it up, this project is awesome!
