### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by brezinajn** [jfurrow/flood#501]
Current build gives me ```Unexpected token <``` on page load. Server delivers with 200 but the page won't load and gives me only this error.

**Comment by sachaw** [comment]
need more detail, what does the console say?

**Comment by brezinajn** [comment]
![image](https://user-images.githubusercontent.com/15677736/31989351-5a3e436e-b972-11e7-98cc-9303b8160a1f.png)
Ungfortunately there is not much I can provide.

**Comment by sachaw** [comment]
Go the server that flood is running on and paste a dump of what it says

**Comment by brezinajn** [comment]
```
Flood server starting on http://192.168.10.10:80.

GET / 200 8.582 ms - 575
GET /torrent/static/css/main.bb75f1da.css 200 3.135 ms - 575
GET /torrent/static/js/main.1e166a63.js 200 1.175 ms - 575
GET /torrent/favicon.ico 304 1.909 ms - -
```

**Comment by sachaw** [comment]
when you started flood, did you run it with sudo or not

**Comment by larvata** [comment]
Maybe you forget to run `npm run build`.

**Comment by jfurrow** [comment]
@brezinajn What version of Node and NPM? (run `node -v` and `npm -v`)

**Comment by brezinajn** [comment]
On port 80 I run it with sudo, on ports > 1000 I don't. Both yield the same results. Unfortunately I did run ```npm run build```. Ran it again just to be tripple sure. Same result.
node: 8.7.0
npm: 5.5.1

**Comment by sachaw** [comment]
I had a similar issue had to reinstall node as standard user.
try removing flood and starting from scratch (no sudo), but also run this to allow node to use port 80/443 without sudo `sudo setcap 'cap_net_bind_service=+ep' `which node`

**Comment by brezinajn** [comment]
Reinstalling node worked like a charm.
