### ISSUE TITLE
npm install --production failed

### ISSUE THREAD

**Issue by calsc** [jfurrow/flood#509]
i installed flood follow “https://freedif.org/flood-modern-web-ui-for-rtorrent/”
but when i run "npm install --production",I Can not continue.
please help！ I use debian8.
==============
root@localhost:/srv/torrent/flood# npm install --production
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
Killed         ....] | extract:to-fast-properties: verb gentlyRm don't care about contents; nuking /srv/torrent/
=============

**Comment by wopian** [comment]
`Killed ....` is the only error there (that `WARN` should be an `INFO`). The machine you're running it on ran out of memory and killed the npm service.

Some more information would be useful in triaging the issue:

Free system memory available? `free`
Node version? `node -v`
NPM version? `npm -v`
Verbose output of the install failure: `npm install --production --loglevel verbose`

**Comment by d0tfile** [comment]
May be relevant to this issue.
1. npm install --production
2. npm run build:
Error: Cannot find module 'webpack-manifest-plugin'

Then in root directory:
1. npm install webpack-manifest-plugin
2. npm run build:
Creating an optimized production build...
Compiled successfully.

I'm not nodejs dev, but suppose missing dependency in package.json. Package webpack-manifest-plugin is listed only in devDependencies.
Can anyone check and confirm/reject my guess?

**Comment by calsc** [comment]
i run the flood,but it can not start.

root@sd-86167:~# systemctl status flood                                                    
● flood.service                                                                            
   Loaded: loaded (/etc/systemd/system/flood.service; enabled)                             
   Active: failed (Result: start-limit) since Sat 2017-10-28 11:52:10 CEST; 40s ago        
  Process: 15417 ExecStart=/usr/bin/npm start (code=exited, status=1/FAILURE)              
 Main PID: 15417 (code=exited, status=1/FAILURE)                                           
                                                                                           
Oct 28 11:52:10 sd-86167.dedibox.fr systemd[1]: Unit flood.service entered failed state.   
Oct 28 11:52:10 sd-86167.dedibox.fr systemd[1]: flood.service holdoff time over, sched...t.
Oct 28 11:52:10 sd-86167.dedibox.fr systemd[1]: Stopping flood.service...                  
Oct 28 11:52:10 sd-86167.dedibox.fr systemd[1]: Starting flood.service...                  
Oct 28 11:52:10 sd-86167.dedibox.fr systemd[1]: flood.service start request repeated t...t.
Oct 28 11:52:10 sd-86167.dedibox.fr systemd[1]: Failed to start flood.service.             
Oct 28 11:52:10 sd-86167.dedibox.fr systemd[1]: Unit flood.service entered failed state.   
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by calsc** [comment]
86167:~# cd /srv/torrent/flood/               
root@sd-86167:/srv/torrent/flood# npm start --producti
on                                                    
                                                      
> flood@1.0.0 start /srv/torrent/flood                
> node server/bin/start.js                            
                                                      
Failed to start web server:                           
Static assets (index.html) are missing. Please check t
he 'Compiling assets and starting the server' section 
of README.md.                                         
                                                      
npm ERR! flood@1.0.0 start: `node server/bin/start.js`
npm ERR! Exit status 1                                
npm ERR!                                              
npm ERR! Failed at the flood@1.0.0 start script.      
npm ERR! This is most likely a problem with the flood 
package,                                              
npm ERR! not with npm itself.                         
npm ERR! Tell the author that this fails on your syste
m:                                                    
npm ERR!     node server/bin/start.js                 
npm ERR! You can get their info via:                  
npm ERR!     npm owner ls flood                       
npm ERR! There is likely additional logging output abo
ve.                                                   
npm ERR! System Linux 4.12.8-041208-generic           
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start
" "--production"                                      
npm ERR! cwd /srv/torrent/flood                       
npm ERR! node -v v6.11.4                              
npm ERR! npm -v 1.4.21                                
npm ERR! code ELIFECYCLE                              
npm WARN This failure might be due to the use of legac
y binary "node"                                       
npm WARN For further explanations, please read        
/usr/share/doc/nodejs/README.Debian                   
                                                      
npm ERR!                                              
npm ERR! Additional logging details can be found in:  
npm ERR!     /srv/torrent/flood/npm-debug.log         
npm ERR! not ok code 0

**Comment by d0tfile** [comment]
@calsc on README Pre-Requisites: Install NodeJS version 7.x.x or higher.

**Comment by calsc** [comment]
@d0tfile 

i install nodejs 8.1.0.
but i am also can not run it.

root@localhost:/srv/torrent/flood# systemctl start flood
root@localhost:/srv/torrent/flood# systemctl status flood
● flood.service
   Loaded: loaded (/etc/systemd/system/flood.service; enabled)
   Active: active (running) since Sun 2017-10-29 04:20:05 EDT; 594ms ago
 Main PID: 12859 (npm)
   CGroup: /system.slice/flood.service
           └─12859 npm
root@localhost:/srv/torrent/flood# systemctl status flood
● flood.service
   Loaded: loaded (/etc/systemd/system/flood.service; enabled)
   Active: failed (Result: start-limit) since Sun 2017-10-29 04:20:08 EDT; 2s ago
  Process: 12896 ExecStart=/usr/bin/npm start (code=exited, status=1/FAILURE)
 Main PID: 12896 (code=exited, status=1/FAILURE)

Oct 29 04:20:08 localhost.localdomain systemd[1]: flood.service: main process exited, code=exited, status=...LURE
Oct 29 04:20:08 localhost.localdomain systemd[1]: Unit flood.service entered failed state.
Oct 29 04:20:08 localhost.localdomain systemd[1]: flood.service start request repeated too quickly, refusi...art.
Oct 29 04:20:08 localhost.localdomain systemd[1]: Failed to start flood.service.
Oct 29 04:20:08 localhost.localdomain systemd[1]: Unit flood.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
root@localhost:/srv/torrent/flood#
