### ISSUE TITLE
i install flood but i can not run it

### ISSUE THREAD

**Issue by calsc** [jfurrow/flood#510]
1. apt-get install rtorrent,and run it.
2.install nodejs 8.1.0 thought nvm
3.install flood.

i run the flood. than ....
=============
root@localhost:/srv/torrent/flood# systemctl start flood
root@localhost:/srv/torrent/flood# systemctl status flood
● flood.service
Loaded: loaded (/etc/systemd/system/flood.service; enabled)
Active: active (running) since Sun 2017-10-29 04:20:05 EDT; 594ms ago
Main PID: 12859 (npm)
CGroup: /system.slice/flood.service
└─12859 npm
root@localhost:/srv/torrent/flood# systemctl status flood
● flood.service
Loaded: loaded (/etc/systemd/system/flood.service; enabled)
Active: failed (Result: start-limit) since Sun 2017-10-29 04:20:08 EDT; 2s ago
Process: 12896 ExecStart=/usr/bin/npm start (code=exited, status=1/FAILURE)
Main PID: 12896 (code=exited, status=1/FAILURE)

Oct 29 04:20:08 localhost.localdomain systemd[1]: flood.service: main process exited, code=exited, status=...LURE
Oct 29 04:20:08 localhost.localdomain systemd[1]: Unit flood.service entered failed state.
Oct 29 04:20:08 localhost.localdomain systemd[1]: flood.service start request repeated too quickly, refusi...art.
Oct 29 04:20:08 localhost.localdomain systemd[1]: Failed to start flood.service.
Oct 29 04:20:08 localhost.localdomain systemd[1]: Unit flood.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
root@localhost:/srv/torrent/flood#

**Comment by wopian** [comment]
Start flood with `npm start` and paste the error output

**Comment by calsc** [comment]
@wopian root@localhost:~# cd /srv/torrent
root@localhost:/srv/torrent# cd flood
root@localhost:/srv/torrent/flood# npm start

> flood@1.0.0 start /srv/torrent/flood
> node server/bin/start.js

Failed to start web server:
Static assets (index.html) are missing. Please check the 'Compiling assets and starting the server' section of README.md.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 start: `node server/bin/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-29T15_52_33_695Z-debug.log
root@localhost:/srv/torrent/flood#

**Comment by wopian** [comment]
Run `npm run build` once and then `systemctl start flood` will be 👌

**Comment by calsc** [comment]
hi @wopian 

i run "npm run build",but the problem still exists

root@localhost:/srv/torrent/flood# npm run build

> flood@1.0.0 build /srv/torrent/flood
> node client/scripts/build.js
module.js:487
    throw err;
    ^
Error: Cannot find module 'webpack-manifest-plugin'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/torrent/flood/client/config/webpack.config.prod.js:8:24)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/torrent/flood/client/scripts/build.js:21:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 build: `node client/scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by SanPilot** [comment]
Read (this)[https://github.com/jfurrow/flood#compiling-assets-and-starting-the-server] section of README.md. I think you may be forgetting some steps.

**Comment by d0tfile** [comment]
@calsc previously you run "npm install --production", right? You can fix it by "npm install webpack-manifest-plugin" in flood root or just "npm install". After run "npm run build"

@SanPilot npm has "--production" flag. With that flag npm installs all dependencies but dev. (I described issue here: https://github.com/jfurrow/flood/issues/509#issuecomment-340113161)

**Comment by mirolm** [comment]
Please read the README as SanPilot suggested, because the way to build flood got changed with recent commits. As stated there:

> Compiling assets and starting the server

Run npm install.
Run npm run build.
Run npm start.

**Comment by dcousens** [comment]
@calsc was your issue resolved?

**Comment by calsc** [comment]
no ...i gave up
________________________________
发件人: Daniel Cousens <notifications@github.com>
发送时间: 2017年11月28日 9:14
收件人: jfurrow/flood
抄送: calsc; Mention
主题: Re: [jfurrow/flood] i install flood but i can not run it (#510)


@calsc<https://github.com/calsc> was your issue resolved?

―

**Comment by noraj1337** [comment]
Sorry to hear that :/
