### ISSUE TITLE
Error on login with latest version

### ISSUE THREAD

**Issue by romancin** [jfurrow/flood#515]
Hello, since I updated to the current flood version, node service gives me a segmentation fault when I try to login:

root@0d304113ef80:/usr/flood$ npm start

> flood@1.0.0 start /usr/flood
> node server/bin/start.js

Flood server starting on https://0.0.0.0:3000.

Segmentation fault
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! flood@1.0.0 start: `node server/bin/start.js`
npm ERR! Exit status 139
npm ERR!
npm ERR! Failed at the flood@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-01T18_31_53_324Z-debug.log

Here is the referenced log:
root@0d304113ef80:/usr/flood$ cat /root/.npm/_logs/2017-11-01T18_31_53_324Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle flood@1.0.0~prestart: flood@1.0.0
6 info lifecycle flood@1.0.0~start: flood@1.0.0
7 verbose lifecycle flood@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle flood@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/flood/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle flood@1.0.0~start: CWD: /usr/flood
10 silly lifecycle flood@1.0.0~start: Args: [ '-c', 'node server/bin/start.js' ]
11 silly lifecycle flood@1.0.0~start: Returned: code: 139  signal: null
12 info lifecycle flood@1.0.0~start: Failed to exec start script
13 verbose stack Error: flood@1.0.0 start: `node server/bin/start.js`
13 verbose stack Exit status 139
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid flood@1.0.0
15 verbose cwd /usr/flood
16 verbose Linux 4.2.8
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 139
22 error flood@1.0.0 start: `node server/bin/start.js`
22 error Exit status 139
23 error Failed at the flood@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 139, true ]

What can be happening?

Thank you.

**Comment by dcousens** [comment]
Try updating your system packages,  then remove `node_modules`,  then `npm i`,  and see if the problem persists.

**Comment by romancin** [comment]
Done it and the same problem. For reference, OS is Alpine 3.6.

**Comment by romancin** [comment]
Update news on this: I reverted to my old container version and logged in correctly. After having the cookie with the login information in my web browser, upgraded again to the newest version and flood works well, so it seems the authentication only is the problem.

**Comment by romancin** [comment]
Finally I have fixed it.
It seems there is a problem with nodejs 8 in Alpine Linux with bcrypt module, solved by doing on install:
npm install --build-from-source=bcrypt 

Here this problem is discussed: https://github.com/kelektiv/node.bcrypt.js/issues/528
