### ISSUE TITLE
Allowing multiple users with separate rtorrent instances to use the same flood server

### ISSUE THREAD

**Issue by jvacek** [jfurrow/flood#518]
Currently, when using flood with multiple users, flood can only listen to one single rtorrent instance, and seems to carry appearance settings across users.

It would be nice if it was possible to extend the multiple user feature and implement more administrative features to allow for more users who have their own rtorrent instances using the same server.

The first created account would automatically become the admin, and all new accounts would become normal users with the same UI-accessibility except for adding more users.
When a new account is created, there should be an option for the admin to specify which socket to listen to

Also, I've been using flood for like 10 minutes and I am 99% switching to using it over rutorrent, it is so much nicer oh my god

**Comment by dcousens** [comment]
duplicate (sort of) of https://github.com/jfurrow/flood/issues/460

**Comment by noraj** [comment]
duplicate (sort of) of #413
