### ISSUE TITLE
Removing tags doesn't work

### ISSUE THREAD

**Issue by jvacek** [jfurrow/flood#521]
giving a torrent a tag called "test" works, however removing it by emptying out the field and saving it does not, the current workaround is to put a space in the field, which will remove the tag

**Comment by jfurrow** [comment]
Oof, yeah, you're right.

**Comment by jwbuiter** [comment]
I created a PR for this

**Comment by Sibicle** [comment]
Confirming this works in the latest version—can be closed.

**Comment by jfurrow** [comment]
Thanks @jwbuiter and @Sibicle!
