### ISSUE TITLE
Expose /RPC2

### ISSUE THREAD

**Issue by Nomuas** [jfurrow/flood#522]
Hello, I'm using flood with rtorrent which expose scgi through an unix socket.
Could you add an URI to map /RPC2 on the rtorrent socket so i don't need to install nginx just to proxy request ?

This is needed by severals apply and module web browser.

Thanks !

**Comment by Jeoffreybauvin** [comment]
Flood shound't be the entrypoint for RPC2... 

On my side, I do have Nginx to proxy Flood & RPC2...

**Comment by Nomuas** [comment]
Your side...
And I already write that possibility can remove the necessity of an nginx proxy.
My access to Flood is behind an ingress controler.
Flood is an interface to rtorrent so it can do this type of proxy.

**Comment by jfurrow** [comment]
Sorry, Flood shouldn't do this.
