### ISSUE TITLE
Storage Error - Tracker

### ISSUE THREAD

**Issue by phonicmouse** [jfurrow/flood#524]
Keep getting this error...do you know what it is?
`Tracker Message | Storage error: [File chunk write error: Cannot allocate memory.]`

**Comment by geekism** [comment]
Looks like youve ran out of memory.. check free ram and cache and see if that helps

**Comment by phonicmouse** [comment]
Yeah thanks, i set up rtorrent wrong, it was allowed only to access a small part of ram...anyway, thanks
