### ISSUE TITLE
[solved] Login to web ui

### ISSUE THREAD

**Issue by jona133** [jfurrow/flood#529]
Hi,

I've been using flood since a couple of weeks now and let me tell you first that it is awesome and a really great work !
So, since today i can connect to the web interface, but I can't log in. My request maybe weird maybe I forgot my password so i'm asking if someone know a way to reset flood ? Or how can I reach the db?
I'm little a bit loose in those files.

Thanks you for your great work !

**Comment by noraj1337** [comment]
Into your flood folder `server/db/users.db`. Here is stored your user account.

**Comment by jona133** [comment]
Thanks you to be that quick, if someone has the same issue you just need to delete the file in flood/server/db/users.db and restart flood. It will now prompt to create a new user.
Again thanks you, nice work !

**Comment by noraj1337** [comment]
@jona133 if problem solved, can you close the issue please ?

@jfurrow I think we can put a _Question_ label on the issue. This kind of issue is mostly due to an absence of documentation. Typically a F.A.Q. could have answer that.

**Comment by jfurrow** [comment]
@noraj1337 Agreed, documentation could be improve significantly.

**Comment by noraj1337** [comment]
FAQ created: https://github.com/jfurrow/flood/wiki/F.A.Q.#i-forgot-my-password-how-can-i-recover-it

**Comment by joegnis** [comment]
To change the password, a way to do it is

1. Install https://github.com/ranisalt/node-argon2-cli
2. Run `echo -n "new-password" | argon2-cli -e`
3. Override the content of the `password` field in `users.db` with the output from the above command
4. Restart the server

Hope it can be helpful.
