### ISSUE TITLE
Check hash is not working

### ISSUE THREAD

**Issue by ginja85** [jfurrow/flood#537]
For cross seeding I often use the force recheck in rutorrent, is such a feature available in flood and if not could it be added?

Thanks.

**Comment by jfurrow** [comment]
@ginja85 Right-click on a torrent and click `Check Hash`

**Comment by ginja85** [comment]
I've tried check hash, which doesn't seem to do anything, file location is correct, if I go to rutorrent and click force recheck that works.

**Comment by noraj1337** [comment]
I can see this king of log:

```
Nov 27 18:56:33 hostname npm[10172]: POST /api/client/torrents/check-hash 200 13.565 ms - 13
```

But yes nothing happen or at least files are not checked.
