### ISSUE TITLE
[Request] Becoming a member

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#545]
Hey @jfurrow. As you can see this days I'm trying to help with flood development. That's why I ask you if I can become a member of the repository. That will mainly allow me to create and apply labels to issues. Because a lot of them have no labels and it's not easy to manage a huge quantity of issues without labels.

Github permissions does not allow fine grain controls (even for organizations) but I will use my member permissions only for issues, not for merging PR, etc..  You're better than me for that.

**Comment by noraj1337** [comment]
- [How we organize GitHub issues: A simple styleguide for tagging](https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/)
- [How to use Github issues to attract new contributors](http://radek.io/2015/08/24/github-issues/)

**Comment by jfurrow** [comment]
@noraj1337 I've definitely noticed your efforts lately, thanks so much for helping!

I could definitely use the help organizing these issues. I'll add you and @dcousens as collaborators. For the time being, I would like for both of you _not_ to merge PRs. Feel free to review them, but I'd like to give a final 👍 on them before merging. This is not to say I'm more qualified be gatekeeper, I'd just feel more comfortable with this approach, for now. Unless I die, then you two can merge away!

**Comment by dcousens** [comment]
@jfurrow why not enable branch protection?  I don't _want_ to be able to merge PRs (or commits).

**Comment by dcousens** [comment]
> Restrict who can push to this branch
> Specify people or teams allowed to push to this branch. Required status checks will still prevent these people from merging if the checks fail.

And put yourself as the only person,  coupled with `Require pull request reviews before merging`

**Comment by jfurrow** [comment]
Hmm, I don't see that option:
<img width="750" alt="screen shot 2017-11-20 at 10 45 37 pm" src="https://user-images.githubusercontent.com/1134755/33058493-b4f8877e-ce44-11e7-9594-17cce5ff44ba.png">

**Comment by noraj1337** [comment]
> @dcousens There is an option to require "code owners" to approve PRs before merging — I just enabled this, but I'm not sure if collaborators are also considered "code owners." I already had branch protection enabled, but it only prevents force pushing and deleting branches.

In a user repo, Collaborators have write permissions but not owner ones : [Permission levels for a user account repository](https://help.github.com/articles/permission-levels-for-a-user-account-repository/).

**Comment by noraj1337** [comment]
> I could definitely use the help organizing these issues. I'll add you and @dcousens as collaborators. For the time being, I would like for both of you not to merge PRs. Feel free to review them, but I'd like to give a final 👍 on them before merging. This is not to say I'm more qualified be gatekeeper, I'd just feel more comfortable with this approach, for now. Unless I die, then you two can merge away!

Of course, that's what I said, I won't merge.

**Comment by noraj1337** [comment]
I dont know if you want to but it is possible to create an organization transfer the repo to the org, and then we will have full features of an org.

- [Repository permission levels for an organization](https://help.github.com/articles/permission-levels-for-an-organization)
- [Permission levels for an organization](https://help.github.com/articles/repository-permission-levels-for-an-organization)
- [ Transferring to an organization](https://help.github.com/articles/repository-permission-levels-for-an-organization)

When you're member of an org you still continue to log in with the same account.
