### ISSUE TITLE
Create contribution guideline

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#547]
See PR #546

## What's done

* add some contributions guidelines (CONTRIBUTING.md)
* add an issue template (ISSUE_TEMPLATE.md)
* add a PR template (PULL_REQUEST_TEMPLATE.md)
* create new labels and document them in CONTRIBUTING.md

New files can be seen [here](https://github.com/jfurrow/flood/tree/git/contribution/.github).

## Why?
> To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's root, docs, or .github folder. Then, whenever someone opens a pull request or creates an issue, they will see a link to that file.
>
> For the repository owner, contribution guidelines are a way to communicate how people should contribute.
>
> For contributors, the guidelines help them verify that they're submitting well-formed pull requests and opening useful issues.
>
> For both owners and contributors, contribution guidelines save time and hassle caused by improperly created pull requests or issues that have to be rejected and re-submitted.

[Setting guidelines for repository contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

> When you add an issue template to your repository, project contributors will automatically see the template's contents in the issue form body. Templates customize and standardize the information you'd like included when contributors open issues.

[Creating an issue template for your repository](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

> When you add a pull request template to your repository, project contributors will automatically see the template's contents in the pull request form body. Templates customize and standardize the information you'd like included when contributors create pull requests.
>
> Contributors can use templates to describe the proposed changes in their pull requests according to the repository's contributing guidelines. For more information, see "Setting guidelines for repository contributors."

[Creating a pull request template for your repository](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

# Note

Those templates are not absolutely and universally right. Please if you have suggestions, give them.

**Comment by jfurrow** [comment]
I really appreciate this, @noraj1337. Thanks! I especially appreciate the thoughtfulness of the code of conduct.

I'll close, feel free to reopen if there's unfinished business.
