### ISSUE TITLE
Sidebar stats should show 0 instead of NaN

### ISSUE THREAD

**Issue by vBm** [jfurrow/flood#55]
This is rather a minor thing.
On fresh start, instead of showing real number we get NaN.

![2016-06-28_13-24-39](https://cloud.githubusercontent.com/assets/80596/16413720/fada879a-3d33-11e6-9d93-b8fc3bba6b31.png)

edit: silly me, switching the two in title xD

**Comment by jfurrow** [comment]
Agreed, should handle this better. Stay tuned...

**Comment by jfurrow** [comment]
Honestly I'm not sure if I inadvertently fixed this a while ago, but I can't reproduce it on a fresh install so I'm labelling it as such and closing. Please re-open if you see this again!

**Comment by vBm** [comment]
Yeah, It's fixed 👍 
Thanks xD
