### ISSUE TITLE
Make username case-insensitive

### ISSUE THREAD

**Issue by SanPilot** [jfurrow/flood#552]
See PR #553 

## Expected Behavior

When logging in, any variation of the case of the username should be accepted as valid.

## Current Behavior

Only the exact case is accepted.

## Possible Solution

1. Search DB in case-insensitive mode for submitted username
2. When creating users, search for existing users in case-insensitive mode

## Steps to Reproduce (for bugs)

1. Log out of Flood
2. Login with username with a different case (ex. all lowercase, uppercase)
3. Login fails.

## Context

Most applications accept any variation of the user name.

## Your Environment

* Version used:
  + Version (stable release) `git --no-pager tag`
v1.0.0
  + Commit ID (development release) `git --no-pager log -1`
```
commit 2fd0edae15d21bcb79421b6ca1b07c9ff7705bc7
Merge: aa09157 ff9efd2
Author: John Furrow <hello@johnfurrow.com>
Date:   Thu Nov 16 20:13:13 2017 -0800

    Merge pull request #539 from jfurrow/add-logout
    
    Add logout functionality
```
* Environment name and version (e.g. Chrome 39, node.js 5.4):
    Firefox 57, Node v6.12.0
* Operating System and version:
Ubuntu 17.10 Server
## Note

You may try to follow the update procedure described in the README and try again before opening this issue.

**Comment by noraj1337** [comment]
Before doing that, let's discuss if it is really the wanted behavior. Maybe case sensitive is fine.

Personally I'm for case insensitive username.

There is already a discussion here. [Should usernames be case-sensitive?](http://community.dzonesoftware.com/questions/27027/should-usernames-be-case-sensitive.html). As said here:
> Good luck managing a system where admin, Admin, ADMIN, and admIn are four separate accounts.

**Comment by dcousens** [comment]
Usersnames aren't authentication,  they're a non-secret, user-friendly identifier for the purposes of authentication via a shared secret.

**Comment by jfurrow** [comment]
Okay, I'm convinced. Let's do this.
