### ISSUE TITLE
Set up automated testing

### ISSUE THREAD

**Issue by jfurrow** [jfurrow/flood#556]
Let's set up a CI with a free service (CircleCI or TravisCI or...?) and fail any PR when:
1. `npm run build` fails
2. `npm run lint` fails
3. `npm run test` fails (we don't actually have tests, lol, so we might need to make this pass artifically for now)

I'm not exactly certain of the what limitations might exist, but I'd love to test `npm run build` against multiple common environments — macOS, Windows, and several popular Linux distros.

**Comment by noraj1337** [comment]
Very gread idea. All CI I used were using docker containers, I don't know if it's possible to test into macOS and Windows.

**Comment by dcousens** [comment]
`TravisCI` is one click,  but it is going to depend on how you interact with a pseudo `rtorrent`,  mock it?

**Comment by jfurrow** [comment]
> All CI I used were using docker containers, I don't know if it's possible to test into macOS and Windows.

Same here — it looks like CircleCI offers builds on Windows and macOS, but it's not cheap. So that's probably not going to happen, for now.

@dcousens Mocking needs to be figured out, for sure! I'll defer thinking too much about that right now, and just focus on getting CI set up.
