### ISSUE TITLE
Flood won't show native added torrent added_date properly

### ISSUE THREAD

**Issue by xiayyu** [jfurrow/flood#566]
Flood won't show native added torrent added date properly.
## Expected Behavior

Expecting Flood web gui show torrent added date correctly.
## Current Behavior

Only torrent added via Flood have a proper added date.
Torrent added by the native rtorrent client have a added date of 1/1/1970(absent)
## Possible Solution

I notice that Flood use a rtorrent custom field as added time
https://github.com/jfurrow/flood/blob/e416666851ceae390977d7b9113cb1648560743f/server/models/ClientRequest.js#L142
which won't generate by native client.
The native rtorrent client provide a load_date by command `d.load_date`. I am not sure if it's the wanted date. Hoping you guys have a check or just add a new column to show this date in the webui.
## Steps to Reproduce (for bugs)

1. Adding a torrent via the native rtorrent client
2. View the webui 'Added' column

**Comment by jfurrow** [comment]
I'll check `d.load_date`, but as far as I know, rtorrent just doesn't keep track of the date a torrent was added. The custom field, `addtime`, is used by ruTorrent, so that's why I decided to use that in Flood as well.

**Comment by xiayyu** [comment]
@jfurrow 
You are right. I tested the `d.load_date`, it refresh when rtorrent restarted. As its name, it's loaded time but not added time.
Now my solution is adding torrent whith the custom infomation agree with Flood's definition.
