### ISSUE TITLE
peer's encrypted status too big

### ISSUE THREAD

**Issue by noraj1337** [jfurrow/flood#571]
The peer's encrypted status in the peer detail columns is too big.

## Expected Behavior

Size of a normal icon.

## Current Behavior

![](https://i.imgur.com/J3JSCql.png)

## Context

PR #554

**Comment by randomnonsense** [comment]
Size is right at my end. The icon is horrible though. Wouldn't be simpler to make it "Yes" or "No" thing?

**Comment by noraj1337** [comment]
Opera 49.0 on the left, Firefox 57.0 on the right:

![](https://i.imgur.com/CVk5IhY.png)

**Comment by noraj1337** [comment]
@randomnonsense Are you using a Blink-based (rendering engine) web browser, a.k.a. a chromium based browser (like chrome, opera, vivaldi, ...) ?

**Comment by jfurrow** [comment]
Closed by https://github.com/jfurrow/flood/issues/571
