### ISSUE TITLE
Flood should respect rtorrent bandwidth schedules

### ISSUE THREAD

**Issue by dcousens** [jfurrow/flood#578]
For example,  given the following bandwidth schedule in `.rtorrent.rc`:

```
schedule2 = night_dl, 00:00:00, 1, download_rate=0
schedule2 = night_ul, 00:00:00, 1, upload_rate=0
schedule2 = peak_dl, 08:00:00, 1, download_rate=20
schedule2 = peak_ul, 08:00:00, 1, upload_rate=1
```

Flood will fight **all day** to set the limits back to `0` (or whatever Flood wants).
Can we enforce Flood to respect these values?  Or otherwise,  disable bandwidth management in Flood?

**Comment by dcousens** [comment]
Related https://github.com/jfurrow/flood/issues/436

**Comment by burner-** [comment]
Looks that flood have own bw limiting UI and it works well. So is this ticket obsolete?

**Comment by dcousens** [comment]
This was actually my own misunderstanding of the schedule syntax.
