### ISSUE TITLE
Cannot Install on arm32v7/node:9.2.1-onbuild

### ISSUE THREAD

**Issue by toebbel** [jfurrow/flood#582]
Installation of argon2 dependency fails on arm architecture.

## Expected Behavior
- `npm install` for flood should work regardless of underlying platform

## Current Behavior

```
> argon2@0.16.2 install /usr/src/app/node_modules/argon2                                                                                      
> node-gyp rebuild                 

make: Entering directory '/usr/src/app/node_modules/argon2/build'      
  CC(target) Release/obj.target/libargon2/argon2/src/ref.o             
*** Error in `cc': double free or corruption (top): 0x01f62c38 ***     
libargon2.target.mk:106: recipe for target 'Release/obj.target/libargon2/argon2/src/ref.o' failed                                             
make: *** [Release/obj.target/libargon2/argon2/src/ref.o] Aborted (core dumped)                       
```

## Possible Solution
- drop argon2 dependency

## Steps to Reproduce (for bugs)
- `docker run -it arm32v7/node:9.2.1-onbuild bash` on a raspberry pi
- git clone this repo
- `npm install`

## Context
This is obviously not your fault. The maintainer of `argon2` do not support installation on all arm platforms (they made a recent change, which does not help in my situation). I would rather suggest to drop `argon2` in favor of `bcryptjs`, which is purely implemented in javascript and does not pull in any dependencies (and thus can not fail on arbitrary platforms). I can see that you migrated from `bcrypt` to `argon2` and you will have your reasons. I believe that you want to allow the broadest possible userbase to run flood. To achieve this goal, I suggest to flatten dependencies and drop native bindings.

## Your Environment

* Version used:  bba07ed  
* Environment name and version: node 9.2.1 on arm32v7
* Operating System and version: `Linux raspberrypi 4.9.41-v7+`

**Comment by d0tfile** [comment]
I have raspberry pi 2 B+ with Arch Linux installed (4.9.67-1-ARCH, armv7l). I have no errors while running "npm install" or "npm run build". Are you sure it is argon2 issue? May docker cause this issue?

**Comment by toebbel** [comment]
Which gcc compiler do you have on your raspberry? My build failed in the
node 9 Docker image. I can check later, which gcc compiler is in there.

**Comment by dcousens** [comment]
@toebbel you should file this in the Argon2 repository... not here.

**Comment by toebbel** [comment]
Hi @dcousens,
I agree that discussion makes no sense here after #583 was closed.
@d0tfile thanks for checking on your Pi, @dcousens thanks for your time 👍
