### ISSUE TITLE
RSS forceInterval and RSS Single Enclosure

### ISSUE THREAD

**Issue by ShoarW** [jfurrow/flood#584]
For Feed.js, can we please set forceInterval as true? I had an RSS feed TTL set to 600 (10 hours) and wasn't sure why it wasn't checking every 5 minutes when set. This could probably be optional but not sure.

```
this.reader = new FeedSub(options.url, {
      autoStart: true,
      emitOnStart: true,
      maxHistory: this.options.maxItemHistory,
      interval: options.interval ? Number(options.interval) : 15,
      forceInterval: true,
      readEveryItem: true
    });
```

Additionally for feedService.js, if torrent files are in a single \<enclosure/> they're not picked up. 

```
if (feedItem.enclosure && feedItem.enclosure.url) {
      return [feedItem.enclosure.url];
    }
```

This code was present [here](https://github.com/jfurrow/flood/pull/502) but not in the final version? I added it to my build and it's working perfectly.

**Comment by noraj1337** [comment]
@jfurrow Sounds easy to fix?

**Comment by noraj1337** [comment]
I'm not sure if #353 is linked.

**Comment by ShoarW** [comment]
Yeah the code I wrote is all that needs to be added. I'd make a pull request but I haven't gotten around to it. If you're up for it it'd be great.

**Comment by jfurrow** [comment]
Closed by https://github.com/jfurrow/flood/pull/669
