### ISSUE TITLE
Deleting a user doesn't prompt for confirmation

### ISSUE THREAD

**Issue by wopian** [jfurrow/flood#587]
Unintentionally pressed the `x` for my user account in the accounts section several hours ago, which visually didn't do anything. 

## Expected Behavior

Pressing `x` should have a confirmation prompt before deleting a user from the database. Especially if there is only one user, as it leaves your Flood instance wide open to anyone who accesses it until a new user is created.

## Current Behavior

Clicking the `x` button does nothing visually. Current behaviour doesn't show until you refresh or open your instance again, where you're greeted with the account creation screen which is a slight security issue since I didn't notice what happened until several hours after.

## Steps to Reproduce

1. Create an instance with a single user
2. Delete the user account in settings
3. Refresh

## Environment

* Version used:
  + Version: `1.0.0`
  + Commit: `8735aaf750b2fde761980b0c7fb1204ab52357e7`

**Comment by SanPilot** [comment]
The 'Authentication' panel of settings is not supposed to allow you to delete the current user. Instead of an 'x', it displays a badge: 'Current User', but for some reason, this badge doesn't appear on the first login. You need to reload the page to see it.

**Comment by wopian** [comment]
Forgot I reverted to a fairly old version 😆 a few weeks ago. `Current User` label is always visible running latest build.
