### ISSUE TITLE
Installation Fails on Raspberry Pi

### ISSUE THREAD

**Issue by virpatel524** [jfurrow/flood#61]
Hey,

Starting flood seems to fail on the Pi with exit status 127. The program told me to notify you that: npm prune && npm install && ./node_modules/.bin/gulp dist && ./node_modules/.bin/nodemon ./server/bin/www

is failing. Ideas? I've tried to update most dependencies but still not sure.

**Comment by jfurrow** [comment]
What OS are you running? There should be additional details above that message (or in `npm-debug.log`), could you paste those here?

**Comment by ansarhun** [comment]
Had a similar problem, when updating the dependencies (sass) make, g++ is required.
After installing these packages, the npm install worked.

**Comment by jfurrow** [comment]
I'm going to close this, seems like it's not an issue.
