### ISSUE TITLE
Feature Request: Disk space usage/free display

### ISSUE THREAD

**Issue by kajer** [jfurrow/flood#617]
## Expected Behavior
display free diskspace somewhere on the client display

## Current Behavior
no filesystem info provided 

## Possible Solution
maybe combined with the bandwidth graph, display available disk space for a directory of choice on the server side filesystem.

## Steps to Reproduce (for bugs)
n/a

## Context
This is a feature request.  As I use a headless system to download, I'd like to know about the disk usage of the VM without needing to check manually.  It should be in the UI somewhere.

## Your Environment
ubuntu 16.04.latest server x64

## Note
n/a

**Comment by noraj1337** [comment]
Duplicate https://github.com/jfurrow/flood/issues/308

 Please look for existing issues before opening a new one.
