### ISSUE TITLE
Progress bars are not displayed properly on Firefox

### ISSUE THREAD

**Issue by afeblot** [jfurrow/flood#620]
Progress bars are not displayed properly

## Expected Behavior
Current behavior with Safari
![flood_safari](https://user-images.githubusercontent.com/12073123/36067864-adc01dc8-0ec7-11e8-8709-5b7e4f528af9.png)

## Faulty Behavior
Current behavior with Firefox 
![flood_firefox](https://user-images.githubusercontent.com/12073123/36067870-dd48ee62-0ec7-11e8-8ac1-2d6899728e2b.png)

## Your Environment
* Version used: Stable 1.0.0, I think: I'm using [a docker image](https://hub.docker.com/r/binhex/arch-rtorrentvpn/builds/bjzps3lsx8krh4bcepdlr7f/) stating "Latest GitHub commit to master branch for Flood". However, looking at the Dockerfile, it uses a github download script which seems to just download the latest release, so 1.0.0. Also, the flood CHANGELOG.md in the image only has the 1.0.0 section, no Unreleased section.
* Environment name and version: Firefox 58.0.1
* Operating System and version: Mac OS High Sierra 10.13.3

**Comment by noraj1337** [comment]
@afeblot Please provide this part of the template:

```markdown
## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version:
```

I'm also using Firefox 58.0.1 on Manjaro and have the normal behavior so it's maybe not about  Firefox but macOS or the version of Flood you use. Please follow the template to help us to find the bug.

**Comment by afeblot** [comment]
Description updated, version seems to be 1.0.0 and not the latest master. Sorry for that.

**Comment by bbashy** [comment]
Functioning fine on macOS 10.13.6 and Firefox 61.0.2 (64-bit)

**Comment by afeblot** [comment]
> Functioning fine on macOS 10.13.6 and Firefox 61.0.2

Indeed, I confirm.
