### ISSUE TITLE
argon2 dep missing?

### ISSUE THREAD

**Issue by joydashy** [jfurrow/flood#623]
I tried to update Flood today, ran into two issues:

- npm install failed on lacking g++ --> resolved manually
- starting Flood after build failed, lacking argon2 --> resolved by npm install argon2

I suppose the argon2 bit could be a missing dep.

**Comment by wopian** [comment]
The g++ failure was argon2's installation. `npm install argon2` without resolving it would've had the same issue.

**Comment by noraj1337** [comment]
> npm install failed on lacking g++ --> resolved manually

the README:
![](https://i.imgur.com/hc7a9ZZ.png)

so if you follow the step you have no dependency problems.


> starting Flood after build failed, lacking argon2 --> resolved by npm install argon2

read

https://github.com/jfurrow/flood/blob/2cb40c4e3cf780864808c47fda20bc3855311188/package.json#L19

and you'll that argon2 dep is here.

And finally, please respect the issue template.

**Comment by joydashy** [comment]
Ok, was just noting that if you follow the "updating" instructions "blindly" (I suppose), you run into issues.

And the template seemed a bit overkill for this, sorry.
