### ISSUE TITLE
Url Path to XMLRPC in Sonarr/Radarr?

### ISSUE THREAD

**Issue by casperstorm** [jfurrow/flood#626]
First of all thanks for flood. Its amazing.
I've recently changed to rTorrent + flood and are working on connecting it with Sonarr/Radarr, however stuck at `Url Path`:

> Path to the XMLRPC endpoint see http(s)://[host]:[port]/[urlPath]. When using ruTorrent this usually is RPC2 or (path to ruTorrent)/plugings/rpc/rpc.php

I am running rTorrent + flood on a Debian 9 container by following this [guide](https://freedif.org/flood-modern-web-ui-for-rtorrent/).

**Comment by SanPilot** [comment]
If you aren't using a Unix socket, this is easy: check the scgi url in `config.js`. The port and address are listed there. If you never changed this file, the default is `localhost:3000`. If you're using a socket, it's a little more involved. In my setup, I use Nginx to proxy requests to the socket.

**Comment by noraj1337** [comment]
@casperstorm Please try to respect the issue template as much as you can.

**Comment by noraj1337** [comment]
I think what you are looking for is this config https://github.com/jfurrow/flood/issues/525#issuecomment-357394387 and explanation is here https://github.com/jfurrow/flood/issues/525#issuecomment-357469803

**Comment by casperstorm** [comment]
> If you aren't using a Unix socket, this is easy: check the scgi url in config.js

I am not (afaik?)
I have the following in my `config.js`

```
const CONFIG = {
  baseURI: '/',
  dbCleanInterval: 1000 * 60 * 60,
  dbPath: './server/db/',
  floodServerHost: '0.0.0.0',
  floodServerPort: 3000,
  floodServerProxy: 'http://192.168.1.100',
  maxHistoryStates: 30,
  pollInterval: 1000 * 5,
  secret: 'flood',
  scgi: {
    host: 'localhost',
    port: 5000,
    socket: false,
    socketPath: '/tmp/rtorrent.sock'
  },
  ssl: false,
  sslKey: '/absolute/path/to/key/',
  sslCert: '/absolute/path/to/certificate/',
  torrentClientPollInterval: 1000 * 2
};

module.exports = CONFIG;
```

rTorrent + Flood is running on a container on 192.168.1.200.
Sonarr is running on a container on 192.168.1.202.
I've tried a few things, but not sure i understand what and where to find the information.

**Comment by Codehhh** [comment]
@casperstorm I had to use the black hole to dump torrents to the flood/rtorrent docker.

**Comment by noraj** [comment]
@bbashy is right, as for Transdroid, Sonarr/Radarr connect to the RPC endpoint of rTorrent, flood is just an UI.
