### ISSUE TITLE
SSL Enabled with BaseURI causes issues.

### ISSUE THREAD

**Issue by heihachi** [jfurrow/flood#642]
## Summary
Enabling BaseURI in config and setting up the proxy using apache2 while having SSL enabled doen't load the page. Checked the wiki and searched all the issues related to this and nothing has worked.

## Expected Behavior
Expected to be able to use the client as usual but just errors out.

## Current Behavior
page generates this error
```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /flood.

Reason: Error reading from remote server
```
another issue i have had is even with the baseuri set it goes from http://xxx/flood to http://xxx/login and never logs in.

## Steps to Reproduce (for bugs)
1. Setup Flood using a proxy and SSL
2. Setup Apache2 using a conf for flood to proxy to port 3000
3. Go to the page and see if it works.

## Context
Prevents using flood with apache2 proxy with SSL

## Your Environment
* Version used:
  + Version (stable release) Flood v1.0.0
  + Commit ID (development release) commit 293aa11d512ee089f1d559b24e6f8bbe707cfb8d
Ubuntu 16.0.4 with node v8.10.0

config.js
```
const CONFIG = {
  baseURI: '/flood',
  dbCleanInterval: 1000 * 60 * 60,
  dbPath: './server/db/',
  floodServerHost: '0.0.0.0',
  floodServerPort: 3000,
  floodServerProxy: 'https://127.0.0.1,
  maxHistoryStates: 30,
  pollInterval: 1000 * 5,
  torrentClientPollInterval: 1000 * 2,
  secret: 'yuMmyTac0s',
  scgi: {
    host: '127.0.0.1',
    port: 51102,
    socket: false,
    socketPath: '/tmp/rtorrent.sock'
  },
  ssl: true,
  sslKey: 'snipped.key',
  sslCert: 'snipped.cer'
};
module.exports = CONFIG;
```
flood.conf
```
<Location /flood>
ProxyPass https://127.0.0.1:3000
ProxyPassReverse https://127.0.0.1:3000
</Location>
```

**Comment by noraj** [comment]
Reverse proxy is working for everyone so this sound like a problem in your config.
In think this issue is personal support.

This aside, did you check that https://127.0.0.1:3000 was answering locally ?

When you'll find the answer for your problem, it will be interesting to complete this wiki page with a valid conf for apache.
