### ISSUE TITLE
built main.js contains config.js with secret exposed

### ISSUE THREAD

**Issue by zawapete** [jfurrow/flood#643]
## Summary
`npm run build` minifies the frontend code in a main.js file

## Expected Behavior
Since config.js should only be related to backend code we should remove from minifying it with `npm run build`

## Current Behavior
this file contains also config.js content, with sensible data exposed to the public
ie:
```
var n = {
        baseURI: "/",
        dbCleanInterval: 36e5,
        dbPath: "./server/db/",
        floodServerHost: "127.0.0.1",
        floodServerPort: 3e3,
        floodServerProxy: "http://127.0.0.1",
        maxHistoryStates: 30,
        pollInterval: 5e3,
        secret: "flood",
        sslKey: "/absolute/path/to/key/",
        sslCert: "/absolute/path/to/certificate/",
        torrentClientPollInterval: 2e3
```

also there's a source map `//# sourceMappingURL=main.788ca06b.js.map` that most of the browers' developer tools expose the existence of the config.js file

**Comment by SanPilot** [comment]
This is a slightly tough one because `config.js` is needed by both client and server. We may need to separate the file out into two (perhaps during the build process). Whatever the case, this needs to be addressed immediately because it completely compromises the authentication system.

**Comment by jfurrow** [comment]
@zawapete @SanPilot This has been fixed since December 30 (https://github.com/jfurrow/flood/pull/603). I just double-checked, cannot reproduce on `master`.
