### ISSUE TITLE
baseURI applies to links but server returns base HTML to everything

### ISSUE THREAD

**Issue by ripdog** [jfurrow/flood#646]
## Summary
With a baseURI set and browser visiting localhost:3000/flood, the screen is pure white. This is because the url pointing at the js bundle returns the base html again. The server only actually serves the js bundle on the original url, without /flood.

## Expected Behavior
`curl localhost:3000/flood/static/js/main.3af0fe36.js` should return the js bundle.

## Current Behavior
`curl localhost:3000/flood/static/js/main.3af0fe36.js` returns the base html.
`curl localhost:3000/static/js/main.3af0fe36.js` returns the js bundle.

## Steps to Reproduce (for bugs)

1. Edit config.js with `baseURI = '/flood'`
2. `npm build`
3. `npm start`
4. Visit localhost:3000 in browser, get blank screen

(The same thing happens when I try the dev server)

## Your Environment

* Version used: 293aa11d512ee089f1d559b24e6f8bbe707cfb8d
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version (e.g. Chrome 39, node.js 5.4): Browser is irrelevant. Node 9.9.0, npm 5.8.0.
* Operating System and version: Arch linux.

Log output from server:

```
% npm start

> flood@1.0.0 start /home/rtorrent/flood
> node server/bin/start.js

Flood server starting on http://127.0.0.1:3000.

GET /flood 200 64.100 ms - 567
GET /flood/static/css/main.5766965a.css 200 2.227 ms - 567
GET /flood/static/js/main.3af0fe36.js 200 0.950 ms - 567
```

Obviously the link generation is respecting the baseURI directive, but the server is ignoring it.

Here's my config.js, secret removed:

```
% cat config.js
// This is the configuration file for Flood, a React-based frontend for the
// rtorrent BitTorrent client.
// Copy this file to ./config.js and make changes below.
// config.js must exist before running `npm run build`.

const CONFIG = {
  // The URL that Flood will be served from. For example, if you intend to
  // serve from http://example.com/flood, set this to '/flood'.
  baseURI: '/flood',
  // Flood uses a local nedb database to keep track of users, torrents,
  // and activity. The database is regularly purged to remove outdated data.
  // This value dictates how old data is, in milliseconds, before being purged.
  dbCleanInterval: 1000 * 60 * 60,
  // Where to store the local nedb database.
  dbPath: './server/db/',
  // The host that Flood should listen for web connections on.
  // If you want to connect to Flood from hosts other that the one it is running
  // on, you should change this value.
  // To listen on all interfaces, change to `floodServerHost: '0.0.0.0'`
  floodServerHost: '127.0.0.1',
  // The port that Flood should listen for web connections on.
  floodServerPort: 3000,
  // Used for development. See the "Local Development" section of README.md
  // for detail.
  floodServerProxy: 'http://127.0.0.1',
  // Flood keeps a history of torrent download and upload speeds.
  // This value dictates the number of individual records per period to keep.
  maxHistoryStates: 30,
  // How often (in milliseconds) Flood will check for updates to torrent detail.
  pollInterval: 1000 * 5,
  // How often (in milliseconds) Flood will check rtorrent for status updates.
  torrentClientPollInterval: 1000 * 2,
  // A unique secret for signing messages with JWT (see https://jwt.io). Change
  // this to something unique and hard to guess.
  secret: '',
  // Configuration details for your backend rtorrent interface.
  // These are defaults for most installs; check your .rtorrent.rc for changes.
  scgi: {
    host: 'localhost',
    port: 5000,
    socket: true,
    socketPath: '/home/rtorrent/rpc.socket'
  },
  // Configuration for SSL, if using SSL with the Flood service directly.
  ssl: false,
  sslKey: '/absolute/path/to/key/',
  sslCert: '/absolute/path/to/certificate/'
};
// Do not remove the below line.
module.exports = CONFIG;
```

**Comment by jfurrow** [comment]
@ripdog On its own, `baseURI` isn't useful — it is meant to be used in conjunction with a web server that routes traffic to Flood accordingly. `baseURI` just tells Flood where to send the requests. [Here](https://github.com/jfurrow/flood/wiki/Using-Flood-behind-a-reverse-proxy) is an overly-simplified nginx config to do this.

**Comment by ripdog** [comment]
Oh sorry, I didn't mention that this was all running through caddy. I get
the exact same result running it through a caddy reverse proxy. Caddy had
been instructed to send all the usual reverse proxy headers with the
transparent directive.

I thought that mentioning the web server (especially a more niche one)
might lead to someone saying the web server was at fault or misconfigured.
I am using a known good and very simple caddy configuration. I can post
that tomorrow if you want it.

But yeah, I get the exact same issue with or without a reverse proxy. Links
are generated with baseURI, but the internal web server is unaware.

**Comment by ripdog** [comment]
Sorry for the ping, but I don't think closed issues generate notifications. @jfurrow

**Comment by jfurrow** [comment]
I'll reopen until I can verify that it works for me (in nginx — sorry, but I don't have the time to test all web servers).

**Comment by ripdog** [comment]
Of course. The fact that both curl and caddy recieve the same output makes
me fairly confident that the internal server is the issue. Thanks.

**Comment by deansheather** [comment]
Can confirm, using nginx here. The internal flood web server is serving the HTML on the routes (using `baseURI`) that it's referencing in the script/style tags, and is returning the proper CSS/JS bundles on the `/static`.

**Comment by ouchadam** [comment]
a temporary work around is to move/copy the `server/assets/*` into a directory called your `baseUri` `server/assets/{baseUri}/*` , otherwise the router defaults to returning the `index.html` for everything.

**Comment by xataz** [comment]
Hi,

Same error with node 10 on alpine 3.7.

**Comment by jfurrow** [comment]
I've just verified, this is working as expected. The best proof I can offer is this screenshot:
<img width="1665" alt="screen shot 2018-05-08 at 10 28 49 pm" src="https://user-images.githubusercontent.com/1134755/39797117-4073d110-530f-11e8-85a9-1ecb3267c280.png">

Some troubleshooting tips:
1. Make sure your nginx config is set up to forward all requests to the server, as [documented in the Wiki](https://github.com/jfurrow/flood/wiki/Using-Flood-behind-a-reverse-proxy).
2. Make sure you rebuild static assets after configuring `baseURI` in `config.js` by running `npm run build`

**Comment by ripdog** [comment]
You have to rebuild assets? Is that documented? I'm not sure I did that.

I just ended up using a new subdomain because of this. If this issue is tripping up this many people, some explicit instructions in the readme would be nice.

**Comment by noraj** [comment]
@ripdog `npm run build` is written in **Compiling assets and starting the server** (for the first install) and in **Updating** so it's in the README.
