### ISSUE TITLE
Start Flood alongside rTorrent automatically

### ISSUE THREAD

**Issue by Gladuin** [jfurrow/flood#653]
How can I start Flood alongside rTorrent? Like if I start rTorrent it starts Flood and when it shuts down Flood also shuts down.
This would be nice to have so I dont have to cd into the Flood dir and stuff like that.

**Comment by SanPilot** [comment]
Use systemd (if you're on Linux.)

Use the `PartOf=` directive so Flood and rtorrent can start and stop together.

**Comment by noraj** [comment]
Also see https://github.com/jfurrow/flood/wiki/Install-flood-with-a-service-account

**Comment by bbashy** [comment]
I know this is old but seems kinda solved. You also wouldn't need to restart Flood every time since it's just a UI?

**Comment by noraj** [comment]
Yeah it was just a question. Flood is just a web UI. The easiest is to enable rTorrent + Flood at startup by using systemd unit files.
