### ISSUE TITLE
white page first installation

### ISSUE THREAD

**Issue by boistordu** [jfurrow/flood#670]
## Summary

I'm getting a white page on first launch
## Expected Behavior

Should get the page where it asks me the first login
## Current Behavior

getting a white page 
## BUG Report from dev tools
it seems that teh different developper tools are complaining about basics error in the first JS files so main JS main.1977e1fb.js:1 and manifest.json
In main.js there is `Uncaught SyntaxError: Unexpected token <`  but I can't manage to find it.

[flood.zip](https://github.com/jfurrow/flood/files/2019947/flood.zip)
and we have for manifest.js manifest.json:1 Manifest: Line: 1, column: 1, Unexpected token.

## Your Environment

* Version used:
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version:
commit ecbf4c5a28dcde9e7a75edbe3795e50918293123 (HEAD -> master, origin/master
archlinux for the server 
windows 10, chrome 66, firefox 60.0.1
tried with edge, google chrome and firefox with the adblocking disable

**Comment by blacksponge** [comment]
I have just ran into the same problem while having set a baseURI to /flood and no rewriting the url from /flood/foo/bar to /foo/bar before proxying the request to flood. So it ends up with all request being prefixed by /flood and returning the index page.

**Comment by noraj** [comment]
@boistordu You may take a look at what is logged in your console (after the `npm start`).
Did you also take a look at https://github.com/jfurrow/flood/wiki/Troubleshooting like it is asked in the issue template? And the wiki for https://github.com/jfurrow/flood/wiki/Using-Flood-behind-a-reverse-proxy?

As @blacksponge said, it looks more like a configuration problem from your side than a flood bug. I'm sorry we have no time for personal support. Some people may have time and help you on the dicord #Troubleshouting.

**Comment by noraj** [comment]
Also if you look at #284 and #427 @jfurrow gave some example of workinf reverse proxy rules. Just by searching for `white` in the issue research form.

I'll update the wiki accordingly.

**Comment by boistordu** [comment]
So I’m not talking about reverse proxying or anything.
There is no error in the console, it just stops feeding data after a few lines that’s all. And I didn’t even configure nginx at this point. I only configure flood to be able to listen to all interfaces and respond to all interface. So there is no transaction between a web server and flood at this point, I just want to have the flood interface available from flood itself.

So it’s actually a white page from flood itself.
If I understand correctly the documentation, normally flood act as a web server already. If you need another web server is to do some reverse proxy. So I should be able to see something from flood itself.

And actually I can see some things. Like the icon is loaded, the title of the page is loading. But nothing more. And since JavaScript is client language and not a server language, I don’t see how a second web server can make it work better, flood have just to feed the client with the js and that’s what it does. But apparently from the dev console from the different browser, it seems to be an error in the compiled JavaScript.

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by boistordu** [comment]
So @blacksponge, sorry but it’s not a good thread to speak about the base uri or anything related to the reverse proxy since I don’t have any reverse proxy configured just yet.

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by blacksponge** [comment]
@boistordu What I also was trying to say is that the I got this error while the browser was trying to parse html as javascript. Did you check that the response from the server is actually what it is supposed to be (network tab in the dev tools for instance) ?

**Comment by boistordu** [comment]
Wait wait. so you got the same error from flood itself when you configure it without any proxy or other web server ? So when you configured your config.js with 0.0.0.0?

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________

**Comment by noraj** [comment]
@boistordu If you want someone to help you please provide your `config.js` and what do you try to load in your browser. Also explain your architecture: as I understand you installed flood and rtorrent on a remote server and try to access it from your personal computer, etc ...

Also javascript is no only a client language, in fact Flood use nodejs that is server side javascript that act like php for example so you are totally wrong on this point. Flood is not 100% client side a you seem to believe it.
A lot of languages offer an embed web server but it is usually only used for dev and test purpose because those web server are not made for production environment and are highly insecure that's why everybody use a reverse proxy in this case. So there is a real usefulness to use a reverse proxy, at least for security purpose.

**Comment by noraj** [comment]
As I said earlier it is not a bug but a misconfiguration from you so please join the discord (https://discord.gg/Z7yR5Uf) and ask in the #troubleshouting. Github issues of open source project are not for personal support.
