### ISSUE TITLE
Give Flood more visibility by adding repository tags

### ISSUE THREAD

**Issue by noraj** [jfurrow/flood#673]
## Summary

Add some tags to the project.

For example:

- rtorrent
- react
- nodejs
- webui

## Expected Behavior

Project has some tags that describe it.

## Current Behavior

Project has no tags.

## Screenshot

Example:

![](https://i.imgur.com/LVGJ3Yr.jpg)

## Context

Add better visibility to the project.

**Comment by noraj** [comment]
@jfurrow this take like 5 seconds to do

**Comment by jfurrow** [comment]
@noraj Thanks for the helpful comment

**Comment by noraj** [comment]
@jfurrow As you seem very very very busy since several months maybe you can give me more permission so I can do this kind of changes mysellf.
And also I may create a static website to promote flood.
I think we must put a banner on top of the readme to say we look for dev and contributors because you're nearly the only person to commit code changes and you're not active those days.
What do you think ?

**Comment by zawapete** [comment]
@noraj as the author of the multi rtorrent instance branch I would like to say that the problem with flood it to understand if @jfurrow has the willing or not to let the project be really open source. I waited almost 9 months to see my feature merged to master: it was totally rewritten and I don't even appear between the project's contributors.
I really wanted to push more flood development, I advocated for it on different places.
In my opinion the project still miss some basic features to be a viable replacement for rutorrent, but if I had to wait 9 months for my own branch (and who knows how long I still have to wait for the rss' improvement branch) I'm the first one to not use flood "in production"
@noraj, you already created the organization to migrate the project to few days ago, but nothing was done on @jfurrow side, so I wonder what he wants to do with the project

**Comment by noraj** [comment]
I think @jfurrow wants to keep the control on the project, that shouldn't be a problem if he was more active like before. Members like me can merge and all but I'm not a dev and know nothing about JS so I prefer no to touch the code. I think we need more active dev on the project, not only the author that seems to have no time today.

**Comment by zawapete** [comment]
@noraj I don't have anything against @jfurrow being the owner of the project: he created it and he has total right to be. but one thing is being the owner, and another it to want to keep total control of the codebase: this doesn't suite an open source project, and also it's not very appealing for other developers that would like to join and contribute to the project but end up not being recognized as contributors, like it happened with me

**Comment by jfurrow** [comment]
As I wrote in https://github.com/jfurrow/flood/issues/672, the quality of contributions has been very low, so I don't think more contributors is the answer.

**Comment by noraj** [comment]
Ok for closing as tags have been added.
