### ISSUE TITLE
Stuck on "Authentication Status" after restarting Flood

### ISSUE THREAD

**Issue by rthompsonj** [jfurrow/flood#674]
## Summary
If you restart flood via terminating the process and restarting it, then refresh your browser that is currently on the `/overview` page you get stuck on "Authentication Status".  It is a minor annoyance as you can just navigate to the page without the `/overview` and it works fine.

## Expected Behavior
It should either reauthenticate you or ask you to reauth.

## Current Behavior
You get stuck on the "/overview" page.  I have verified this to happen in Chrome and Firefox but _not_ Safari.
![screen shot 2018-05-26 at 11 35 02 am](https://user-images.githubusercontent.com/543053/40578418-3d45fcf2-60d9-11e8-975d-91f8eed9ebe3.png)

## Possible Solution
Not sure how to fix the minor annoyance but wanted to make sure you were aware.

## Steps to Reproduce (for bugs)
1. start flood
2. open a browser to the `/overview` page
3. stop flood
4. start flood
5. refresh the browser and navigate directly to the `/overview` page

## Your Environment
* Version used:
  + v1.0.0
  + 1493f8f9cbf6d6c94f1083a53aaba82d95d508af
* node.js 8.10.0, Chrome 66.0.3359.181, Firefox 57.0
* MacOS 10.12.5

**Comment by noraj** [comment]
Did you check other issues?

For example by searching for `Authentication Status` : https://github.com/jfurrow/flood/issues?q=is%3Aissue+Authentication+Status+is%3Aclosed

See [Flood page freeze on main page load](https://github.com/jfurrow/flood/issues/489) and tell us if that resolve your problem.

**Comment by rthompsonj** [comment]
I did search for authentication but didn't see anything.  Sorry about that!
