### ISSUE TITLE
Flood systemd service "timeout" yet runs as a zombie

### ISSUE THREAD

**Issue by piperun** [jfurrow/flood#678]
## Summary

Essentially after having installed flood for the user 'node', when I try and start the flood server via:
`npm --prefix=/home/node/flood start`
It works as intended, however, if I try the same via:
`service flood start`
I get a timeout error from systemd:
```
-- Unit flood.service has begun starting up.
Jun 27 04:45:37 rumia flood_start[10670]: > flood@1.0.0 start /home/node/flood
Jun 27 04:45:37 rumia flood_start[10670]: > node server/bin/start.js
Jun 27 04:45:39 rumia flood_start[10670]: Flood server starting on https://0.0.0.0:3000.
Jun 27 04:47:07 rumia systemd[1]: flood.service: Start operation timed out. Terminating.
Jun 27 04:47:07 rumia systemd[1]: flood.service: Failed with result 'timeout'.
Jun 27 04:47:07 rumia systemd[1]: Failed to start flood.
-- Subject: Unit flood.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit flood.service has failed.
--
-- The result is RESULT.

```
And flood continues to run in the background, while systemd thinks it has failed.
## Expected Behavior
Given the .service example in the wiki, where there isn't  a usage of `tmux `or `screen`, systemd should simply return flood's status as runing when flood is running.

## Current Behavior
flood causes systemd to "terminate" on the "timeout" result being the failure.

## Possible Solution
The most likely solution I can think of is to use tmux or screen to put flood into a separate environment, 
which is the case with rtorrent.

Or it would be to add an option for flood to have it spawn in the background / forking it.

## Steps to Reproduce (for bugs)
```
[Unit]
Description=flood
After=network.target

[Service]
Type=forking
#KillMode=process
User=node
#PermissionsStartOnly=true
#LimitNOFILE=4096
#IgnoreSIGPIPE=false

# Pre-run
#ExecStartPre=/sbin/sysctl -w net.ipv4.ip_forward=1
#ExecStartPre=/sbin/iptables -t nat -A PREROUTING -i enp1s0 -p tcp --dport 80 -j REDIRECT --to-port 3000

# Run

ExecStart=/home/node/.scripts/flood_start
ExecStop=/home/node/.scripts/flood_halt
WorkingDirectory=/home/node/flood


[Install]
WantedBy=multi-user.target
```
the scripts:
flood_halt:
```
#!/usr/bin/env bash

#
# Usage: ./flood-update.sh
#


NPMCMD=$(npm --prefix=/home/node/flood/)

. /home/node/.nvm/nvm.sh
$NPMCMD stop
```
flood_start:
```
#!/usr/bin/env bash

#
# Usage: ./flood-update.sh
#

NPMCMD=$(echo npm --prefix=/home/node/flood)

. /home/node/.nvm/nvm.sh
$NPMCMD start


```

## Context
I'm trying to make the flood start on startup and have iptables rebind any connection to 80 from 3000

## Your Environment

* Version used:
  + Version v1.0.0
  + Commit ID: 1493f8f9cbf6d6c94f1083a53aaba82d95d508af
* Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome 67, nodejs 10.5.0 via nvm
* Operating System and version: Linux Ubuntu 18.04 LTS

**Comment by noraj** [comment]
that's a very weird configuration. Why running flodo as node? Why rebinding the port with iptable and not changing it directly in the config file?

**Comment by piperun** [comment]
It reroutes port 80 to node's port, since you can't run node on port 80 or 443 without being root.
But iptable line is commented out and deprecated.

I run flood as node for both user separation and for a tad bit more security.

**Comment by noraj** [comment]
@piperun Yeah of course but my question was more why you run flood as node and not as flood user? (for even better separation and security, something similar to https://github.com/jfurrow/flood/wiki/Install-flood-with-a-service-account)

**Comment by piperun** [comment]
Two main reasons:
nvm and the fact that I don't use any other node program.

**Comment by noraj** [comment]
@piperun it is may be hard to hear but here it is: it seems there is not a flood bug, the problem must come from your custom install method and your custom systemd service script. This is out of the flood scope and here there are only volunteers giving a few of their free time to get this project live so we have no time for personal support I'm sorry.

To get better chance to be helped try the discord server [![Discord server badge](https://img.shields.io/discord/418267176873623553.svg?style=flat-square)](https://discord.gg/Z7yR5Uf) in the `#troubleshooting` channel.

**Comment by noraj** [comment]
PS : also for your general culture, *service* (when you use `service flood start`) is deprecated on all systemd distro (including ubuntu), use `systemctl start flood` instead.

**Comment by piperun** [comment]
Sorry but no, technically the fault is at systemd, but the service file I have is identical in how it functions to the one at the wiki, the same issue would popup if I only used npm flood start.
Because the issue is that flood doesn't run as a forked process / daemon, thus systemd will think the process has hanged while in reality it hasn't, this exact same behavior is expected with rtorrent since both of these applications run in the foreground.


And thus the fix in flood's case is either to make flood capable to start in the background or to simply provide a service file that includes tmux/screen.

**Comment by noraj** [comment]
@piperun please follow https://github.com/jfurrow/flood/wiki/Install-flood-with-a-service-account, of course you can use tmux but you can also use a flood account only for flood so that is not a problem if it is a catching process. Maybe the node user have some particular rights and permissions. Plus there must be some tweaks to do with your PATH as you use nvm.

**Comment by noraj** [comment]
> Sorry but no, technically the fault is at systemd, but the service file I have is identical in how it functions to the one at the wiki, the same issue would popup if I only used npm flood start.

Actually no, it is not similar, you are using `Type=forking` and custom start/stop scripts.
