### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by geops22** [jfurrow/flood#682]
Please provide a dark mode for the right pane. The bright white is eye-gouging.

**Comment by Vustom** [comment]
![Dark Mode](https://i.imgur.com/ezuZggq.png)
![Dark Mode](https://imgur.com/2rLQhlv.png)
![Dark Mode](https://imgur.com/c8lyVM6.png)
![Dark Mode](https://imgur.com/J2MQ6wV.png)
![Dark Mode](https://imgur.com/fR43w01.png)

Theme can be found on [gist.github.com](https://gist.github.com/Vustom/dcbdab73263710e60b54d1d11053a252). To enable it, copy contents to something like Stylus for Firefox/Chrome. Credits to [@sek0n](https://github.com/jfurrow/flood/issues/444) for the color palette.

Hope this helps!

**Comment by joker999** [comment]
Same, I made for myself but you can use my style (not CSS) its userscript - not perfect 
https://github.com/joker999/rtorrent-dark-flood

**Comment by geops22** [comment]
Thanks! Still, it would be better to have it integrated in the website with a simple dark/light toggle.

**Comment by joker999** [comment]
![](https://i.imgur.com/B9tGE6U.jpg)

https://github.com/joker999/rtorrent-dark-flood

**Comment by noraj** [comment]
Waiting for this to be integrated in flood can you push your themes on https://userstyles.org/ please ?

**Comment by noraj** [comment]
I'm closing this issue because it is a duplicate of https://github.com/jfurrow/flood/issues/444, please put your ideas there.

@geops22 Please search in existing issues before opening one and fill the template.
