### ISSUE TITLE
Help needed - Working on automatically adding RSS filters from watchlist at themoviedb.org

### ISSUE THREAD

**Issue by htilly** [jfurrow/flood#687]
Hi! 
First of, awesome GUI!

I just got a working bash script that will automatically add RSS filter to Flood based on my watchlist over at https://www.themoviedb.org/.
Quite nice. No more manual adding of RSS rules and regexp.. just keep you watchlist updated and download will happen =)

However, I have two questions.

1: Last field "_id". Is that simply a unique generated id of 16 letters? I.e. as for now Im just generating a random value.. Seems to work but want to verify.
"_id":"0L00p886fylIUfWF"

2: When manually (or thru the script) editing the file feeds.db it won't show up in the GUI unless I restart Flood. Is there any way of triggering this without restarting the app?

Thanks in advance!

If anyone is interested in the script or solution, feel free to reach out!

**Comment by noraj** [comment]
Hi @htilly ,
maybe try on the discord server https://discord.gg/Z7yR5Uf to get a quicker answer.

**Comment by htilly** [comment]
Thanks!

**Comment by htilly** [comment]
Closing the case:

Answers below:
1:
bashy:
'unique yup. It's how flood deletes the item etc'

2:
jfurrow:
yeah the db is all held in memory
so I'm not sure how to get the database to pick up external changes to its files — check out their repo https://github.com/louischatriot/nedb
