### ISSUE TITLE
"Cannot connect to rTorrent" loop via TCP on latest master

### ISSUE THREAD

**Issue by etbusch** [jfurrow/flood#708]
## Summary

The "Cannot connect to rTorrent" dialog pops up on app load and successfully tests the connection, and then proceeds to appear again when save is pressed.

## Expected Behavior

The app should take the xmlrpc server information, save it, and continue loading the app.

## Current Behavior

The "Cannot connect to rTorrent" dialog pops up and prompts me to enter in the ip and port the rtorrent xmlrpc server is listening on

I enter in the correct info and click "Test", and a checkmark appears.

I click submit, the dialog disappears momentarily, but then reappears with the information populated in the form.

This was working before I updated, and ruTorrent is currently working fine with the same rtorrent server. I reinstalled flood from scratch as well (with a fresh config.js) with the same result.

## Possible Solution

Fix the bug, and perhaps be a little less strict on issue templates ;)

## Steps to Reproduce (for bugs)

1. install flood
2. use a TCP connection to the rtorrrent xmlrpc server
3. attempt to use the app
4. 

## Context

This prevents the use of flood entirely on my setup

## Your Environment

* Version used: e21ab29c8ed10a600ca316fb7e8a88006c5ca512
* Environment name and version (e.g. Chrome 39, node.js 5.4): nodeJS 8.9.2
* Operating System and version: Alpine Linux 3.7

**Comment by boistordu** [comment]
Same issue here under archlinux up to date version. 
same version of rep

**Comment by notDavid** [comment]
@etbusch did you get this to work? i'm having the same issue...

**Comment by Sundava** [comment]
Same here, whenever I click "save settings", I can see an error 500 in the network tab, with the message : 
"Users.patchUser is not a function"

**Comment by harkor** [comment]
The solution of Sundava didn't work for me. Same issue.

**Comment by etbusch** [comment]
This was a duplicate of #706 and was resolved for me on a recent commit.

**Comment by okeehou** [comment]
I reinstalled flood from the scratch just few minutes ago and get the same issue "Cannot connect to rTorrent". Any idea?
