### ISSUE TITLE
Download a file from flood error 500

### ISSUE THREAD

**Issue by lokoum** [jfurrow/flood#714]
## Note

- [x] You may try to follow the update procedure described in the README and try again before opening this issue.
- [x] Before asking for something, please check the [F.A.Q.](https://github.com/jfurrow/flood/wiki/F.A.Q.).
- [x] Before opening a bug issue, please check the [Troubleshooting](https://github.com/jfurrow/flood/wiki/Troubleshooting) wiki section.
- [x] If you want to contribute to the project please review the [contributing guidelines](https://github.com/jfurrow/flood/blob/master/.github/CONTRIBUTING.md).
- [x] Keep in mind that Flood is a [FLOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software#FLOSS) (Free, Libre and Open Source Software), so please try to provide a PR when opening a bug issue. Without contributions the project can't live and with your help fix and request will come faster.
- [x] The project is accepting issues (bugs report), feature or enhancement requests, discussions and questions but **not personal support**.

## Summary
Tried multiple installation on different OS (Arch, BSD, Debian), tried with and without Docker
I got error 500 when downloading any file from flood. (direct download from flood to my PC)

## Expected Behavior
The download should start correclty

## Current Behavior
Here is the stack trace I got from the logs I added:
```
GET /favicon.ico 304 0.449 ms - -                                                    [28/462]
GET /login 200 2.608 ms - 543
GET /login 200 1.152 ms - 543
GET /static/css/main.1b57ea7f.css 304 0.454 ms - -
GET /static/js/main.be5d4735.js 304 0.444 ms - -
GET /auth/verify?1537472474060 200 4.212 ms - 41
GET /api/settings 304 3.540 ms - -
GET /api/client/settings 304 15.141 ms - -
GET /favicon.ico 304 0.521 ms - -
TypeError: Cannot read property 'methodCall' of undefined
    at ClientRequest.send (/home/lokoum/flood/server/models/ClientRequest.js:116:8)
    at Object.getTorrentDetails (/home/lokoum/flood/server/models/client.js:223:13)
    at Object.downloadFiles (/home/lokoum/flood/server/models/client.js:86:12)
    at router.get (/home/lokoum/flood/server/routes/api.js:22:10)
    at Layer.handle [as handle_request] (/home/lokoum/flood/node_modules/express/lib/router/l
ayer.js:95:5)
    at next (/home/lokoum/flood/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/lokoum/flood/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/lokoum/flood/node_modules/express/lib/router/l
ayer.js:95:5)
    at /home/lokoum/flood/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/lokoum/flood/node_modules/express/lib/router/index.js:3
35:12)
GET /api/download?hash=F67C13CBD11A00BCCD1EDDDF8C7B0E3DB80E6312 500 3.336 ms - 2
GET /api/activity-stream?historySnapshot=fiveMin 200 1.212 ms - -
```

## Steps to Reproduce (for bugs)
on a fresh Arch Linux install
1. $pacman -S base base-devel curl wget nodejs npm python2 python3
2. $git clone https://github.com/jfurrow/flood
3. `starting rtorrent`
4. $npm install #no errors
5. $npm run build #no errors
6. $npm start #everything start without errors
7. `Add a torrent from the flood interface #again everything is working, flood is adding the torrent to rtorrent`
8. `Download the torrent from flood with the 'Download' option (right click menu)`
9. `Then, I get the error 500`

## Your Environment

* Version used:
  master ( 8867c7d )
* Environment name and version 
  Firefox, Safari, Chrome on mac os
* Operating System and version:
 the flood and rtorrent instance are installed on ArchLinux (up to date)
node 10.10.0

**Comment by bbashy** [comment]
Confirmed as well.

**Comment by kallard1** [comment]
Hi, i've the same problem and i can't download files from flood

`/api/download?hash=D0A58C325E9FBD5C05DB7DC205322C86B504D0E4 500 3.647 ms - 2`

**Comment by noraj** [comment]
Same I have HTTP error 500 on every download. Using node v10.10.0 and npm 6.4.1.

**Comment by noraj** [comment]
@stephdewit was my troubleshooting useful ?

**Comment by stephdewit** [comment]
> @stephdewit was my troubleshooting useful ?

Hello @noraj.

Yes it was. The bug wasn't actually related to an URL problem, but the search you sent nevertheless pinpointed the file I had to change.
