### ISSUE TITLE
Unable to build and start flood 

### ISSUE THREAD

**Issue by t0maz** [jfurrow/flood#731]
## Note

- [x] You may try to follow the update procedure described in the README and try again before opening this issue.
- [x] Before asking for something, please check the [F.A.Q.](https://github.com/jfurrow/flood/wiki/F.A.Q.).
- [x] Before opening a bug issue, please check the [Troubleshooting](https://github.com/jfurrow/flood/wiki/Troubleshooting) wiki section.
- [ ] If you want to contribute to the project please review the [contributing guidelines](https://github.com/jfurrow/flood/blob/master/.github/CONTRIBUTING.md).
- [ ] Keep in mind that Flood is a [FLOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software#FLOSS) (Free, Libre and Open Source Software), so please try to provide a PR when opening a bug issue. Without contributions the project can't live and with your help fix and request will come faster.
- [x] The project is accepting issues (bugs report), feature or enhancement requests, discussions and questions but **not personal support**.

## Summary

```
flood@owczarek /mnt/data/Pliki/samba_share/Download/rtorrent/flood $ **npm start**

> flood@1.0.0 start /mnt/data/Pliki/samba_share/Download/rtorrent/flood
> node server/bin/start.js

Failed to start Flood:
Trace: Static assets (index.html) are missing. Please check the 'Compiling assets and starting the server' section of README.md.
    at enforcePrerequisites.then.then.catch.error (/mnt/data/Pliki/samba_share/Download/rtorrent/flood/server/bin/start.js:12:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 start: `node server/bin/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/flood/.npm/_logs/2018-10-13T21_53_41_011Z-debug.log

flood@owczarek /mnt/data/Pliki/samba_share/Download/rtorrent/flood $ **npm install**
npm WARN flood@1.0.0 No repository field.
npm WARN flood@1.0.0 No license field.

updated 1 package and audited 34504 packages in 10.478s
found 8 moderate severity vulnerabilities
run npm audit fix to fix them, or npm audit for details

flood@owczarek /mnt/data/Pliki/samba_share/Download/rtorrent/flood $ **npm audit fix**
npm WARN flood@1.0.0 No repository field.
npm WARN flood@1.0.0 No license field.

updated 1 package in 8.143s
fixed 8 of 8 vulnerabilities in 34504 scanned packages

flood@owczarek /mnt/data/Pliki/samba_share/Download/rtorrent/flood $ **npm run build**

    flood@1.0.0 build /mnt/data/Pliki/samba_share/Download/rtorrent/flood
    node client/scripts/build.js

Creating an optimized production build...
Failed to compile.

Cannot read property 'compilation' of undefined

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 build: node client/scripts/build.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flood@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/flood/.npm/_logs/2018-10-13T21_16_51_957Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v10.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle flood@1.0.0prebuild: flood@1.0.0
6 info lifecycle flood@1.0.0build: flood@1.0.0
7 verbose lifecycle flood@1.0.0build: unsafe-perm in lifecycle true
8 verbose lifecycle flood@1.0.0build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/data/Pliki/samba_share/Download/rtorrent/flood/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle flood@1.0.0build: CWD: /mnt/data/Pliki/samba_share/Download/rtorrent/flood
**10 silly lifecycle flood@1.0.0build: Args: [ '-c', 'node client/scripts/build.js' ]
11 silly lifecycle flood@1.0.0build: Returned: code: 1 signal: null**
12 info lifecycle flood@1.0.0build: Failed to exec build script
13 verbose stack Error: flood@1.0.0 build: node client/scripts/build.js
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack at EventEmitter.emit (events.js:182:13)
13 verbose stack at ChildProcess. (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:182:13)
13 verbose stack at maybeClose (internal/child_process.js:962:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid flood@1.0.0
15 verbose cwd /mnt/data/Pliki/samba_share/Download/rtorrent/flood
16 verbose Linux 4.4.0-128-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.12.0
19 verbose npm v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error flood@1.0.0 build: node client/scripts/build.js
23 error Failed at the flood@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Please let me know if you need any more info.
Thanks

## Expected Behavior

should build and start without errors

## Current Behavior

fail to build and start

## Steps to Reproduce (for bugs)

1. npm start (fail as above)
2. npm install
3. npm run build (fail as above)
4.

## Your Environment

* Version used:
  + Version (stable release) `git --no-pager tag` v1.0.0
  + Commit ID (development release) `git --no-pager log -1` commit 0fd40f14f10831d05b69abf7d286ea81b511b024
* Environment name and version (e.g. Chrome 39, node.js 5.4):
```
2 info using npm@6.4.1
3 info using node@v10.12.0
```
* Operating System and version:
```
RELEASE=18
CODENAME=sarah
EDITION="Xfce 64-bit"
DESCRIPTION="Linux Mint 18 Sarah"
DESKTOP=Xfce
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_sarah_xfce_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_sarah_xfce.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 18 Xfce 64-bit
```

**Comment by t0maz** [comment]
It seems that it is #510 reproduced

**Comment by zawapete** [comment]
@t0maz I think the fist thing is to test with a supported version of node and npm:
    "node": ">=7.0.0",
    "npm": "~5.3.0"

**Comment by t0maz** [comment]
Thanks for your feedback.

2 info using npm@6.4.1
3 info using node@v10.12.0

Do you mean that I should try to downgrade node and npm then?
I've just upgrade them due to https://github.com/ranisalt/node-argon2/issues/147
I've runned following commands:
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
and not sure how may I perform a downgrade now?

when I try to install node 8:
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
$ sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**nodejs is already the newest version** (10.12.0-1nodesource1).

**Comment by zawapete** [comment]
@t0maz I read in your ticket: `node.js 5.4`

if you are already using minimum requirement or later is fine

**Comment by t0maz** [comment]
thanks @zawapete 

I've added environment info.
Please let me know guys if you need any more data or if I can help anyhow.
Many thanks

**Comment by noraj** [comment]
@t0maz I updated your post to have proper code blocks, please use markdown syntax or the buttons of the editor.

You ran the steps in the wrong order. It is not start, install, the build. This should be install, build, start.

Please follow the README **carefully**.

This is not a bug but just you not following the README, you are asking for personal support that we don't provide.

>  The project is accepting issues (bugs report), feature or enhancement requests, discussions and questions but **not personal support**.

If you want help you may ask on the discord.

**Comment by t0maz** [comment]
@noraj it fails to start because it failed to build

**Comment by noraj** [comment]
In your logs and steps to reproduce you used `npm start` before installing and building.

You may also missed some prerequisites. 

Anyway check the readme very carefully or ask for help on discord.
