### ISSUE TITLE
rtorrent 0.9.7

### ISSUE THREAD

**Issue by Hipoglos** [jfurrow/flood#735]
Type: Question
I have installed flood successfully but after login, it shows:

**Connection could not be verified.**

Ive specified the correct scgi port, but still no luck.

Is flood supporting 0.9.7?

Thanks!!

**Comment by noraj** [comment]
Hi @Hipoglos, yes flood is supporting this version of rtorrent. Check your rtorrent service is started  and working (check status). You also want to check your rtorrent config and check the flood readme carefully and the FAQ on the wiki.

If you encounter a bug with flood in the process, open a bug issue.
