### ISSUE TITLE
Faults on: geoip-country-only

### ISSUE THREAD

**Issue by geekism** [jfurrow/flood#737]
Git: 1.0.0
Commit id: a6771ee06373519a5fcff3d234b0d2332ac6a8f0
node version 8.12.0
npm version: 6.4.1
firefox+chrome current
Debian 9

During npm install. it faults at 
> geoip-country-only@1.1.8 postinstall /srv/flood/node_modules/geoip-country-only

[root@darkmedia:/srv/flood]# npm install

> geoip-country-only@1.1.8 postinstall /srv/flood/node_modules/geoip-country-only
> npm run-script updatedb

npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!   stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

> geoip-country-only@1.1.8 updatedb /srv/flood/node_modules/geoip-country-only
> node scripts/updatedb.js

Fetching  https://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/srv/flood/node_modules/geoip-country-only/tmp'
    at Object.fs.mkdirSync (fs.js:885:18)
    at mkdir (/srv/flood/node_modules/geoip-country-only/scripts/updatedb.js:43:6)
    at fetch (/srv/flood/node_modules/geoip-country-only/scripts/updatedb.js:131:2)
    at /srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:1149:20
    at /srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:375:13
    at iterate (/srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:281:9)
    at Object.async.inject.async.foldl.async.reduce (/srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:374:15)
    at /srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:1148:19
    at /srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:166:37
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geoip-country-only@1.1.8 updatedb: `node scripts/updatedb.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geoip-country-only@1.1.8 updatedb script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN flood@1.0.0 No repository field.
npm WARN flood@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! geoip-country-only@1.1.8 postinstall: `npm run-script updatedb`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the geoip-country-only@1.1.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-02T10_32_07_187Z-debug.log
[root@darkmedia:/srv/flood]# mkdir node_modules/geoip-country-only/
[root@darkmedia:/srv/flood]# mkdir node_modules/geoip-country-only/tmo
[root@darkmedia:/srv/flood]# mkdir node_modules/geoip-country-only/tmp
[root@darkmedia:/srv/flood]# npm install

> geoip-country-only@1.1.8 postinstall /srv/flood/node_modules/geoip-country-only
> npm run-script updatedb

npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!   stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
glob error { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
  stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

> geoip-country-only@1.1.8 updatedb /srv/flood/node_modules/geoip-country-only
> node scripts/updatedb.js

Fetching  https://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/srv/flood/node_modules/geoip-country-only/tmp'
    at Object.fs.mkdirSync (fs.js:885:18)
    at mkdir (/srv/flood/node_modules/geoip-country-only/scripts/updatedb.js:43:6)
    at fetch (/srv/flood/node_modules/geoip-country-only/scripts/updatedb.js:131:2)
    at /srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:1149:20
    at /srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:375:13
    at iterate (/srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:281:9)
    at Object.async.inject.async.foldl.async.reduce (/srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:374:15)
    at /srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:1148:19
    at /srv/flood/node_modules/geoip-country-only/node_modules/async/lib/async.js:166:37
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geoip-country-only@1.1.8 updatedb: `node scripts/updatedb.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geoip-country-only@1.1.8 updatedb script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN flood@1.0.0 No repository field.
npm WARN flood@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! geoip-country-only@1.1.8 postinstall: `npm run-script updatedb`
npm ERR! Exit status 243
npm ERR! 
npm ERR! Failed at the geoip-country-only@1.1.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-02T10_32_35_711Z-debug.log

[root@darkmedia:/srv/flood]# cat /root/.npm/_logs/2018-11-02T10_32_35_711Z-debug.log
[truncated module list]
1070 warn ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
1071 warn flood@1.0.0 No repository field.
1072 warn flood@1.0.0 No license field.
1073 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
1074 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
1075 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1075 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1075 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
1075 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1076 verbose stack Error: geoip-country-only@1.1.8 postinstall: `npm run-script updatedb`
1076 verbose stack Exit status 243
1076 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
1076 verbose stack     at emitTwo (events.js:126:13)
1076 verbose stack     at EventEmitter.emit (events.js:214:7)
1076 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1076 verbose stack     at emitTwo (events.js:126:13)
1076 verbose stack     at ChildProcess.emit (events.js:214:7)
1076 verbose stack     at maybeClose (internal/child_process.js:915:16)
1076 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1077 verbose pkgid geoip-country-only@1.1.8
1078 verbose cwd /srv/flood
1079 verbose Linux 4.9.0-7-amd64
1080 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
1081 verbose node v8.12.0
1082 verbose npm  v6.4.1
1083 error code ELIFECYCLE
1084 error errno 243
1085 error geoip-country-only@1.1.8 postinstall: `npm run-script updatedb`
1085 error Exit status 243
1086 error Failed at the geoip-country-only@1.1.8 postinstall script.
1086 error This is probably not a problem with npm. There is likely additional logging output above.
1087 verbose exit [ 243, true ]
[root@darkmedia:/srv/flood]#

**Comment by noraj** [comment]
Hi @geekism 

Thanks for posting your issue, but can you please take time to edit it in order to fill the issue template.
Laso please format the code using markdown code blocks.

```markdown
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.
- [ ] Please check the [F.A.Q.](https://github.com/jfurrow/flood/wiki/F.A.Q.).
- [ ] Please check the [Troubleshooting](https://github.com/jfurrow/flood/wiki/Troubleshooting) wiki section.

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version:
  + Node.js version `node --version`
  + npm version `npm --version`
  + Web browser `name and version`
* Operating System and version:

## Summary
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
<!--- (Optional) Tell us what should happen -->

## Current Behavior
<!--- (Optional) Tell us what happens instead of the expected behavior -->

## Possible Solution
<!--- (Optional) suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- (Optional) What are you trying to accomplish? -->
```

I'm closing the issue until you fill it.

Feel free to ask to re-open it as soon as it's done.

**Comment by noraj** [comment]
Also if you had read the section [Troubleshooting](https://github.com/jfurrow/flood/wiki/Troubleshooting#node-gyp-with-sudo-not-working) you would have read that.

> If you understand the security implications of running any command with sudo, and you are absolutely certain you need sudo, use sudo npm i --unsafe-perm (see here for why --unsafe-perm) else installation will fail. If you don't need sudo just use npm i as usual.

## But this is a very bad idea to install npm packages as root

and you will get tons of problem doing that. So just restarts an installation with a regular user.
