### ISSUE TITLE
geoip county error 404

### ISSUE THREAD

**Issue by noeuse** [jfurrow/flood#750]
> geoip-country-only@1.1.8 postinstall /app/flood/node_modules/geoip-country-only
> npm run-script updatedb

> geoip-country-only@1.1.8 updatedb /app/flood/node_modules/geoip-country-only
> node scripts/updatedb.js

Fetching  https://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip
Retrieving GeoIPCountryCSV.zip .../app/flood/node_modules/geoip-country-only/scripts/updatedb.js:111
                        console.log('ERROR'.red + ': HTTP Request Failed [%d %s]', status, https.STATUS_CODES[status]);
                                                                                                             ^

TypeError: Cannot read property '404' of undefined

**Comment by noraj** [comment]
Hi @noeuse  

Thanks for posting your issue, but can you please take time to edit it in order to fill the issue template.
Laso please format the code using markdown code blocks.

```markdown
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.
- [ ] Please check the [F.A.Q.](https://github.com/jfurrow/flood/wiki/F.A.Q.).
- [ ] Please check the [Troubleshooting](https://github.com/jfurrow/flood/wiki/Troubleshooting) wiki section.

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version:
  + Node.js version `node --version`
  + npm version `npm --version`
  + Web browser `name and version`
* Operating System and version:

## Summary
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
<!--- (Optional) Tell us what should happen -->

## Current Behavior
<!--- (Optional) Tell us what happens instead of the expected behavior -->

## Possible Solution
<!--- (Optional) suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- (Optional) What are you trying to accomplish? -->
```

I'm closing the issue until you fill it.

Feel free to ask to re-open it as soon as it's done.
