### ISSUE TITLE
RSS filter

### ISSUE THREAD

**Issue by fsamareanu** [jfurrow/flood#757]
Type: Question

## Question

I have the following regex that works in transmission rss but I'm unable to figure out how flood expects it to be written:

^(.(?!(?i)E([0-9]{1,2})(?-i)))*$

I have tried the following combinations:

A: `Match .*[\s\S]* Exclude .*(E([0-9]{1,2}))*` -> No results
B: `Match .*(.!(E([0-9]{1,2})))*` -> Matches the format of the files I don't want despite the "!"
C: `Match .*[\s\S]* Exclude ((e|E)([0-9]{1,2}))` -> No results

My goal is to exclude from the RSS feed every individual episode and only retrieve full packs. So anything that's like SXXEYY should be excluded from being added to rtorrent. Any clues?

EDIT: Answering my own question - this seems to be working:

`Match (.*) Exclude (E([0-9]{1,2}))`

**Comment by noraj** [comment]
https://github.com/jfurrow/flood/issues/541

**Comment by fsamareanu** [comment]
None of the suggestions in #541 applies and I tried restarting.

**Comment by noraj** [comment]
I agree, a PR or a Wiki edit would be much welcomed.
Also you said you succeed with `Match (.*) Exclude (E([0-9]{1,2}))`
