### ISSUE TITLE
folder not deleted when Remove torrent, just files under it

### ISSUE THREAD

**Issue by euri10** [jfurrow/flood#760]
Type: Bug Report

- [x] Try to follow the update procedure described in the README and try again before opening this issue.
- [x] Please check the [F.A.Q.](https://github.com/jfurrow/flood/wiki/F.A.Q.).
- [x] Please check the [Troubleshooting](https://github.com/jfurrow/flood/wiki/Troubleshooting) wiki section.

## Your Environment

* Version used:
  + Version (stable release) `?`
  + Commit ID (development release) `2cd1aa63e70c15640f9007452b3b987eabd9c7b5`
* Environment name and version:
  + Node.js version `v10.1.0`
  + npm version `5.6.0`
  + Web browser `Version 72.0.3626.53 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)`
* Operating System and version:
`Debian buster`
## Summary

When clicking Remove on a torrent with Torrent data checkbox checked, all the files are well erased but the containing folder stays

## Expected Behavior

The containing folder if it's part of the said torrent should be deleted as well

## Steps to Reproduce

1.
2.
3.
4.

**Comment by fsamareanu** [comment]
Can confirm this one on the latest git.

**Comment by bbashy** [comment]
See #399 and #466
