### ISSUE TITLE
Flood server stuck at starting

### ISSUE THREAD

**Issue by DominicMe** [jfurrow/flood#765]
I am trying to install flood and got it to run once and was able to connect to rtorrent but now that I am trying to install it permanently I cannot get it to even start.

Here are the steps I took on Fedora 29:

```
sudo dnf install nodejs npm
sudo mkdir /usr/share/webapps/flood

git clone https://github.com/jfurrow/flood.git /usr/share/webapps/flood

cd /usr/share/webapps/flood
cp config.template.js config.js

npm install
npm run build
npm start
```

After the last command I just get:

```
> flood@1.0.0 start /mnt/downloads/rtorrent/flood
> node server/bin/start.js

Flood server starting on http://127.0.0.1:3600.
```

During the several re-installs I also ran the following in case it matters:

npm install -g node-gyp

Co log file is created and I did try several different ports and rebooted few times already. What can be causing this?

**Comment by noraj** [comment]
Hi @DominicMe Thanks for posting your issue, but can you please take time to edit it in order to fill the issue template.  Those information is very important for the developer else he won't be able to reproduce anything.

```markdown
Type: Bug Report

- [ ] Try to follow the update procedure described in the README and try again before opening this issue.
- [ ] Please check the [F.A.Q.](https://github.com/jfurrow/flood/wiki/F.A.Q.).
- [ ] Please check the [Troubleshooting](https://github.com/jfurrow/flood/wiki/Troubleshooting) wiki section.

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used:
  + Version (stable release) `git --no-pager tag`
  + Commit ID (development release) `git --no-pager log -1`
* Environment name and version:
  + Node.js version `node --version`
  + npm version `npm --version`
  + Web browser `name and version`
* Operating System and version:

## Summary
<!--- Provide a general summary of the issue in the Title above -->

## Expected Behavior
<!--- (Optional) Tell us what should happen -->

## Current Behavior
<!--- (Optional) Tell us what happens instead of the expected behavior -->

## Possible Solution
<!--- (Optional) suggest a fix/reason for the bug, -->
<!--- or ideas how to implement the addition or change -->

## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Context
<!--- (Optional) What are you trying to accomplish? -->
```

I'm closing the issue until you fill it.

Feel free to ask to re-open it as soon as it's done.

**Comment by noraj** [comment]
Have you searched for existing issues: take a look at https://github.com/jfurrow/flood/issues/761 or https://github.com/jfurrow/flood/issues/435 or maybe https://github.com/jfurrow/flood/issues/674

Did you searched in the Wiki ? Check https://github.com/jfurrow/flood/wiki/Troubleshooting#stuck-after-log-in

**Comment by DominicMe** [comment]
I knew immediately after seeing the post that it was that I forgot to change 127.0.0.1 to 0.0.0.0 this time. Confirmed it now and it's working. It is quite confusing that it just shows "Flood server starting on ..." and nothing else until you access the web interface instead of "server running" or something along those lines.
