### ISSUE TITLE
File & Folder not deleted

### ISSUE THREAD

**Issue by JamesAdams92150** [jfurrow/flood#775]
Hi,

I have a problème, when i delete my torrent on the flood interface my file is not deleted

![Capture](https://user-images.githubusercontent.com/20860324/54785976-e6230100-4c27-11e9-8a82-4b9d384e136b.PNG)

Is it a permission error ?

**Comment by JamesAdams92150** [comment]
I add the line in the .rtorrent.rc

system.umask.set = 002

**Comment by zuosc** [comment]
why set system.umask.set = 002 is ok?   And the default setting is  system.umask.set = 0022  

And I set uid and gid is 0

this is why?
