### ISSUE TITLE
total giga of torrent present

### ISSUE THREAD

**Issue by JamesAdams92150** [jfurrow/flood#778]
Hi,

it would be nice to have the total in giga of the present torrent on the interface :D

**Comment by noraj** [comment]
Hi @JamesAdams92150 , Thanks for posting your issue, but can you please take time to edit it in order to fill the issue template.

I'm closing the issue until you fill it.

Feel free to ask to re-open it as soon as it's done.

**Comment by noraj** [comment]
Also I suggest you to describe more precisely your idea. Thx
