### ISSUE TITLE
Add mediainfo support

### ISSUE THREAD

**Issue by maximuml** [jfurrow/flood#85]
Will be mediainfo and geoip available in flood?

**Comment by jfurrow** [comment]
Yes, absolutely! I will add this soon.

**Comment by jfurrow** [comment]
Mediainfo support is almost here, you can track it here: https://github.com/jfurrow/flood/pull/170
I created a separate issue for GeoIP support: https://github.com/jfurrow/flood/issues/171

**Comment by jfurrow** [comment]
Mediainfo support is merged!

**Comment by maximuml** [comment]
error for single file


Trace: { error:
   { [Error: stdout maxBuffer exceeded]
     cmd: 'mediainfo /home/rtorrent/downloads/hdd2/HDTV_PRO' } }
    at /home/flood/server/util/ajaxUtil.js:7:17
    at /home/flood/server/util/mediainfo.js:26:15
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
GET /api/mediainfo?hash=EFF762F8408D395F0D3080EA62A0DA908D9EA9DD 500 37637.223 ms - 75

**Comment by jfurrow** [comment]
@maximuml please track this in https://github.com/jfurrow/flood/issues/187 and provide any additional details.
